// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Apply a GD-alignment delay to existing FIR coefficients.
///
/// This is used when a production path has already generated FIRs before the
/// room-level GD target is known. It mirrors the delay handling in
/// `generate_fir_correction_with_gd_target` so both paths encode the same
/// sample-domain shift into the convolution IR.
pub(crate) fn apply_gd_delay_to_fir_coefficients(
    coeffs: &[f64],
    delay_ms: f64,
    sample_rate: f64,
) -> Vec<f64> {
    if delay_ms.abs() <= 1e-6 {
        return coeffs.to_vec();
    }
    let delay_samples = delay_ms * 1e-3 * sample_rate;
    apply_fractional_sample_shift(coeffs, delay_samples)
}

/// Shift FIR coefficients by a given number of samples (positive = later).
/// Pads with zeros on the appropriate side and truncates to maintain length.
#[allow(dead_code)]
pub(super) fn apply_sample_shift(coeffs: &[f64], shift: isize) -> Vec<f64> {
    let n = coeffs.len();
    let mut shifted = vec![0.0; n];

    if shift >= 0 {
        let s = shift as usize;
        if s < n {
            shifted[s..n].copy_from_slice(&coeffs[..(n - s)]);
        }
    } else {
        let s = (-shift) as usize;
        let len = n.saturating_sub(s);
        if len > 0 {
            shifted[..len].copy_from_slice(&coeffs[s..s + len]);
        }
    }

    shifted
}

/// Shift FIR coefficients by a fractional number of samples using linear
/// interpolation. Positive shift = later (delays the signal).
pub(super) fn apply_fractional_sample_shift(coeffs: &[f64], shift: f64) -> Vec<f64> {
    let n = coeffs.len();
    if shift.abs() < 1e-9 {
        return coeffs.to_vec();
    }
    let mut shifted = vec![0.0; n];
    #[allow(clippy::needless_range_loop)]
    for i in 0..n {
        let src = i as f64 - shift;
        let idx = src.floor();
        let frac = src - idx;
        let idx = idx as isize;
        if idx < 0 || idx >= n as isize {
            continue;
        }
        let v0 = coeffs[idx as usize];
        if frac.abs() < 1e-9 || idx + 1 >= n as isize {
            shifted[i] = v0;
        } else {
            let v1 = coeffs[(idx + 1) as usize];
            shifted[i] = (1.0 - frac) * v0 + frac * v1;
        }
    }
    shifted
}
