// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::lerp_exp;

/// Map a quality level (0.0 = fast, 1.0 = maximum) to population and maxeval.
/// Used by the Intermediate mode quality slider.
pub fn quality_to_optimizer_params(quality: f32) -> (usize, usize) {
    let quality = quality.clamp(0.0, 1.0);
    // Exponential interpolation for perceptually linear slider
    let population = lerp_exp(30.0, 300.0, quality) as usize;
    let maxeval = lerp_exp(1000.0, 50000.0, quality) as usize;
    (population, maxeval)
}

/// User-facing label for a quality level.
pub fn quality_label(quality: f32) -> &'static str {
    if quality < 0.2 {
        "Fast (seconds)"
    } else if quality < 0.5 {
        "Balanced (minutes)"
    } else if quality < 0.8 {
        "Thorough (slow)"
    } else {
        "Maximum (very slow)"
    }
}

