// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::inline_measurement::InlineMeasurement;
use super::measurement_ref::MeasurementRef;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Single measurement with metadata
///
/// Custom implementation to support both string path and object with speaker_name
#[derive(Debug, Clone, JsonSchema)]
pub struct MeasurementSingle {
    pub measurement: MeasurementRef,
    pub speaker_name: Option<String>,
}

impl Serialize for MeasurementSingle {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if self.speaker_name.is_none() {
            // No metadata, serialize as the inner ref (might be string or object)
            self.measurement.serialize(serializer)
        } else {
            // Has metadata, must serialize as object
            use serde::ser::SerializeMap;
            let mut map = serializer.serialize_map(None)?;
            match &self.measurement {
                MeasurementRef::Path(p) => {
                    map.serialize_entry("path", p)?;
                }
                MeasurementRef::Named { path, name } => {
                    map.serialize_entry("path", path)?;
                    if let Some(n) = name {
                        map.serialize_entry("name", n)?;
                    }
                }
                MeasurementRef::Inline(inline) => {
                    // Inline is already an object, but we can't easily merge without duplicating fields
                    // or using a temporary value.
                    map.serialize_entry("inline", inline)?;
                }
            }
            map.serialize_entry("speaker_name", &self.speaker_name)?;
            map.end()
        }
    }
}

impl<'de> Deserialize<'de> for MeasurementSingle {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            path: Option<PathBuf>,
            name: Option<String>,
            inline: Option<InlineMeasurement>,
            speaker_name: Option<String>,
        }

        let value = serde_json::Value::deserialize(deserializer)?;

        if value.is_string() {
            // Case: "path/to/file.csv"
            let path = value.as_str().unwrap().into();
            return Ok(MeasurementSingle {
                measurement: MeasurementRef::Path(path),
                speaker_name: None,
            });
        }

        if let Ok(helper) = serde_json::from_value::<Helper>(value.clone()) {
            let speaker_name = helper.speaker_name;

            if let Some(inline) = helper.inline {
                return Ok(MeasurementSingle {
                    measurement: MeasurementRef::Inline(inline),
                    speaker_name,
                });
            }

            if let Some(path) = helper.path {
                if let Some(name) = helper.name {
                    return Ok(MeasurementSingle {
                        measurement: MeasurementRef::Named {
                            path,
                            name: Some(name),
                        },
                        speaker_name,
                    });
                } else {
                    return Ok(MeasurementSingle {
                        measurement: MeasurementRef::Path(path),
                        speaker_name,
                    });
                }
            }
        }

        // Fallback to trying to parse as MeasurementRef if it doesn't match our helper
        let measurement = serde_json::from_value(value).map_err(serde::de::Error::custom)?;
        Ok(MeasurementSingle {
            measurement,
            speaker_name: None,
        })
    }
}
