// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::alloc::{GlobalAlloc, Layout, System};
use std :: sync :: atomic :: { Ordering } ;
use super::misc::ALLOC_COUNT;
use super::misc::COUNTING_ENABLED;

pub struct CountingAlloc;

/// # Safety
/// This implementation is safe as it only increments an atomic counter.
/// It uses `System` allocator for the actual memory operations.
unsafe impl GlobalAlloc for CountingAlloc {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        if COUNTING_ENABLED.load(Ordering::Relaxed) {
            ALLOC_COUNT.fetch_add(1, Ordering::Relaxed);
        }
        unsafe { System.alloc(layout) }
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        unsafe { System.dealloc(ptr, layout) }
    }
}

