//! Shared memory interface for communication with Swift HAL driver
//!
//! This module provides a Rust interface to the shared memory region
//! created by the Swift HAL driver for audio data exchange.
//!
//! # Cross-process memory model
//!
//! Every field in [`SharedAudioHeader`] that may be touched by both the daemon
//! (this crate) and the Swift HAL plugin running inside `coreaudiod` is an
//! atomic type (`AtomicU32`/`AtomicU64`). Plain non-atomic stores from one
//! process while the other process is reading the same word would be a data
//! race in the Rust/C++ abstract machines (undefined behaviour), so we publish
//! every cross-process value through `store(_, Ordering::Release)` and consume
//! it via `load(Ordering::Acquire)`. The Swift side performs equivalent
//! atomic accesses via `std::atomic`.
//!
//! The `key_fingerprint` is exposed externally as an `[u8; 8]` but stored as
//! an `AtomicU64` in big-endian byte order so that the 8 bytes are published
//! in a single atomic store.
//!
//! # Reconfiguration protocol
//!
//! Geometry changes go through [`SharedAudioBuffer::reconfigure_quiesced`]
//! which uses a `configuring` handshake flag:
//!
//! 1. Daemon stores `configuring = 1` (Release).
//! 2. Daemon spins briefly so the writer can drain its IO cycle.
//! 3. Daemon publishes new geometry and resets ring positions.
//! 4. Daemon sets `config_changed = 1` so the writer reloads geometry.
//! 5. Daemon clears `configuring = 0`.
//!
//! The legacy `set_sample_rate` / `set_buffer_frames` / `set_channel_count`
//! setters route through this path so they no longer race the HAL writer.

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::sync::atomic::{AtomicU32, AtomicU64};

mod consts;
mod current;
mod encrypted;
mod ensure;
mod grant;
mod hal_input_reader;
mod hal_output_writer;
mod misc;
mod shared_audio_buffer;
mod types;
mod validate;
#[cfg(test)]
mod tests;

pub use consts::*;
pub use hal_input_reader::*;
pub use hal_output_writer::*;
pub use misc::*;
pub use shared_audio_buffer::*;

/// Header structure for shared memory region.
///
/// Must match the Swift side exactly. All cross-process fields are atomic
/// (`AtomicU32`/`AtomicU64`). `AtomicU32` and `AtomicU64` have the same
/// memory layout and alignment as plain `u32`/`u64` (guaranteed by the
/// standard library), so the byte layout remains compatible with the
/// Swift `struct SharedAudioHeader` mirror.
#[repr(C, align(8))]
pub struct SharedAudioHeader {
    /// Magic number for validation (0x534F5446 = 'SOTF')
    pub magic: AtomicU32,
    /// Protocol version
    pub version: AtomicU32,
    /// Current sample rate in Hz
    pub sample_rate: AtomicU32,
    /// Frames per buffer
    pub buffer_frames: AtomicU32,
    /// Number of audio channels
    pub channel_count: AtomicU32,

    // Ring buffer state (atomic)
    /// Write position in samples
    pub write_position: AtomicU64,
    /// Read position in samples
    pub read_position: AtomicU64,

    // Control flags (atomic)
    /// IO is running
    pub active: AtomicU32,
    /// Configuration changed (engine should reload)
    pub config_changed: AtomicU32,
    /// Driver is initialized and ready
    pub driver_ready: AtomicU32,
    /// Rust engine is connected and ready
    pub engine_ready: AtomicU32,

    // Encryption fields (version 2+)
    /// Encryption enabled flag: 0 = disabled, 1 = enabled
    pub encrypted: AtomicU32,
    /// First 8 bytes of SHA256 hash of the encryption key, stored in
    /// big-endian byte order (so `to_be_bytes` gives the canonical 8-byte
    /// fingerprint).
    pub key_fingerprint: AtomicU64,
    /// Frame counter for nonce generation (monotonically increasing, never reuse!)
    pub frame_counter: AtomicU64,

    // Config negotiation fields (version 3+)
    /// Requested sample rate (set by requester, either HAL or Daemon)
    pub requested_sample_rate: AtomicU32,
    /// Requested buffer frames (set by requester)
    pub requested_buffer_frames: AtomicU32,
    /// Actual sample rate in use (set by responder after negotiation)
    pub actual_sample_rate: AtomicU32,
    /// Actual buffer frames in use (set by responder after negotiation)
    pub actual_buffer_frames: AtomicU32,
    /// Config status: 0=pending, 1=accepted, 2=negotiated, 3=error
    pub config_status: AtomicU32,
    /// Config source: 1=HAL initiated, 2=Daemon initiated
    pub config_source: AtomicU32,
    /// Error code if config_status=3
    pub config_error_code: AtomicU32,

    // Statistics
    /// Number of times encrypted write failed due to insufficient buffer space
    pub encryption_overflow_count: AtomicU64,
    /// Daemon liveness heartbeat in Unix epoch milliseconds.
    pub daemon_heartbeat_ms: AtomicU64,

    // Reconfiguration handshake (version 5+)
    /// 1 while the daemon is performing a quiesced reconfiguration. The
    /// Swift HAL plugin must drop any pending write and refrain from
    /// publishing new `write_position` values while this is set.
    pub configuring: AtomicU32,
}

