# ----------------------------------------------------------------------
# BUILD MATH
# ----------------------------------------------------------------------

[group('build')]
prod-math:
	cargo build --release --bin plot_functions
	cargo build --release --bin plot-autoeq-de
	cargo build --release --bin run-autoeq-de

# ----------------------------------------------------------------------
# BENCH MATH
# ----------------------------------------------------------------------

[group('bench')]
bench-math:
	cargo run --release --bin benchmark-convergence

# ----------------------------------------------------------------------
# DOWNLOAD
# ----------------------------------------------------------------------

[group('download')]
generate-ml-dataset-muslan:
	mkdir -p data_cached/com.google.research; \
	wget -Odata_cached/com.google.research/muslan.tar.gz https://openslr.org/resources/17/musan.tar.gz

[group('download')]
generate-ml-dataset-ava:
	mkdir -p data_cached/com.google.research; \
	wget -Odata_cached/com.google.research/ava_speech_labels_v1.csv \
	   https://research.google.com/ava/download/ava_speech_labels_v1.csv



# ----------------------------------------------------------------------
# EXAMPLES
# ----------------------------------------------------------------------

[group('examples')]
examples-math: examples-iir examples-de examples-testfunctions

[group('examples')]
examples-iir :
	cargo run --release --example format_demo
	cargo run --release --example readme_example

[group('examples')]
examples-de :
	cargo run --release --example optde_basic
	cargo run --release --example optde_adaptive_demo
	cargo run --release --example optde_linear_constraints
	cargo run --release --example optde_nonlinear_constraints
	cargo run --release --example optde_parallel

[group('examples')]
examples-testfunctions:
	cargo run --release --example test_hartman_4d

# ----------------------------------------------------------------------
# QA MATH
# ----------------------------------------------------------------------

[group('qa-math')]
qa-math:

# ----------------------------------------------------------------------
# PUBLISH MATH
# ----------------------------------------------------------------------

[group('publish')]
publish-math:
	cd crates/math-test-functions && cargo publish
	cd crates/math-optimisation && cargo publish
	cd crates/math-iir-fir && cargo publish

