# ----------------------------------------------------------------------
# BUILD MATH
# ----------------------------------------------------------------------

[group('build')]
prod-math:
	cargo build --release --bin plot-functions -p math-test-functions --features plotly
	cargo build --release --bin plot-de -p math-optimisation --features plotly
	cargo build --release --bin run-de -p math-optimisation
	cargo build --release --bin wav2csv -p math-dsp
	cargo build --release --bin simd-fuzzer -p math-dsp

# ----------------------------------------------------------------------
# BENCH MATH
# ----------------------------------------------------------------------

[group('bench')]
bench-math:
	cargo run --release --bin benchmark-convergence
	cargo run --release --bin biquad-bench

# ----------------------------------------------------------------------
# DOWNLOAD
# ----------------------------------------------------------------------

[group('download')]
generate-ml-dataset-muslan:
	mkdir -p data_cached/com.google.research; \
	wget -Odata_cached/com.google.research/muslan.tar.gz https://openslr.org/resources/17/musan.tar.gz

[group('download')]
generate-ml-dataset-ava:
	mkdir -p data_cached/com.google.research; \
	wget -Odata_cached/com.google.research/ava_speech_labels_v1.csv \
	   https://research.google.com/ava/download/ava_speech_labels_v1.csv



# ----------------------------------------------------------------------
# EXAMPLES
# ----------------------------------------------------------------------

[group('examples')]
examples-math: examples-iir examples-optimisation examples-testfunctions

[group('examples')]
examples-iir :
	cargo run --release --example format_demo -p math-iir-fir
	cargo run --release --example format_rme_room_demo -p math-iir-fir
	cargo run --release --example readme_example -p math-iir-fir
	cargo run --release --example fir_example -p math-iir-fir
	cargo run --release --example peq_loudness_compensation -p math-iir-fir

[group('examples')]
examples-optimisation :
	cargo run --release --example optde_basic -p math-optimisation
	cargo run --release --example optde_adaptive_demo -p math-optimisation
	cargo run --release --example optde_linear_constraints -p math-optimisation
	cargo run --release --example optde_nonlinear_constraints -p math-optimisation
	cargo run --release --example optde_parallel -p math-optimisation

[group('examples')]
examples-testfunctions:
	cargo run --release --example test_hartman-4d -p math-test-functions
	cargo run --release --example test_new-sfu-functions -p math-test-functions

# ----------------------------------------------------------------------
# QA MATH
# ----------------------------------------------------------------------

[group('qa-math')]
qa-math:
	cargo run --release --bin simd-fuzzer -p math-dsp

# ----------------------------------------------------------------------
# PUBLISH MATH
# ----------------------------------------------------------------------

[group('publish')]
publish-math:
	cd crates/math-test-functions && cargo publish
	cd crates/math-optimisation && cargo publish
	cd crates/math-iir-fir && cargo publish

