// Auto-generated by r2factor. Manual edits will be overwritten on next split.


/// Canonical error string returned when the recording-side cancel flag
/// is observed during a capture. Stable so UI code can match on it.
pub const CANCELLED_ERR: &str = "cancelled";

/// Default level for auxiliary recording stimuli (delay probe and bass anchor).
///
/// These are short/narrowband signals and are noticeably quieter than sweeps
/// when played at the same peak level, so keep the historical 0.5 linear
/// amplitude default unless a caller explicitly chooses otherwise.
pub const DEFAULT_AUXILIARY_SIGNAL_LEVEL_DB: f32 = -6.0206;

/// Default MLS order for recording workflows.
pub const DEFAULT_MLS_ORDER: u8 = 16;

/// Fixed seed for allpass probe generation — ensures the same probe is used
/// for generation and matched-filter detection.
pub const PROBE_SEED: u64 = 0xDEAD_BEEF_CAFE_1337;

