[workspace]
members = [
    "src-tauri"
]
resolver = "2"

[workspace.dependencies]
# Core numerical computing
ndarray = { version = "0.16.0", features = ["blas", "serde"] }
blas-src = { version = "0.12.1" }
# Use static feature for Windows to build OpenBLAS from source
# Use system feature for Unix to link to system OpenBLAS
openblas-src = { version = "0.10", features = ["cblas", "static"] }

# Serialization and data
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async and networking
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.23", features = ["json"] }
urlencoding = "2.1"

# Plotting and visualization
plotly = { version = "0.13", features = ["static_export_default"] }

# Tauri (UI framework)
tauri = { version = "2.8", features = [] }
tauri-build = { version = "2.4", features = [] }
tauri-plugin-dialog = "2.4"
tauri-plugin-opener = "2.5"

[workspace.metadata.cross.target.aarch64-unknown-linux-gnu]
# Install libssl-dev:arm64, see <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "apt update && apt -y upgrade && apt install --assume-yes pkg-config libssl-dev cmake libgdk3.0-cil-dev"
]
