// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::mpd_play_state::MpdPlayState;

/// Status snapshot returned by the adapter.
pub struct MpdStatus {
    pub volume: u8, // 0-100
    pub repeat: bool,
    pub random: bool,
    pub single: bool,
    pub consume: bool,
    pub state: MpdPlayState,
    /// Current song position in playlist (0-indexed).
    pub song: Option<u32>,
    /// Current song ID.
    pub songid: Option<u32>,
    /// Elapsed time in seconds.
    pub elapsed: f64,
    /// Total duration in seconds.
    pub duration: f64,
    /// Audio format string: "samplerate:bits:channels"
    pub audio: Option<String>,
    /// Playlist length.
    pub playlist_length: u32,
    /// Playlist version (incremented on changes).
    pub playlist_version: u32,
}

/// Directory entry for lsinfo.
pub struct MpdDirEntry {
    pub is_directory: bool,
    pub path: String,
}
