[package]
name = "sotf-dlna"
description = "DLNA/UPnP MediaRenderer and MediaServer for SOTF"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
log = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "macros", "sync", "rt", "time"] }
uuid = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
proptest = { workspace = true }
