// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use gpui::*;
use sotf_audio_player :: { Player } ;
use std::collections::VecDeque;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::OnceLock;
use super::types::RemoteCommand;

/// Global handle to the player so C FFI callbacks can control playback.
/// Set once during app initialization, never changes.
pub(super) static GLOBAL_PLAYER: OnceLock<Arc<parking_lot::Mutex<Player>>> = OnceLock::new();

pub(super) static PENDING_REMOTE_COMMANDS: OnceLock<parking_lot::Mutex<VecDeque<RemoteCommand>>> =
    OnceLock::new();

pub(super) static PENDING_IMPORTED_FILES: OnceLock<parking_lot::Mutex<Vec<PathBuf>>> = OnceLock::new();

pub(super) static PENDING_QR_PAYLOADS: OnceLock<parking_lot::Mutex<VecDeque<String>>> = OnceLock::new();

