//! Differential Evolution optimization library.
//!
//! This crate provides a Rust implementation of the Differential Evolution (DE)
//! algorithm, a population-based stochastic optimizer for continuous optimization
//! problems. It also includes CMA-ES for coupled continuous landscapes and
//! NSGA-II/NSGA-III for real Pareto multi-objective search.
//!
//! # Features
//!
//! - Multiple mutation strategies (Best1, Rand1, CurrentToBest1, etc.)
//! - Binomial and exponential crossover
//! - Adaptive parameter control (SHADE-style)
//! - **L-SHADE**: Linear population size reduction for faster convergence
//! - **External Archive**: Maintains diversity by storing discarded solutions
//! - **Current-to-pbest/1**: SHADE mutation strategy for balanced exploration
//! - Parallel population evaluation
//! - Constraint handling via penalty methods
//! - Latin Hypercube initialization
//! - CMA-ES with full covariance adaptation
//! - NSGA-II/III Pareto-front optimizers
//!
//! # Example
//!
//! ```rust
//! use math_audio_optimisation::{differential_evolution, DEConfigBuilder};
//!
//! // Minimize the sphere function: f(x) = sum(x_i^2)
//! let bounds = vec![(-5.0, 5.0), (-5.0, 5.0)];
//! let config = DEConfigBuilder::new()
//!     .maxiter(100)
//!     .seed(42)
//!     .build()
//!     .expect("invalid config");
//!
//! let result = differential_evolution(
//!     &|x| x.iter().map(|&xi| xi * xi).sum(),
//!     &bounds,
//!     config,
//! ).expect("optimization should succeed");
//!
//! assert!(result.fun < 1e-6);
//! ```
//!
//! # L-SHADE Example
//!
//! ```rust
//! use math_audio_optimisation::{differential_evolution, DEConfigBuilder, Strategy, LShadeConfig};
//!
//! let bounds = vec![(-5.0, 5.0), (-5.0, 5.0)];
//! let lshade_config = LShadeConfig {
//!     np_init: 18,
//!     np_final: 4,
//!     p: 0.11,
//!     arc_rate: 2.1,
//!     ..Default::default()
//! };
//!
//! let config = DEConfigBuilder::new()
//!     .maxiter(100)
//!     .strategy(Strategy::LShadeBin)
//!     .lshade(lshade_config)
//!     .seed(42)
//!     .build()
//!     .expect("invalid config");
//!
//! let result = differential_evolution(
//!     &|x| x.iter().map(|&xi| xi * xi).sum(),
//!     &bounds,
//!     config,
//! ).expect("optimization should succeed");
//!
//! assert!(result.fun < 1e-6);
//! ```
#![doc = include_str!("../README.md")]
#![doc = include_str!("../REFERENCES.md")]
#![warn(missing_docs)]

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub use bayesian::{
    BayesAcquisition, BayesOptCallback, BayesOptConfig, BayesOptIntermediate, BayesOptParetoReport,
    BayesOptReport, BayesParetoSolution, bayesian_multi_objective, bayesian_optimization,
};
pub use cmaes::{CmaEsConfig, CmaEsIntermediate, CmaEsReport, cma_es};
pub use cobyla::{CobylaConfig, CobylaConstraint, CobylaReport, CobylaStopTols};
pub use continuous_area::{
    AreaError, AreaScalarisation, Prior, Quadrature, build_quadrature_points, evaluate_area_loss,
    try_evaluate_area_loss,
};
pub use differential_evolution::differential_evolution;
pub use error::{DEError, Result};
pub use external_archive::ExternalArchive;
pub use isres::{IsresConfig, IsresConstraint, IsresReport, isres};
pub use levenberg_marquardt::{
    LMCallbackAction, LMConfig, LMConfigBuilder, LMError, LMIntermediate, LMReport, LMResult,
    levenberg_marquardt,
};
pub use lshade::LShadeConfig;
pub use nsga::{NsgaConfig, NsgaReport, NsgaVariant, ParetoSolution, nsga, nsga2, nsga3};
pub use parallel_eval::ParallelConfig;
pub use recorder::{OptimizationRecord, OptimizationRecorder};
pub use run_recorded::run_recorded_differential_evolution;

/// Integer variable handling for mixed-integer optimization.
pub mod apply_integrality;
/// Wrapper Local Search (WLS) application for local refinement.
pub mod apply_wls;
mod argmin;
/// Gaussian-process Bayesian optimizers for expensive objectives.
pub mod bayesian;
/// Pure-Rust CMA-ES global optimizer.
pub mod cmaes;
/// Pure-Rust COBYLA local optimizer.
///
/// Hand-translated from NLopt 2.7.1's `cobyla.c` (Powell 1994) — see
/// [`cobyla_native`] for the implementation. The public API lives in
/// [`cobyla`].
pub mod cobyla;
mod cobyla_native;
/// Continuous-prior loss integration for spatial / area-based optimization
/// (expected value, worst-case, CVaR over a [`continuous_area::Prior`]).
pub mod continuous_area;
/// Binomial (uniform) crossover implementation.
pub mod crossover_binomial;
/// Exponential crossover implementation.
pub mod crossover_exponential;
/// Main differential evolution algorithm implementation.
pub mod differential_evolution;
/// Utilities for selecting distinct random indices from a population.
pub mod distinct_indices;
pub mod error;
/// External archive for L-SHADE algorithm.
pub mod external_archive;
/// Registry of standard test functions for benchmarking.
pub mod function_registry;
/// Internal helper functions for DE implementation.
pub mod impl_helpers;
/// Latin Hypercube Sampling initialization strategy.
pub mod init_latin_hypercube;
/// Random uniform initialization strategy.
pub mod init_random;
/// Sobol quasi-random initialization strategy.
pub mod init_sobol;
/// Pure-Rust ISRES global constrained optimizer.
pub mod isres;
pub mod levenberg_marquardt;
/// L-SHADE configuration.
pub mod lshade;
/// Metadata-driven optimization examples and tests.
pub mod metadata;
/// Adaptive mutation strategy with dynamic parameter control.
pub mod mutant_adaptive;
/// Best/1 mutation strategy: uses best individual plus one difference vector.
pub mod mutant_best1;
/// Best/2 mutation strategy: uses best individual plus two difference vectors.
pub mod mutant_best2;
/// Current-to-best/1 mutation: blends current with best individual.
pub mod mutant_current_to_best1;
/// Current-to-pbest/1 mutation: blends current with p-best individual (SHADE).
pub mod mutant_current_to_pbest1;
/// Rand/1 mutation strategy: uses random individual plus one difference vector.
pub mod mutant_rand1;
/// Rand/2 mutation strategy: uses random individual plus two difference vectors.
pub mod mutant_rand2;
/// Rand-to-best/1 mutation: blends random with best individual.
pub mod mutant_rand_to_best1;
/// Pure-Rust NSGA-II/III multi-objective optimizers.
pub mod nsga;
/// Parallel population evaluation support.
pub mod parallel_eval;
/// Optimization recording for analysis and debugging.
pub mod recorder;
/// Recorded optimization wrapper for testing.
pub mod run_recorded;
/// Linear penalty stacking utilities for combining multiple constraints.
pub mod stack_linear_penalty;

mod adaptive_config;
mod adaptive_state;
mod deconfig;
mod deconfig_builder;
mod dereport;
mod differential_evolution_mod;
mod linear_constraint_helper;
mod mutation;
mod nonlinear_constraint_helper;
mod strategy;
#[cfg(test)]
mod tests;
mod types;

pub use adaptive_config::*;
pub use deconfig::*;
pub use deconfig_builder::*;
pub use dereport::*;
pub use differential_evolution_mod::*;
pub use linear_constraint_helper::*;
pub use mutation::*;
pub use nonlinear_constraint_helper::*;
pub use strategy::*;
pub use types::*;
