// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub(super) const DSF_HEADER_LEN: usize = 12;

pub(super) const DSF_ROOT_CHUNK_SIZE: usize = 28;

pub(super) const DSF_FMT_CHUNK_SIZE: usize = 52;

pub(super) const DFF_HEADER_LEN: usize = 12;

pub(super) const DSD_TO_PCM_DECIMATION: u64 = 64;

pub(super) const DSD_DECODE_CHUNK_FRAMES: u64 = 4096;

pub(super) fn pcm_sample_from_ones(ones: u32) -> f32 {
    ((ones as f32 * 2.0) - DSD_TO_PCM_DECIMATION as f32) / DSD_TO_PCM_DECIMATION as f32
}
