// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::types::OptimizerConfig;
use crate::Curve;
use crate::loss::DriversLossData;
use math_audio_iir_fir::{Biquad, BiquadFilterType};
use ndarray::Array1;
use num_complex::Complex64;
use std::error::Error;
use std::f64::consts::PI;

pub(super) fn allpass_frequency_bounds(
    config: &OptimizerConfig,
) -> Result<(f64, f64), Box<dyn Error>> {
    let min_freq = config.min_freq.max(20.0);
    let max_freq = config.max_freq.min(200.0);
    if max_freq <= min_freq {
        return Err(format!(
            "Multi-sub all-pass optimization requires a non-zero frequency range after clamping to 20-200 Hz, got [{min_freq:.1}, {max_freq:.1}] Hz"
        )
        .into());
    }
    Ok((min_freq, max_freq))
}

/// Compute combined multi-sub response with per-sub all-pass filters.
pub(super) fn compute_combined_with_allpass(
    data: &DriversLossData,
    gains: &[f64],
    delays: &[f64],
    allpass_filters: &[(f64, f64)],
    sample_rate: f64,
) -> Array1<f64> {
    let n_drivers = data.drivers.len();

    // Prepare driver curves on common grid (same approach as loss.rs)
    let driver_curves: Vec<Curve> = data
        .drivers
        .iter()
        .map(|d| {
            crate::read::normalize_and_interpolate_response_with_range(
                &data.freq_grid,
                &Curve {
                    freq: d.freq.clone(),
                    spl: d.spl.clone(),
                    phase: d.phase.clone(),
                    ..Default::default()
                },
                20.0,
                20000.0,
            )
        })
        .collect();

    // Sum complex responses
    let mut combined_complex = Array1::<Complex64>::zeros(data.freq_grid.len());

    for i in 0..n_drivers {
        let mag_factor = 10.0_f64.powf(gains[i] / 20.0);
        let delay_s = delays[i] / 1000.0;
        let (ap_freq, ap_q) = allpass_filters[i];
        let ap_biquad = Biquad::new(BiquadFilterType::AllPass, ap_freq, sample_rate, ap_q, 0.0);

        for j in 0..data.freq_grid.len() {
            let f = data.freq_grid[j];
            let spl = driver_curves[i].spl[j];

            // Driver complex response
            let z_driver = if let Some(phase) = &driver_curves[i].phase {
                let phi = phase[j].to_radians();
                let m = 10.0_f64.powf(spl / 20.0);
                Complex64::from_polar(m, phi)
            } else {
                let m = 10.0_f64.powf(spl / 20.0);
                Complex64::new(m, 0.0)
            };

            // Delay phase
            let phi_delay = -2.0 * PI * f * delay_s;
            let z_delay = Complex64::from_polar(1.0, phi_delay);

            // All-pass complex response
            let z_allpass = allpass_complex_response(&ap_biquad, f);

            combined_complex[j] += z_driver * mag_factor * z_delay * z_allpass;
        }
    }

    // Convert to dB SPL
    combined_complex.mapv(|z| 20.0 * z.norm().max(1e-12).log10())
}

/// Compute complex frequency response of an all-pass biquad at frequency f.
pub(super) fn allpass_complex_response(biquad: &Biquad, f: f64) -> Complex64 {
    let (a1, a2, b0, b1, b2) = biquad.constants();
    let omega = 2.0 * PI * f / biquad.srate;
    let z_inv = Complex64::from_polar(1.0, -omega);
    let z_inv2 = z_inv * z_inv;

    let num = b0 + b1 * z_inv + b2 * z_inv2;
    let den = 1.0 + a1 * z_inv + a2 * z_inv2;

    num / den
}
