#![allow(clippy::field_reassign_with_default)]
#![cfg(any(feature = "qa", debug_assertions))]

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[path = "distortion_regression_tests/misc.rs"]
mod misc;
#[cfg(test)]
#[path = "distortion_regression_tests/tests.rs"]
mod tests;
