// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::SMOOTHING_MS;
use super::stereo_imager_plugin_params::StereoImagerPluginParams;
use crate::params::PARAMS as SI;
use sotf_host::lr4_crossover::Lr4Crossover;
use sotf_host::param_specs::find_by_key as pk;
use sotf_host::parameters::{Parameter, ParameterId, ParameterValue};
use sotf_host::plugin::{InPlacePlugin, PluginInfo, PluginResult, ProcessContext};
use sotf_host::simd::{enable_ftz_daz, flush_denormals_inplace};
use sotf_host::smoothing::Smoother;

pub struct StereoImagerPlugin {
    pub(super) channels: usize,
    pub(super) sample_rate: u32,

    // Parameters
    pub(super) width: f32,
    pub(super) low_mid_freq: f32,
    pub(super) mid_high_freq: f32,
    pub(super) low_width: f32,
    pub(super) mid_width: f32,
    pub(super) high_width: f32,
    pub(super) mono_bass: bool,
    pub(super) mix: f32,

    // Crossovers: each crossover handles 2 channels (one for mid signal, one for side signal)
    pub(super) crossover_low: Lr4Crossover<f32>,
    pub(super) crossover_high: Lr4Crossover<f32>,

    // Pre-allocated dry buffer for mix blending
    pub(super) dry_buf: Vec<f32>,

    // Smoothers for click-free parameter changes
    pub(super) width_smoother: Smoother,
    pub(super) low_mid_freq_smoother: Smoother,
    pub(super) mid_high_freq_smoother: Smoother,
    pub(super) low_width_smoother: Smoother,
    pub(super) mid_width_smoother: Smoother,
    pub(super) high_width_smoother: Smoother,
    pub(super) mix_smoother: Smoother,

    pub(super) cached_parameters: Vec<Parameter>,
}

impl StereoImagerPlugin {
    pub fn new(channels: usize, params: StereoImagerPluginParams) -> Self {
        let sr = 48000;
        let mut plugin = Self {
            channels,
            sample_rate: sr,

            width: params.width,
            low_mid_freq: params.low_mid_freq,
            mid_high_freq: params.mid_high_freq,
            low_width: params.low_width,
            mid_width: params.mid_width,
            high_width: params.high_width,
            mono_bass: params.mono_bass,
            mix: params.mix,

            // 2 channels: channel 0 = mid, channel 1 = side
            crossover_low: Lr4Crossover::new(params.low_mid_freq, sr as f32, 2),
            crossover_high: Lr4Crossover::new(params.mid_high_freq, sr as f32, 2),

            dry_buf: Vec::new(),

            width_smoother: Smoother::new(params.width, SMOOTHING_MS, sr),
            low_mid_freq_smoother: Smoother::new(params.low_mid_freq, SMOOTHING_MS, sr),
            mid_high_freq_smoother: Smoother::new(params.mid_high_freq, SMOOTHING_MS, sr),
            low_width_smoother: Smoother::new(params.low_width, SMOOTHING_MS, sr),
            mid_width_smoother: Smoother::new(params.mid_width, SMOOTHING_MS, sr),
            high_width_smoother: Smoother::new(params.high_width, SMOOTHING_MS, sr),
            mix_smoother: Smoother::new(params.mix, SMOOTHING_MS, sr),

            cached_parameters: Vec::new(),
        };
        plugin.rebuild_cached_parameters();
        plugin
    }

    pub fn from_params(channels: usize, params: StereoImagerPluginParams) -> Self {
        Self::new(channels, params)
    }

    pub(super) fn rebuild_cached_parameters(&mut self) {
        self.cached_parameters = vec![
            Parameter::new_float(
                "width",
                "Width",
                self.width,
                pk(SI, "width").min_f64() as f32,
                pk(SI, "width").max_f64() as f32,
            ),
            Parameter::new_float(
                "low_mid_freq",
                "Low-Mid Freq",
                self.low_mid_freq,
                pk(SI, "low_mid_freq").min_f64() as f32,
                pk(SI, "low_mid_freq").max_f64() as f32,
            ),
            Parameter::new_float(
                "mid_high_freq",
                "Mid-High Freq",
                self.mid_high_freq,
                pk(SI, "mid_high_freq").min_f64() as f32,
                pk(SI, "mid_high_freq").max_f64() as f32,
            ),
            Parameter::new_float(
                "low_width",
                "Low Width",
                self.low_width,
                pk(SI, "low_width").min_f64() as f32,
                pk(SI, "low_width").max_f64() as f32,
            ),
            Parameter::new_float(
                "mid_width",
                "Mid Width",
                self.mid_width,
                pk(SI, "mid_width").min_f64() as f32,
                pk(SI, "mid_width").max_f64() as f32,
            ),
            Parameter::new_float(
                "high_width",
                "High Width",
                self.high_width,
                pk(SI, "high_width").min_f64() as f32,
                pk(SI, "high_width").max_f64() as f32,
            ),
            Parameter::new_bool("mono_bass", "Mono Bass", self.mono_bass),
            Parameter::new_float(
                "mix",
                "Mix",
                self.mix,
                pk(SI, "mix").min_f64() as f32,
                pk(SI, "mix").max_f64() as f32,
            ),
        ];
    }
}

impl InPlacePlugin for StereoImagerPlugin {
    fn info(&self) -> PluginInfo {
        PluginInfo::new("StereoImager", env!("CARGO_PKG_VERSION"), "SotF")
            .with_description("Multi-band M/S stereo width control")
    }

    fn channels(&self) -> usize {
        self.channels
    }

    fn parameters(&self) -> Vec<Parameter> {
        self.cached_parameters.clone()
    }

    /// Override default to avoid cloning `cached_parameters` on every call.
    /// The trait default calls `self.parameters()` (a clone), which allocates.
    /// Instead, validate directly against the static PARAMS table — no heap
    /// allocation required.
    fn validate_parameter(&self, id: &ParameterId, value: &ParameterValue) -> PluginResult<()> {
        // Search the static PARAMS array; `find_by_key` panics so use .find() directly.
        let spec = SI.iter().find(|s| s.engine_key == id.as_str());
        if let Some(spec) = spec {
            if let ParameterValue::Float(v) = value {
                let min = spec.min_f64() as f32;
                let max = spec.max_f64() as f32;
                if *v < min || *v > max {
                    return Err(format!(
                        "{}: value {} out of range [{}, {}]",
                        id, v, min, max
                    ));
                }
            }
            Ok(())
        } else {
            Err(format!("Unknown parameter: {}", id))
        }
    }

    fn set_parameter(&mut self, id: ParameterId, value: ParameterValue) -> PluginResult<()> {
        self.validate_parameter(&id, &value)?;

        // Update the corresponding cached_parameter in-place (no Vec reallocation).
        // `Parameter::default_value` is the current value field used by the host.
        macro_rules! update_cached {
            ($id:expr, $val:expr) => {
                if let Some(p) = self.cached_parameters.iter_mut().find(|p| p.id == $id) {
                    p.default_value = $val;
                }
            };
        }

        match id.as_str() {
            "width" => {
                if let Some(v) = value.as_float() {
                    self.width = v;
                    self.width_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            "low_mid_freq" => {
                if let Some(v) = value.as_float() {
                    self.low_mid_freq = v;
                    self.low_mid_freq_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            "mid_high_freq" => {
                if let Some(v) = value.as_float() {
                    self.mid_high_freq = v;
                    self.mid_high_freq_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            "low_width" => {
                if let Some(v) = value.as_float() {
                    self.low_width = v;
                    self.low_width_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            "mid_width" => {
                if let Some(v) = value.as_float() {
                    self.mid_width = v;
                    self.mid_width_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            "high_width" => {
                if let Some(v) = value.as_float() {
                    self.high_width = v;
                    self.high_width_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            "mono_bass" => {
                if let Some(v) = value.as_bool() {
                    self.mono_bass = v;
                    update_cached!(id, ParameterValue::Bool(v));
                }
            }
            "mix" => {
                if let Some(v) = value.as_float() {
                    self.mix = v;
                    self.mix_smoother.set_target(v);
                    update_cached!(id, ParameterValue::Float(v));
                }
            }
            _ => return Err(format!("Unknown parameter: {}", id)),
        }
        Ok(())
    }

    fn get_parameter(&self, id: &ParameterId) -> Option<ParameterValue> {
        match id.as_str() {
            "width" => Some(ParameterValue::Float(self.width)),
            "low_mid_freq" => Some(ParameterValue::Float(self.low_mid_freq)),
            "mid_high_freq" => Some(ParameterValue::Float(self.mid_high_freq)),
            "low_width" => Some(ParameterValue::Float(self.low_width)),
            "mid_width" => Some(ParameterValue::Float(self.mid_width)),
            "high_width" => Some(ParameterValue::Float(self.high_width)),
            "mono_bass" => Some(ParameterValue::Bool(self.mono_bass)),
            "mix" => Some(ParameterValue::Float(self.mix)),
            _ => None,
        }
    }

    fn initialize(&mut self, sample_rate: u32) -> PluginResult<()> {
        self.sample_rate = sample_rate;

        // Reinitialize crossovers at the correct sample rate
        self.crossover_low
            .reinit(self.low_mid_freq, sample_rate as f32, 2);
        self.crossover_high
            .reinit(self.mid_high_freq, sample_rate as f32, 2);

        // Reset smoothers at the new sample rate
        self.width_smoother = Smoother::new(self.width, SMOOTHING_MS, sample_rate);
        self.low_mid_freq_smoother = Smoother::new(self.low_mid_freq, SMOOTHING_MS, sample_rate);
        self.mid_high_freq_smoother = Smoother::new(self.mid_high_freq, SMOOTHING_MS, sample_rate);
        self.low_width_smoother = Smoother::new(self.low_width, SMOOTHING_MS, sample_rate);
        self.mid_width_smoother = Smoother::new(self.mid_width, SMOOTHING_MS, sample_rate);
        self.high_width_smoother = Smoother::new(self.high_width, SMOOTHING_MS, sample_rate);
        self.mix_smoother = Smoother::new(self.mix, SMOOTHING_MS, sample_rate);

        // Pre-allocate dry buffer for maximum expected frame size.
        // 65536 * 2 covers virtually all real-world buffer sizes (up to ~1.4s @ 48 kHz).
        self.dry_buf.resize(65536 * 2, 0.0);

        Ok(())
    }

    fn reset(&mut self) {
        self.crossover_low.reset();
        self.crossover_high.reset();
        // Snap all smoothers to their current target values so a reset
        // during a parameter transition does not resume the ramp.
        self.width_smoother.reset(self.width);
        self.low_mid_freq_smoother.reset(self.low_mid_freq);
        self.mid_high_freq_smoother.reset(self.mid_high_freq);
        self.low_width_smoother.reset(self.low_width);
        self.mid_width_smoother.reset(self.mid_width);
        self.high_width_smoother.reset(self.high_width);
        self.mix_smoother.reset(self.mix);
    }

    fn process_in_place(
        &mut self,
        buffer: &mut [f32],
        context: &ProcessContext,
    ) -> PluginResult<usize> {
        enable_ftz_daz();

        let nf = context.num_frames;

        // Stereo only -- pass through unchanged for non-stereo
        if self.channels != 2 {
            return Ok(nf);
        }

        // Fully dry path: no need to allocate/copy dry buffers or run any DSP.
        let mix_is_zero = self.mix_smoother.target() <= f32::EPSILON
            && self.mix_smoother.current() <= f32::EPSILON;
        if mix_is_zero {
            return Ok(nf);
        }

        // Ensure dry buffer is large enough.
        // initialize() pre-allocates 65536*2 samples covering virtually all
        // real-world buffer sizes; this resize is a last-resort fallback only.
        if self.dry_buf.len() < nf * 2 {
            self.dry_buf.resize(nf * 2, 0.0);
        }

        // Save dry signal for mix blending only when wet/dry blend is active.
        // At mix=1.0 (default) the copy is wasted; skip it to save memory bandwidth.
        let need_dry = !(self.mix_smoother.target() >= 1.0 - f32::EPSILON
            && self.mix_smoother.current() >= 1.0 - f32::EPSILON);
        if need_dry {
            self.dry_buf[..nf * 2].copy_from_slice(&buffer[..nf * 2]);
        }

        // Hoist mono_bass out of the per-sample loop — it changes extremely rarely
        // and checking a bool every sample wastes branch prediction budget.
        let low_side_enable = if self.mono_bass { 0.0 } else { 1.0 };

        for frame in 0..nf {
            let idx = frame * 2;
            let l = buffer[idx];
            let r = buffer[idx + 1];

            // M/S encode
            let mid = (l + r) * 0.5;
            let side = (l - r) * 0.5;

            // Smooth crossover automation. Retuning the LR4 filters in small
            // per-frame frequency steps avoids the large coefficient jumps that
            // caused zipper clicks when set_parameter() updated them instantly.
            let mut low_mid_freq = self.low_mid_freq_smoother.advance();
            let mut mid_high_freq = self.mid_high_freq_smoother.advance();
            if low_mid_freq > mid_high_freq {
                std::mem::swap(&mut low_mid_freq, &mut mid_high_freq);
            }
            self.crossover_low.set_frequency(low_mid_freq);
            self.crossover_high.set_frequency(mid_high_freq);

            // Split mid and side into bands via cascaded crossovers.
            // crossover_low: channel 0 = mid signal, channel 1 = side signal
            let (mid_low, mid_rest) = self.crossover_low.process(mid, 0);
            let (side_low, side_rest) = self.crossover_low.process(side, 1);
            // crossover_high: channel 0 = mid rest, channel 1 = side rest
            let (mid_mid, mid_high) = self.crossover_high.process(mid_rest, 0);
            let (side_mid, side_high) = self.crossover_high.process(side_rest, 1);

            // Advance smoothers (per-sample)
            let gw = self.width_smoother.advance();
            let lw = self.low_width_smoother.advance();
            let mw = self.mid_width_smoother.advance();
            let hw = self.high_width_smoother.advance();

            // Apply per-band width scaling to side signal.
            let low_side = side_low * lw * gw * low_side_enable;
            let mid_side_scaled = side_mid * mw * gw;
            let high_side_scaled = side_high * hw * gw;

            // Reconstruct total mid and side
            let total_mid = mid_low + mid_mid + mid_high;
            let total_side = low_side + mid_side_scaled + high_side_scaled;

            // M/S decode
            let wet_l = total_mid + total_side;
            let wet_r = total_mid - total_side;

            // Dry/wet mix
            let m = self.mix_smoother.advance();
            if need_dry {
                buffer[idx] = self.dry_buf[idx] * (1.0 - m) + wet_l * m;
                buffer[idx + 1] = self.dry_buf[idx + 1] * (1.0 - m) + wet_r * m;
            } else {
                buffer[idx] = wet_l;
                buffer[idx + 1] = wet_r;
            }
        }

        flush_denormals_inplace(buffer);
        Ok(nf)
    }
}
