// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::PREVIEW_HEIGHT;
use super::misc::PREVIEW_WIDTH;
use super::misc::downsample_rgb;
use super::misc::extract_qr_bounds;
use super::types::CameraPreview;
use super::types::QrScanResult;
use gpui::*;
use gpui_ui_kit::*;
use nokhwa::Camera;
use nokhwa::pixel_format::RgbFormat;
use nokhwa::utils::{
    CameraFormat, CameraIndex, FrameFormat, RequestedFormat, RequestedFormatType, Resolution,
};
use std::sync::mpsc;
use std::thread;
use std::time::Duration;

pub(super) fn camera_error_message(raw: &str) -> String {
    let lower = raw.to_lowercase();
    if lower.contains("lock") || lower.contains("busy") || lower.contains("in use") {
        format!(
            "Camera is in use by another application. \
             Close the other app and try again.\n\nDetails: {}",
            raw
        )
    } else if lower.contains("permission")
        || lower.contains("denied")
        || lower.contains("authorized")
    {
        format!(
            "Camera access denied. Grant permission in \
             System Settings > Privacy & Security > Camera.\n\nDetails: {}",
            raw
        )
    } else if lower.contains("not found")
        || lower.contains("no camera")
        || lower.contains("no device")
    {
        "No camera found. Connect a camera and try again.".to_string()
    } else {
        format!("Could not open camera: {}", raw)
    }
}

pub(super) fn camera_capture_loop(
    result_tx: mpsc::Sender<QrScanResult>,
    stop_rx: mpsc::Receiver<()>,
) -> Result<(), String> {
    let formats_to_try = [
        RequestedFormat::new::<RgbFormat>(RequestedFormatType::Closest(CameraFormat::new(
            Resolution::new(1280, 720),
            FrameFormat::MJPEG,
            30,
        ))),
        RequestedFormat::new::<RgbFormat>(RequestedFormatType::Closest(CameraFormat::new(
            Resolution::new(1280, 720),
            FrameFormat::YUYV,
            30,
        ))),
        RequestedFormat::new::<RgbFormat>(RequestedFormatType::Closest(CameraFormat::new(
            Resolution::new(640, 480),
            FrameFormat::MJPEG,
            30,
        ))),
        RequestedFormat::new::<RgbFormat>(RequestedFormatType::None),
    ];

    let mut camera = None;
    let mut last_error = String::new();

    for requested in &formats_to_try {
        match Camera::new(CameraIndex::Index(0), *requested) {
            Ok(cam) => {
                camera = Some(cam);
                break;
            }
            Err(e) => {
                last_error = format!("{}", e);
            }
        }
    }

    let mut camera = camera.ok_or_else(|| camera_error_message(&last_error))?;

    camera
        .open_stream()
        .map_err(|e| camera_error_message(&e.to_string()))?;

    loop {
        if stop_rx.try_recv().is_ok() {
            break;
        }

        let frame = match camera.frame() {
            Ok(f) => f,
            Err(_) => {
                thread::sleep(Duration::from_millis(100));
                continue;
            }
        };

        let decoded = match frame.decode_image::<RgbFormat>() {
            Ok(img) => img,
            Err(_) => {
                thread::sleep(Duration::from_millis(100));
                continue;
            }
        };

        let width = decoded.width() as usize;
        let height = decoded.height() as usize;
        let rgb_data = decoded.into_raw();

        // Grayscale for QR detection
        let mut gray_data = Vec::with_capacity(width * height);
        for chunk in rgb_data.chunks(3) {
            if chunk.len() == 3 {
                let gray =
                    (chunk[0] as u32 * 299 + chunk[1] as u32 * 587 + chunk[2] as u32 * 114) / 1000;
                gray_data.push(gray as u8);
            }
        }

        // Downsample for preview
        let preview_rgb = downsample_rgb(&rgb_data, width, height, PREVIEW_WIDTH, PREVIEW_HEIGHT);

        // Detect QR codes
        let mut decoder = rqrr::PreparedImage::prepare_from_greyscale(width, height, |x, y| {
            gray_data.get(y * width + x).copied().unwrap_or(0)
        });
        let grids = decoder.detect_grids();

        if grids.is_empty() {
            let preview = CameraPreview {
                rgb_pixels: preview_rgb,
                width: PREVIEW_WIDTH,
                height: PREVIEW_HEIGHT,
                qr_bounds: None,
            };
            let _ = result_tx.send(QrScanResult::Scanning(preview));
        } else {
            let mut decoded_any = false;
            let mut qr_bounds = None;

            for grid in &grids {
                if qr_bounds.is_none() {
                    qr_bounds = Some(extract_qr_bounds(grid, width, height));
                }

                if let Ok((_meta, content)) = grid.decode() {
                    let preview = CameraPreview {
                        rgb_pixels: preview_rgb.clone(),
                        width: PREVIEW_WIDTH,
                        height: PREVIEW_HEIGHT,
                        qr_bounds,
                    };
                    let _ = result_tx.send(QrScanResult::Success(content, preview));
                    decoded_any = true;
                }
            }

            if !decoded_any {
                let preview = CameraPreview {
                    rgb_pixels: preview_rgb,
                    width: PREVIEW_WIDTH,
                    height: PREVIEW_HEIGHT,
                    qr_bounds,
                };
                let _ = result_tx.send(QrScanResult::Detected(preview));
            }
        }

        thread::sleep(Duration::from_millis(50));
    }

    Ok(())
}
