// Auto-generated by r2factor. Manual edits will be overwritten on next split.


pub(super) const ROOM_EQ_PYTHON_DEFAULT_SMOOTHING_OCTAVES: f64 = 1.0 / 6.0;

/// Window-width threshold above which the per-channel review charts
/// switch from stacked to a 2-column grid.
pub(super) const ROOM_EQ_REVIEW_WIDE_BREAKPOINT_PX: f32 = 1600.0;

pub(super) const ROOM_EQ_CHANNEL_COLORS: [u32; 10] = [
    0x1f77b4, // blue
    0xff7f0e, // orange
    0x2ca02c, // green
    0xd62728, // red
    0x9467bd, // purple
    0x8c564b, // brown
    0xe377c2, // pink
    0x7f7f7f, // gray
    0xbcbd22, // olive
    0x17becf, // cyan
];

pub(super) const ROOM_EQ_DRIVER_OPACITIES: [f32; 4] = [1.0, 0.78, 0.58, 0.42];

