// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::position::Position;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Unique identifier for workflow nodes
pub type NodeId = uuid::Uuid;

/// Unique identifier for connections
pub type ConnectionId = uuid::Uuid;

/// Link type for connections
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum LinkType {
    /// Fat link - carries all channels bundled together
    #[default]
    Fat,
    /// Thin link - carries a single channel
    Thin,
}

/// Current interaction mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum InteractionMode {
    #[default]
    None,
    /// Panning the canvas
    Panning,
    /// Dragging nodes
    DraggingNodes,
    /// Creating a connection
    CreatingConnection,
    /// Box selection
    BoxSelecting,
    /// Alt+drag from node body for bulk-connect
    BulkConnecting,
}

/// State for dragging nodes
#[derive(Debug, Clone)]
pub struct NodeDragState {
    /// IDs of nodes being dragged
    pub dragging_nodes: Vec<NodeId>,
    /// Starting mouse position
    pub start_mouse: Position,
    /// Original positions (for undo)
    pub original_positions: HashMap<NodeId, Position>,
}

/// State for dragging a new connection
#[derive(Debug, Clone)]
pub struct ConnectionDrag {
    pub from_node: NodeId,
    pub from_port: usize,
    pub is_output: bool,
    pub current_position: Position,
}

/// State for bulk-connect drag (Alt+drag from node body to another node)
#[derive(Debug, Clone)]
pub struct BulkConnectDrag {
    pub from_node: NodeId,
    pub current_position: Position,
}

/// State for context menu
#[derive(Debug, Clone)]
pub struct ContextMenuState {
    pub position: Position,
    pub visible: bool,
    /// If the right-click hit a node, this is set so the canvas can show
    /// node-specific menu items and the parent can dispatch per-node actions.
    pub target_node: Option<NodeId>,
}
