FROM sotf-base-win-arm64

ENV CARGO_BUILD_TARGET=aarch64-pc-windows-gnullvm
ENV CC_aarch64_pc_windows_gnullvm=aarch64-w64-mingw32-gcc
ENV CXX_aarch64_pc_windows_gnullvm=aarch64-w64-mingw32-g++
ENV AR_aarch64_pc_windows_gnullvm=aarch64-w64-mingw32-ar
ENV CARGO_TARGET_AARCH64_PC_WINDOWS_GNULLVM_LINKER=aarch64-w64-mingw32-clang
ENV OPENSSL_STATIC=1
ENV OPENSSL_VENDORED=1
ENV AUTOEQ_DIR=/project
