// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::service::{redact_secret, *};
use serde::Deserialize;
use std::sync::Arc;

mod async_runtime;
mod consts;
mod misc;
mod tidal_service;
mod types;
#[cfg(test)]
mod tests;

pub use tidal_service::*;

