// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[path = "layout_tests/default.rs"]
mod default;
#[path = "layout_tests/fake_measure.rs"]
mod fake_measure;
#[path = "layout_tests/misc.rs"]
mod misc;
#[cfg(test)]
#[path = "layout_tests/tests.rs"]
mod tests;
