//! Delimiter-separated values (DSV) parser
//!
//! Low-level DSV parsing that handles any delimiter.

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

mod dsv_parse_error_kind;
mod dsv_parser;
mod error;
mod parse;
#[cfg(test)]
mod tests;
mod types;

pub use dsv_parse_error_kind::*;
pub use dsv_parser::*;
pub use error::*;
pub use parse::*;
pub use types::*;
