// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::Curve;
use std::collections::HashMap;

/// CEA2034 spin data with all standard curves
#[derive(Debug, Clone)]
pub struct Cea2034Data {
    /// On Axis response
    pub on_axis: Curve,
    /// Listening Window response
    pub listening_window: Curve,
    /// Early Reflections response
    pub early_reflections: Curve,
    /// Sound Power response
    pub sound_power: Curve,
    /// Estimated In-Room Response (PIR)
    pub estimated_in_room: Curve,
    /// Early Reflections Directivity Index (On Axis - ER)
    pub er_di: Curve,
    /// Sound Power Directivity Index (On Axis - SP)
    pub sp_di: Curve,
    /// All curves as HashMap (for backward compatibility)
    pub curves: HashMap<String, Curve>,
}

/// Contour plot data with 2D heatmap structure
///
/// Used for "SPL Horizontal Contour" and "SPL Vertical Contour" measurements
/// which provide full angle range data (-180° to +180°).
#[derive(Debug, Clone)]
pub struct ContourPlotData {
    /// Frequency values (X axis)
    pub freq: Vec<f64>,
    /// Angle values in degrees (Y axis)
    pub angles: Vec<f64>,
    /// SPL values as a 2D grid (row-major: angles × freq)
    pub spl: Vec<f64>,
    /// Number of frequency points
    pub freq_count: usize,
    /// Number of angle points
    pub angle_count: usize,
}
