// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use gpui::*;

pub(super) const SPECTRUM_STANDARD_FREQUENCIES: [f32; 15] = [
    20.0, 30.0, 50.0, 100.0, 200.0, 300.0, 500.0, 1000.0, 2000.0, 3000.0, 5000.0, 10000.0, 15000.0,
    20000.0, 24000.0,
];

/// Format a frequency value for compact spectrum axis labels.
pub fn format_spectrum_frequency_label(freq: f32) -> String {
    if freq >= 1000.0 {
        let khz = freq / 1000.0;
        if khz == khz.floor() {
            format!("{}k", khz as i32)
        } else {
            format!("{khz:.1}k")
        }
    } else if freq == freq.floor() {
        format!("{}", freq as i32)
    } else {
        format!("{freq:.0}")
    }
}

/// Calculate logarithmic position of a frequency within a range.
pub fn logarithmic_frequency_position(freq: f32, min_freq: f32, max_freq: f32) -> f32 {
    let (min_freq, max_freq) = valid_frequency_range(min_freq, max_freq);
    let freq = if freq.is_finite() {
        freq.clamp(min_freq, max_freq)
    } else {
        min_freq
    };
    let log_min = min_freq.log10();
    let log_max = max_freq.log10();
    let denominator = log_max - log_min;
    if denominator.abs() <= f32::EPSILON {
        0.0
    } else {
        ((freq.log10() - log_min) / denominator).clamp(0.0, 1.0)
    }
}

pub(super) fn valid_frequency_range(min_freq: f32, max_freq: f32) -> (f32, f32) {
    let min_freq = if min_freq.is_finite() && min_freq > 0.0 {
        min_freq
    } else {
        20.0
    };
    let max_freq = if max_freq.is_finite() && max_freq > min_freq {
        max_freq
    } else {
        (min_freq * 2.0).max(20_000.0)
    };
    (min_freq, max_freq)
}

pub(super) fn rgba(hex: u32) -> Rgba {
    Rgba {
        r: ((hex >> 24) & 0xff) as f32 / 255.0,
        g: ((hex >> 16) & 0xff) as f32 / 255.0,
        b: ((hex >> 8) & 0xff) as f32 / 255.0,
        a: (hex & 0xff) as f32 / 255.0,
    }
}
