[package]
name = "math-delaunay"
version = "0.5.3"
authors.workspace = true
description = "Delaunay triangulation and Voronoi diagram — faithful port of d3-delaunay"
edition.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
delaunator = { workspace = true }

[dev-dependencies]
