// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::fitness_class::FitnessClass;
use super::knuth_plass_params::KnuthPlassParams;
use super::misc::badness;
use super::types::LineBreakStrategy;

mod misc;

#[test]
fn test_kp_fitness_class_from_ratio() {
    assert_eq!(FitnessClass::from_ratio(-1.0), FitnessClass::Tight);
    assert_eq!(FitnessClass::from_ratio(-0.3), FitnessClass::Normal);
    assert_eq!(FitnessClass::from_ratio(0.0), FitnessClass::Normal);
    assert_eq!(FitnessClass::from_ratio(0.7), FitnessClass::Loose);
    assert_eq!(FitnessClass::from_ratio(1.5), FitnessClass::VeryLoose);
}

#[test]
fn test_kp_badness() {
    assert!((badness(0.0) - 0.0).abs() < 1e-6);
    assert!((badness(1.0) - 100.0).abs() < 1e-6);
    assert!((badness(-1.0) - 100.0).abs() < 1e-6);
    assert_eq!(badness(f64::INFINITY), 10000.0);
    // badness(0.5) = 100 * 0.125 = 12.5
    assert!((badness(0.5) - 12.5).abs() < 1e-6);
}

#[test]
fn test_kp_line_break_strategy_default() {
    assert_eq!(LineBreakStrategy::default(), LineBreakStrategy::Greedy);
}

#[test]
fn test_kp_params_default() {
    let params = KnuthPlassParams::default();
    assert_eq!(params.line_penalty, 0.0);
    assert_eq!(params.hyphen_penalty, 50.0);
    assert_eq!(params.flagged_demerits, 3000.0);
    assert_eq!(params.fitness_demerits, 10000.0);
    assert_eq!(params.tolerance, 2.0);
    assert!(params.looseness_recovery);
}
