// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate :: app :: { App } ;
use std::sync::{Arc, Mutex};
use super::consts::OPT_PROGRESS;
use super::consts::OPT_RESULT;
use super::consts::SPEAKERS_RESULT;
use super::spawn::spawn_spinorama_speaker_load;

/// Poll speaker-load result on every tick. Returns true if the UI needs a redraw.
/// Also auto-triggers speaker list loading when entering the Select step.
pub fn poll_spinorama_speaker_load(app: &mut App) -> bool {
    use crate::app::{ConfigureSubScreen, Screen, SpinoramaStep};

    // Auto-load speakers when on Select step with empty list
    if !app.spinorama_eq.loading_speakers
        && app.spinorama_eq.available_speakers.is_empty()
        && app.spinorama_eq.speakers_error.is_none()
        && app.current_screen == Screen::Configure
        && app.configure_sub_screen == ConfigureSubScreen::SpinoramaEq
        && app.spinorama_eq.step == SpinoramaStep::Select
    {
        app.spinorama_eq.loading_speakers = true;
        spawn_spinorama_speaker_load();
    }

    if !app.spinorama_eq.loading_speakers {
        return false;
    }
    let result_slot = SPEAKERS_RESULT
        .get_or_init(|| Arc::new(Mutex::new(None)))
        .clone();
    if let Ok(mut guard) = result_slot.lock()
        && let Some(result) = guard.take()
    {
        app.spinorama_eq.loading_speakers = false;
        match result {
            Ok(speakers) => {
                app.spinorama_eq.available_speakers = speakers;
                app.spinorama_eq.update_filter();
            }
            Err(e) => {
                app.spinorama_eq.speakers_error = Some(e);
            }
        }
        return true;
    }
    false
}

/// Poll optimization progress/result on every tick while optimization is running.
/// Returns true if the UI needs a redraw.
pub fn poll_spinorama_optimization(app: &mut App) -> bool {
    use sotf_audio_player::room_eq_types::OptimizationStatus;
    use sotf_audio_player::spinorama_eq_types::SpinoramaBiquad;

    if app.spinorama_eq.opt_status != OptimizationStatus::Running {
        return false;
    }

    let result_slot = OPT_RESULT
        .get_or_init(|| Arc::new(Mutex::new(None)))
        .clone();
    let progress_slot = OPT_PROGRESS
        .get_or_init(|| Arc::new(Mutex::new(None)))
        .clone();

    if let Ok(mut guard) = result_slot.lock()
        && let Some(result) = guard.take()
    {
        match result {
            Ok(r) => {
                app.spinorama_eq.pre_loss = r.initial_loss;
                app.spinorama_eq.post_loss = r.final_loss;
                app.spinorama_eq.filters = r
                    .biquads
                    .iter()
                    .map(|b| SpinoramaBiquad {
                        filter_type: format!("{:?}", b.filter_type),
                        freq: b.freq,
                        q: b.q,
                        db_gain: b.db_gain,
                    })
                    .collect();
                app.spinorama_eq.curve_frequencies = r.frequencies.clone();
                app.spinorama_eq.curve_input = r.input_curve.clone();
                app.spinorama_eq.curve_target = r.target_curve.clone();
                app.spinorama_eq.curve_corrected = r.corrected_curve.clone();
                app.spinorama_eq.curve_filter_response = r.filter_response.clone();
                // Keep the progress-based loss_history (which includes scores)
                // Only override if empty (e.g. if the callback wasn't called)
                if app.spinorama_eq.loss_history.is_empty() {
                    app.spinorama_eq.loss_history = r
                        .optimization_history
                        .iter()
                        .map(|(iter, loss)| (*iter, *loss, None))
                        .collect();
                }
                app.spinorama_eq.opt_status = OptimizationStatus::Completed;
                app.spinorama_eq.opt_progress = 1.0;
            }
            Err(e) => {
                app.spinorama_eq.opt_status = OptimizationStatus::Failed;
                app.spinorama_eq.opt_error = Some(e);
            }
        }
        return true;
    }

    if let Ok(mut guard) = progress_slot.lock()
        && let Some((iter, max_iter, loss, pct, score)) = guard.take()
    {
        app.spinorama_eq.opt_iteration = iter;
        app.spinorama_eq.opt_max_iter = max_iter;
        app.spinorama_eq.opt_loss = loss;
        app.spinorama_eq.opt_progress = pct;
        app.spinorama_eq.loss_history.push((iter, loss, score));
        return true;
    }

    false
}

