use sotf_audio_player::PluginSettings;

/// Extract a type key string from a PluginSettings variant.
pub fn plugin_type_key(settings: &PluginSettings) -> &'static str {
    match settings {
        PluginSettings::EQ { .. } => "eq",
        PluginSettings::Gain { .. } => "gain",
        PluginSettings::AAE { .. } => "aae",
        PluginSettings::Upmixer { .. } => "upmixer",
        PluginSettings::Compressor { .. } => "compressor",
        PluginSettings::Limiter { .. } => "limiter",
        PluginSettings::Gate { .. } => "gate",
        PluginSettings::Expander { .. } => "expander",
        PluginSettings::MultibandCompressor { .. } => "multiband_compressor",
        PluginSettings::MultibandExpander { .. } => "multiband_expander",
        PluginSettings::LoudnessCompensation { .. } => "loudness_compensation",
        PluginSettings::FletcherMunson { .. } => "fletcher_munson",
        PluginSettings::BinauralDecoder { .. } => "binaural",
        PluginSettings::Convolution { .. } => "convolution",
        PluginSettings::LoudnessMonitor => "loudness_monitor",
        PluginSettings::SpectrumAnalyzer { .. } => "spectrum_analyzer",
        PluginSettings::ChannelMuteSolo { .. } => "channel_mute_solo",
        PluginSettings::Matrix { .. } => "matrix",
        PluginSettings::XTC { .. } => "xtc",
        PluginSettings::Denoiser { .. } => "denoiser",
        PluginSettings::Declick { .. } => "declick",
        PluginSettings::HissReducer { .. } => "hiss_reducer",
        PluginSettings::SpeechDenoiser { .. } => "speech_denoiser",
        PluginSettings::Pnd { .. } => "pnd",
        PluginSettings::Crossfeed { .. } => "crossfeed",
        PluginSettings::Delay { .. } => "delay",
        PluginSettings::Downmix { .. } => "downmix",
        PluginSettings::MonoToStereo { .. } => "mono_to_stereo",
        PluginSettings::ABCompare { .. } => "ab_compare",
        PluginSettings::Crossover { .. } => "crossover",
        PluginSettings::AmbisonicsDecoder { .. } => "ambisonics",
        PluginSettings::Beamformer { .. } => "beamformer",
        PluginSettings::Aec { .. } => "aec",
        PluginSettings::BandSplit { .. } => "band_split",
        PluginSettings::BandMerge { .. } => "band_merge",
        PluginSettings::StereoImager { .. } => "stereo_imager",
        PluginSettings::DeEsser { .. } => "de_esser",
        PluginSettings::TransientShaper { .. } => "transient_shaper",
        PluginSettings::Saturation { .. } => "saturation",
        PluginSettings::Dither { .. } => "dither",
        PluginSettings::DynamicEq { .. } => "dynamic_eq",
        PluginSettings::LinearPhaseEq { .. } => "linear_phase_eq",
        PluginSettings::SpectralCompressor { .. } => "spectral_compressor",
        PluginSettings::External { .. } => "external",
    }
}
