//! ============================================================================
//! A/B Comparison Plugin
//! ============================================================================
//!
//! This plugin allows fair comparison between two audio processing chains
//! with automatic loudness matching. Each path (A or B) can be:
//! - A single plugin
//! - A rack (linear chain of plugins)
//! - A graph (full DAG topology)

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub use config::*;

mod config;
mod factory;
pub mod params;

#[path = "lib/abcompare_plugin.rs"]
mod abcompare_plugin;
#[path = "lib/delay_line.rs"]
mod delay_line;
#[path = "lib/types.rs"]
mod types;
#[cfg(test)]
#[path = "lib/tests.rs"]
mod tests;

pub use abcompare_plugin::*;
pub use types::*;

