// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::reflection_hrtf::ReflectionHrtf;

/// Represents a single reflection path from source to listener
#[derive(Debug, Clone)]
pub struct Reflection {
    /// Delay in samples
    pub delay_samples: usize,
    /// Linear gain (after absorption and distance attenuation)
    pub gain: f32,
    /// Left/right channel multipliers for asymmetric reflections
    pub left_gain: f32,
    pub right_gain: f32,
    /// DOA azimuth in degrees (0 = front, positive = left). Used for per-reflection HRTF lookup.
    pub azimuth_deg: f32,
    /// DOA elevation in degrees. Used for per-reflection HRTF lookup.
    pub elevation_deg: f32,
    /// Pre-computed HRTF FIR for this reflection's DOA: [left_ir, right_ir] in frequency domain.
    /// Populated during initialize() when a SOFA file is loaded. Empty for ISM reflections.
    pub hrtf_filter: Option<ReflectionHrtf>,
}
