//! wgpu-based 3D surface renderer

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use bytemuck::{Pod, Zeroable};

mod misc;
mod surface3_drenderer;
mod transparent;
mod uniforms;
mod unpremultiply;

pub use surface3_drenderer::*;
pub use transparent::*;
pub use unpremultiply::*;

/// Uniform buffer data (must match shader layout)
#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
struct Uniforms {
    view_proj: [[f32; 4]; 4],
    model: [[f32; 4]; 4],
    light_dir: [f32; 3],
    colormap: f32,
    ambient: f32,
    diffuse: f32,
    opacity: f32,
    z_min: f32,
    x_min_log: f32,
    x_range_log: f32,
    is_log_x: f32,
    show_surface_isolines: f32,
    isoline_step: f32,
    isoline_width_px: f32,
    isoline_opacity: f32,
    isoline_color_r: f32,
    isoline_color_g: f32,
    isoline_color_b: f32,
    _padding0: f32,
    _padding1: f32,
}
