// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::default::default_country_code;
use super::default::default_httpd_port;
use super::default::default_mpd_port;
use super::default::default_sotf_api_port;
use super::default::default_spotify_quality;
use super::default::default_tidal_quality;
use super::mpd_client_auth_mode::MpdClientAuthMode;
use serde::{Deserialize, Serialize};

/// Per-source connection configuration.
///
/// Serialized as JSON into the `library_sources.config_json` column.
/// The `type` tag discriminant maps to `SourceType` in `sotf-federation`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "type")]
pub enum SourceConnectionConfig {
    Subsonic {
        url: String,
        username: String,
        password: String,
        #[serde(default)]
        legacy_auth: bool,
    },
    Mpd {
        host: String,
        #[serde(default = "default_mpd_port")]
        port: u16,
        #[serde(default)]
        auth_mode: MpdClientAuthMode,
        /// Password for password authentication.
        password: Option<String>,
        /// Port for MPD's httpd streaming output (default 6601).
        /// SOTF streams audio from this port during playback.
        #[serde(default = "default_httpd_port")]
        httpd_port: u16,
    },
    Dlna {
        location_url: Option<String>,
        friendly_name: Option<String>,
    },
    Peer {
        host: String,
        #[serde(default = "default_sotf_api_port")]
        port: u16,
        accepted_fingerprint: Option<String>,
        #[serde(default)]
        auth_token: Option<String>,
    },
    Tidal {
        #[serde(default)]
        access_token: String,
        #[serde(default = "default_tidal_quality")]
        quality: String,
        #[serde(default = "default_country_code")]
        country_code: String,
    },
    Spotify {
        #[serde(default)]
        username: String,
        #[serde(default)]
        password: String,
        #[serde(default = "default_spotify_quality")]
        quality: String,
    },
    IcyRadio {
        #[serde(default)]
        url: String,
        #[serde(default)]
        name: String,
    },
}

impl SourceConnectionConfig {
    /// Human-readable type name for UI display.
    #[must_use]
    pub fn type_name(&self) -> &'static str {
        match self {
            Self::Subsonic { .. } => "Subsonic",
            Self::Mpd { .. } => "MPD",
            Self::Dlna { .. } => "DLNA",
            Self::Peer { .. } => "Peer",
            Self::Tidal { .. } => "Tidal",
            Self::Spotify { .. } => "Spotify",
            Self::IcyRadio { .. } => "Radio",
        }
    }

    /// Database/serde key for this source type (lowercase, used for storage).
    #[must_use]
    pub fn source_type_key(&self) -> &'static str {
        match self {
            Self::Subsonic { .. } => "subsonic",
            Self::Mpd { .. } => "mpd",
            Self::Dlna { .. } => "dlna",
            Self::Peer { .. } => "peer",
            Self::Tidal { .. } => "tidal",
            Self::Spotify { .. } => "spotify",
            Self::IcyRadio { .. } => "icy_radio",
        }
    }

    /// Default config for a new source of the given type.
    #[must_use]
    pub fn default_for_type(type_name: &str) -> Self {
        match type_name {
            "subsonic" => Self::Subsonic {
                url: "https://".to_string(),
                username: String::new(),
                password: String::new(),
                legacy_auth: false,
            },
            "mpd" => Self::Mpd {
                host: "localhost".to_string(),
                port: 6600,
                auth_mode: MpdClientAuthMode::default(),
                password: None,
                httpd_port: 6601,
            },
            "dlna" => Self::Dlna {
                location_url: None,
                friendly_name: None,
            },
            "peer" => Self::Peer {
                host: String::new(),
                port: default_sotf_api_port(),
                accepted_fingerprint: None,
                auth_token: None,
            },
            "tidal" => Self::Tidal {
                access_token: String::new(),
                quality: default_tidal_quality(),
                country_code: default_country_code(),
            },
            "spotify" => Self::Spotify {
                username: String::new(),
                password: String::new(),
                quality: default_spotify_quality(),
            },
            "icy_radio" => Self::IcyRadio {
                url: String::new(),
                name: String::new(),
            },
            _ => Self::Mpd {
                host: "localhost".to_string(),
                port: 6600,
                auth_mode: MpdClientAuthMode::default(),
                password: None,
                httpd_port: 6601,
            },
        }
    }

    /// Editable field names for this source type.
    #[must_use]
    pub fn field_names(&self) -> Vec<&'static str> {
        match self {
            Self::Subsonic { .. } => vec!["URL", "Username", "Password", "Legacy Auth"],
            Self::Mpd { .. } => vec!["Host", "Port", "Auth Mode", "Password", "HTTP Stream Port"],
            Self::Dlna { .. } => vec!["Location URL", "Friendly Name"],
            Self::Peer { .. } => vec!["Host", "Port", "Fingerprint", "API Token"],
            Self::Tidal { .. } => vec!["Access Token", "Quality", "Country Code"],
            Self::Spotify { .. } => vec!["Username", "Password", "Quality"],
            Self::IcyRadio { .. } => vec!["Stream URL", "Station Name"],
        }
    }

    /// Get field value by index for UI display.
    #[must_use]
    pub fn field_value(&self, index: usize) -> String {
        match self {
            Self::Subsonic {
                url,
                username,
                password,
                legacy_auth,
            } => match index {
                0 => url.clone(),
                1 => username.clone(),
                2 => "*".repeat(password.len().min(8)),
                3 => legacy_auth.to_string(),
                _ => String::new(),
            },
            Self::Mpd {
                host,
                port,
                auth_mode,
                password,
                httpd_port,
            } => match index {
                0 => host.clone(),
                1 => port.to_string(),
                2 => auth_mode.label().to_string(),
                3 => password
                    .as_ref()
                    .map_or_else(String::new, |p| "*".repeat(p.len().min(8))),
                4 => httpd_port.to_string(),
                _ => String::new(),
            },
            Self::Dlna {
                location_url,
                friendly_name,
            } => match index {
                0 => location_url.clone().unwrap_or_default(),
                1 => friendly_name.clone().unwrap_or_default(),
                _ => String::new(),
            },
            Self::Peer {
                host,
                port,
                accepted_fingerprint,
                auth_token,
            } => match index {
                0 => host.clone(),
                1 => port.to_string(),
                2 => accepted_fingerprint.clone().unwrap_or_default(),
                3 => auth_token
                    .as_ref()
                    .map_or_else(String::new, |token| "*".repeat(token.len().min(8))),
                _ => String::new(),
            },
            Self::Tidal {
                access_token,
                quality,
                country_code,
            } => match index {
                0 => "*".repeat(access_token.len().min(8)),
                1 => quality.clone(),
                2 => country_code.clone(),
                _ => String::new(),
            },
            Self::Spotify {
                username,
                password,
                quality,
            } => match index {
                0 => username.clone(),
                1 => "*".repeat(password.len().min(8)),
                2 => quality.clone(),
                _ => String::new(),
            },
            Self::IcyRadio { url, name } => match index {
                0 => url.clone(),
                1 => name.clone(),
                _ => String::new(),
            },
        }
    }

    /// Set field value by index from UI input.
    pub fn set_field_value(&mut self, index: usize, value: &str) {
        match self {
            Self::Subsonic {
                url,
                username,
                password,
                legacy_auth,
            } => match index {
                0 => *url = value.to_string(),
                1 => *username = value.to_string(),
                2 => *password = value.to_string(),
                3 => *legacy_auth = value == "true",
                _ => {}
            },
            Self::Mpd {
                host,
                port,
                auth_mode,
                password,
                httpd_port,
            } => match index {
                0 => *host = value.trim().to_string(),
                1 => {
                    if let Ok(p) = value.trim().parse() {
                        *port = p;
                    }
                }
                2 => {
                    *auth_mode = match value {
                        "Password" => MpdClientAuthMode::Password,
                        "SSL" => MpdClientAuthMode::Ssl,
                        _ => MpdClientAuthMode::None,
                    }
                }
                3 => {
                    *password = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                }
                4 => {
                    if let Ok(p) = value.trim().parse() {
                        *httpd_port = p;
                    }
                }
                _ => {}
            },
            Self::Dlna {
                location_url,
                friendly_name,
            } => match index {
                0 => {
                    *location_url = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                }
                1 => {
                    *friendly_name = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                }
                _ => {}
            },
            Self::Peer {
                host,
                port,
                accepted_fingerprint,
                auth_token,
            } => match index {
                0 => *host = value.trim().to_string(),
                1 => {
                    if let Ok(p) = value.trim().parse() {
                        *port = p;
                    }
                }
                2 => {
                    *accepted_fingerprint = if value.is_empty() {
                        None
                    } else {
                        Some(value.trim().to_string())
                    };
                }
                3 => {
                    *auth_token = if value.trim().is_empty() {
                        None
                    } else {
                        Some(value.trim().to_string())
                    };
                }
                _ => {}
            },
            Self::Tidal {
                access_token,
                quality,
                country_code,
            } => match index {
                0 => *access_token = value.to_string(),
                1 => *quality = value.to_string(),
                2 => *country_code = value.to_string(),
                _ => {}
            },
            Self::Spotify {
                username,
                password,
                quality,
            } => match index {
                0 => *username = value.to_string(),
                1 => *password = value.to_string(),
                2 => *quality = value.to_string(),
                _ => {}
            },
            Self::IcyRadio { url, name } => match index {
                0 => *url = value.to_string(),
                1 => *name = value.to_string(),
                _ => {}
            },
        }
    }
}
