// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::net::{Ipv4Addr, SocketAddr, SocketAddrV4};
use std::time::Duration;
use tokio::net::UdpSocket;
use super::build::build_mdns_query;
use super::parse::parse_sotf_mdns_response;
use super::types::DiscoveredSotfApiServer;

pub const SOTF_API_SERVICE_TYPE: &str = "_sotf._tcp.local";

pub(super) const MDNS_MULTICAST: Ipv4Addr = Ipv4Addr::new(224, 0, 0, 251);

pub(super) const MDNS_PORT: u16 = 5353;

#[cfg(any(not(target_os = "macos"), test))]
pub(super) const SERVICE_ENUMERATION_TYPE: &str = "_services._dns-sd._udp.local";

#[cfg(any(not(target_os = "macos"), test))]
pub(super) const MDNS_TTL_SECS: u32 = 120;

/// Discover SOTF API servers advertised as `_sotf._tcp` on the local network.
pub async fn discover_sotf_api_servers(
    timeout: Duration,
) -> Result<Vec<DiscoveredSotfApiServer>, String> {
    let socket = UdpSocket::bind(SocketAddrV4::new(Ipv4Addr::UNSPECIFIED, 0))
        .await
        .map_err(|e| format!("Failed to bind SOTF discovery socket: {e}"))?;
    let query = build_mdns_query(SOTF_API_SERVICE_TYPE);
    let target = SocketAddr::V4(SocketAddrV4::new(MDNS_MULTICAST, MDNS_PORT));
    socket
        .send_to(&query, target)
        .await
        .map_err(|e| format!("Failed to send SOTF discovery query: {e}"))?;

    let mut servers = Vec::new();
    let mut buf = [0u8; 4096];
    let deadline = tokio::time::Instant::now() + timeout;

    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        if remaining.is_zero() {
            break;
        }

        match tokio::time::timeout(remaining, socket.recv_from(&mut buf)).await {
            Ok(Ok((len, from))) => {
                for server in parse_sotf_mdns_response(&buf[..len], from) {
                    if !servers.iter().any(|existing: &DiscoveredSotfApiServer| {
                        existing.address == server.address && existing.port == server.port
                    }) {
                        servers.push(server);
                    }
                }
            }
            Ok(Err(e)) => return Err(format!("Failed to receive SOTF discovery response: {e}")),
            Err(_) => break,
        }
    }

    Ok(servers)
}

