// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::app::theme::Theme;
use crate :: app :: types :: recording :: { RecordingState } ;
use crate::ui::PlayerView;
use gpui::prelude::*;
use gpui_ui_kit :: { Button , ButtonSize , ButtonVariant , HStack , StackAlign , StackSpacing , Text , TextSize , TextWeight } ;

pub(super) const PROBE_SIGNAL_BOOST_DB: f32 = 20.0;

/// Labelled numeric row with `-` / `+` buttons. Mirrors the helper in
/// `components/room_eq/step_2_delay_detection.rs` but mutates the
/// recording state rather than the Room EQ state. Closures are `Fn`
/// so no per-click clone is needed.
pub(super) fn probe_number_row(
    cx: &mut Context<PlayerView>,
    theme: &Theme,
    label: &'static str,
    current: f64,
    step: f32,
    apply: impl Fn(&mut RecordingState, f32) + Send + 'static + Clone,
) -> impl IntoElement {
    let apply_plus = apply.clone();
    let apply_minus = apply;
    HStack::new()
        .spacing(StackSpacing::Md)
        .align(StackAlign::Center)
        .child(Text::new(label).size(TextSize::Xs))
        .child(
            // intentional: numeric value emphasis in stepper, not a kicker label
            Text::new(format!("{:.0}", current))
                .size(TextSize::Xs)
                .weight(TextWeight::Bold),
        )
        .child(
            Button::new(format!("{label}_minus"), "−")
                .aria_label(format!("Decrease {label}"))
                .variant(ButtonVariant::Secondary)
                .size(ButtonSize::Xs)
                .theme(theme.to_button_theme())
                .on_click_event(cx.listener(move |view, _, _, cx| {
                    view.state.update(cx, |state, _| {
                        apply_minus(&mut state.app.measurement_state.recording_state, -step);
                    });
                    cx.notify();
                })),
        )
        .child(
            Button::new(format!("{label}_plus"), "+")
                .aria_label(format!("Increase {label}"))
                .variant(ButtonVariant::Secondary)
                .size(ButtonSize::Xs)
                .theme(theme.to_button_theme())
                .on_click_event(cx.listener(move |view, _, _, cx| {
                    view.state.update(cx, |state, _| {
                        apply_plus(&mut state.app.measurement_state.recording_state, step);
                    });
                    cx.notify();
                })),
        )
}

