// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::animation_rules::AnimationRules;
use super::audio_control_rules::AudioControlRules;
use super::corner_radii::CornerRadii;
use super::design_conformance_report::DesignConformanceReport;
use super::design_language::DesignLanguage;
use super::design_platform::DesignPlatform;
use super::design_token::DesignToken;
use super::design_token::token;
use super::elevation_rules::ElevationRules;
use super::finite::finite_non_negative;
use super::finite::finite_positive;
use super::interaction_rules::InteractionRules;
use super::layout_thresholds::LayoutThresholds;
use super::spacing_rules::SpacingRules;
use super::types::ConformanceFinding;
use super::types::CornerRadiusStyle;
use super::types::GroupSeparatorStyle;
use super::types::LabelPosition;
use super::types::MotionSpec;
use super::types::ToggleVariant;
use super::typography_rules::TypographyRules;
use serde::Serialize;

/// Complete design system — all shape, spacing, and interaction rules
/// needed to render platform-appropriate UIs.
///
/// Orthogonal to the Theme (which handles colors). Any Theme works with
/// any DesignSystem.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct DesignSystem {
    /// Which platform language this represents.
    pub language: DesignLanguage,
    /// Corner radius values and rendering style.
    pub corners: CornerRadii,
    /// Spacing grid and density.
    pub spacing: SpacingRules,
    /// Touch targets and interaction sizing.
    pub interaction: InteractionRules,
    /// Shadow and elevation model.
    pub elevation: ElevationRules,
    /// Animation timing.
    pub animation: AnimationRules,
    /// Typography.
    pub typography: TypographyRules,
    /// Layout solver thresholds.
    pub layout: LayoutThresholds,
    /// Audio-specific control geometry.
    pub audio_controls: AudioControlRules,
    /// Preferred toggle visual style.
    pub toggle_variant: ToggleVariant,
    /// Where labels appear relative to controls.
    pub label_position: LabelPosition,
    /// How control groups are visually separated.
    pub group_separator: GroupSeparatorStyle,
}

impl DesignSystem {
    /// Neutral preset — matches the current hardcoded values exactly.
    /// Zero visual change for existing users.
    pub fn neutral() -> Self {
        Self {
            language: DesignLanguage::Neutral,
            corners: CornerRadii {
                sm: 4.0,
                md: 8.0,
                lg: 12.0,
                xl: 16.0,
                style: CornerRadiusStyle::Circular,
            },
            spacing: SpacingRules {
                grid_unit: 4.0,
                control_padding_x: 12.0,
                control_padding_y: 8.0,
                control_gap: 8.0,
                section_gap: 16.0,
                card_padding: 12.0,
            },
            interaction: InteractionRules {
                min_touch_target: 32.0,
                border_width: 1.0,
                focus_ring_width: 2.0,
                focus_ring_offset: 2.0,
            },
            elevation: ElevationRules {
                level_0_blur: 0.0,
                level_1_blur: 4.0,
                level_2_blur: 16.0,
                shadow_opacity: 0.15,
                shadow_y_offset: 2.0,
            },
            animation: AnimationRules {
                duration_ms: 200,
                fast_ms: 100,
                slow_ms: 400,
                prefer_spring: false,
                spring_stiffness: 170.0,
                spring_damping: 26.0,
            },
            typography: TypographyRules {
                font_family: ".SystemUIFont".to_string(),
                dynamic_sizing: false,
                base_size: 14.0,
                small_size: 11.0,
                large_size: 18.0,
            },
            layout: LayoutThresholds {
                vertical_threshold: 400.0,
                group_stack_threshold: 500.0,
                compact_slider_threshold: 700.0,
                hide_viz_threshold: 600.0,
                compact_knob_threshold: 400.0,
                large_knob_threshold: 800.0,
                slider_height_normal: 180.0,
                slider_height_compact: 120.0,
            },
            audio_controls: AudioControlRules {
                knob_arc_start_deg: 135.0,
                knob_arc_sweep_deg: 270.0,
                knob_arc_width: 2.5,
                knob_arc_segments: 48,
                knob_border_width: 2.0,
                slider_track_widths: [14.0, 18.0, 24.0],
            },
            toggle_variant: ToggleVariant::Capsule,
            label_position: LabelPosition::Below,
            group_separator: GroupSeparatorStyle::Divider,
        }
    }

    /// Apple Human Interface Guidelines preset.
    pub fn apple_hig() -> Self {
        Self {
            language: DesignLanguage::AppleHig,
            corners: CornerRadii {
                sm: 6.0,
                md: 10.0,
                lg: 14.0,
                xl: 20.0,
                style: CornerRadiusStyle::Continuous,
            },
            spacing: SpacingRules {
                grid_unit: 8.0,
                control_padding_x: 16.0,
                control_padding_y: 12.0,
                control_gap: 8.0,
                section_gap: 20.0,
                card_padding: 16.0,
            },
            interaction: InteractionRules {
                min_touch_target: 44.0,
                border_width: 0.5,
                focus_ring_width: 3.0,
                focus_ring_offset: 2.0,
            },
            elevation: ElevationRules {
                level_0_blur: 0.0,
                level_1_blur: 8.0,
                level_2_blur: 24.0,
                shadow_opacity: 0.1,
                shadow_y_offset: 4.0,
            },
            animation: AnimationRules {
                duration_ms: 350,
                fast_ms: 150,
                slow_ms: 500,
                prefer_spring: true,
                spring_stiffness: 120.0,
                spring_damping: 14.0,
            },
            typography: TypographyRules {
                font_family: ".SystemUIFont".to_string(),
                dynamic_sizing: true,
                base_size: 15.0,
                small_size: 12.0,
                large_size: 20.0,
            },
            layout: LayoutThresholds {
                vertical_threshold: 400.0,
                group_stack_threshold: 500.0,
                compact_slider_threshold: 700.0,
                hide_viz_threshold: 600.0,
                compact_knob_threshold: 400.0,
                large_knob_threshold: 800.0,
                slider_height_normal: 180.0,
                slider_height_compact: 120.0,
            },
            audio_controls: AudioControlRules {
                knob_arc_start_deg: 135.0,
                knob_arc_sweep_deg: 270.0,
                knob_arc_width: 2.5,
                knob_arc_segments: 48,
                knob_border_width: 1.5,
                slider_track_widths: [14.0, 18.0, 24.0],
            },
            toggle_variant: ToggleVariant::Capsule,
            label_position: LabelPosition::Below,
            group_separator: GroupSeparatorStyle::Divider,
        }
    }

    /// Material Design 3 preset.
    pub fn material3() -> Self {
        Self {
            language: DesignLanguage::Material3,
            corners: CornerRadii {
                sm: 8.0,
                md: 12.0,
                lg: 16.0,
                xl: 28.0,
                style: CornerRadiusStyle::Circular,
            },
            spacing: SpacingRules {
                grid_unit: 4.0,
                control_padding_x: 16.0,
                control_padding_y: 12.0,
                control_gap: 8.0,
                section_gap: 16.0,
                card_padding: 16.0,
            },
            interaction: InteractionRules {
                min_touch_target: 48.0,
                border_width: 1.0,
                focus_ring_width: 2.0,
                focus_ring_offset: 2.0,
            },
            elevation: ElevationRules {
                level_0_blur: 0.0,
                level_1_blur: 12.0,
                level_2_blur: 24.0,
                shadow_opacity: 0.2,
                shadow_y_offset: 4.0,
            },
            animation: AnimationRules {
                duration_ms: 300,
                fast_ms: 150,
                slow_ms: 500,
                prefer_spring: false,
                spring_stiffness: 170.0,
                spring_damping: 26.0,
            },
            typography: TypographyRules {
                font_family: ".SystemUIFont".to_string(),
                dynamic_sizing: false,
                base_size: 14.0,
                small_size: 12.0,
                large_size: 22.0,
            },
            layout: LayoutThresholds {
                vertical_threshold: 360.0,
                group_stack_threshold: 480.0,
                compact_slider_threshold: 700.0,
                hide_viz_threshold: 600.0,
                compact_knob_threshold: 400.0,
                large_knob_threshold: 800.0,
                slider_height_normal: 180.0,
                slider_height_compact: 120.0,
            },
            audio_controls: AudioControlRules {
                knob_arc_start_deg: 135.0,
                knob_arc_sweep_deg: 270.0,
                knob_arc_width: 3.0,
                knob_arc_segments: 48,
                knob_border_width: 2.0,
                slider_track_widths: [16.0, 20.0, 24.0],
            },
            toggle_variant: ToggleVariant::ThumbOnTrack,
            label_position: LabelPosition::Below,
            group_separator: GroupSeparatorStyle::Card,
        }
    }

    /// Windows Fluent Design preset.
    pub fn fluent() -> Self {
        Self {
            language: DesignLanguage::Fluent,
            corners: CornerRadii {
                sm: 2.0,
                md: 4.0,
                lg: 8.0,
                xl: 12.0,
                style: CornerRadiusStyle::Circular,
            },
            spacing: SpacingRules {
                grid_unit: 4.0,
                control_padding_x: 12.0,
                control_padding_y: 8.0,
                control_gap: 6.0,
                section_gap: 12.0,
                card_padding: 12.0,
            },
            interaction: InteractionRules {
                min_touch_target: 32.0,
                border_width: 1.0,
                focus_ring_width: 2.0,
                focus_ring_offset: 1.0,
            },
            elevation: ElevationRules {
                level_0_blur: 0.0,
                level_1_blur: 2.0,
                level_2_blur: 8.0,
                shadow_opacity: 0.08,
                shadow_y_offset: 1.0,
            },
            animation: AnimationRules {
                duration_ms: 200,
                fast_ms: 100,
                slow_ms: 350,
                prefer_spring: false,
                spring_stiffness: 300.0,
                spring_damping: 30.0,
            },
            typography: TypographyRules {
                font_family: ".SystemUIFont".to_string(),
                dynamic_sizing: false,
                base_size: 14.0,
                small_size: 12.0,
                large_size: 18.0,
            },
            layout: LayoutThresholds {
                vertical_threshold: 400.0,
                group_stack_threshold: 500.0,
                compact_slider_threshold: 700.0,
                hide_viz_threshold: 600.0,
                compact_knob_threshold: 400.0,
                large_knob_threshold: 800.0,
                slider_height_normal: 160.0,
                slider_height_compact: 100.0,
            },
            audio_controls: AudioControlRules {
                knob_arc_start_deg: 135.0,
                knob_arc_sweep_deg: 270.0,
                knob_arc_width: 2.0,
                knob_arc_segments: 48,
                knob_border_width: 1.0,
                slider_track_widths: [12.0, 16.0, 20.0],
            },
            toggle_variant: ToggleVariant::Pill,
            label_position: LabelPosition::Right,
            group_separator: GroupSeparatorStyle::Border,
        }
    }

    pub fn for_language(language: DesignLanguage) -> Self {
        match language {
            DesignLanguage::AppleHig => Self::apple_hig(),
            DesignLanguage::Material3 => Self::material3(),
            DesignLanguage::Fluent => Self::fluent(),
            DesignLanguage::Neutral => Self::neutral(),
        }
    }

    pub fn from_language_id(id: &str) -> Option<Self> {
        DesignLanguage::from_id(id).map(Self::for_language)
    }

    pub fn for_platform(platform: DesignPlatform) -> Self {
        match platform {
            DesignPlatform::Macos | DesignPlatform::Ios => Self::apple_hig(),
            DesignPlatform::Windows => Self::fluent(),
            DesignPlatform::Android => Self::material3(),
            DesignPlatform::Linux | DesignPlatform::Other => Self::neutral(),
        }
    }

    /// Returns the platform-appropriate default design system.
    pub fn platform_default() -> Self {
        Self::for_platform(DesignPlatform::current())
    }
}

impl DesignSystem {
    /// Export stable platform/design tokens for Style Dictionary pipelines.
    pub fn style_dictionary_tokens(&self) -> Vec<DesignToken> {
        vec![
            token("design.language", self.language.as_str(), "string"),
            token("radius.sm", self.corners.sm, "dimension"),
            token("radius.md", self.corners.md, "dimension"),
            token("radius.lg", self.corners.lg, "dimension"),
            token("spacing.grid_unit", self.spacing.grid_unit, "dimension"),
            token(
                "spacing.control_padding_x",
                self.spacing.control_padding_x,
                "dimension",
            ),
            token(
                "spacing.control_padding_y",
                self.spacing.control_padding_y,
                "dimension",
            ),
            token("spacing.control_gap", self.spacing.control_gap, "dimension"),
            token("spacing.section_gap", self.spacing.section_gap, "dimension"),
            token(
                "spacing.card_padding",
                self.spacing.card_padding,
                "dimension",
            ),
            token(
                "interaction.min_touch_target",
                self.interaction.min_touch_target,
                "dimension",
            ),
            token(
                "interaction.border_width",
                self.interaction.border_width,
                "dimension",
            ),
            token(
                "interaction.focus_ring_width",
                self.interaction.focus_ring_width,
                "dimension",
            ),
            token(
                "interaction.focus_ring_offset",
                self.interaction.focus_ring_offset,
                "dimension",
            ),
            token(
                "elevation.level_0_blur",
                self.elevation.level_0_blur,
                "dimension",
            ),
            token(
                "elevation.level_1_blur",
                self.elevation.level_1_blur,
                "dimension",
            ),
            token(
                "elevation.level_2_blur",
                self.elevation.level_2_blur,
                "dimension",
            ),
            token(
                "elevation.shadow_opacity",
                self.elevation.shadow_opacity,
                "number",
            ),
            token(
                "typography.font_family",
                &self.typography.font_family,
                "font",
            ),
            token(
                "typography.base_size",
                self.typography.base_size,
                "dimension",
            ),
            token(
                "typography.dynamic_sizing",
                self.typography.dynamic_sizing,
                "boolean",
            ),
            token("motion.duration_ms", self.animation.duration_ms, "duration"),
            token("motion.fast_ms", self.animation.fast_ms, "duration"),
            token("motion.slow_ms", self.animation.slow_ms, "duration"),
            token(
                "motion.prefer_spring",
                self.animation.prefer_spring,
                "boolean",
            ),
            token(
                "audio.knob_arc_start_deg",
                self.audio_controls.knob_arc_start_deg,
                "number",
            ),
            token(
                "audio.knob_arc_sweep_deg",
                self.audio_controls.knob_arc_sweep_deg,
                "number",
            ),
            token(
                "audio.knob_arc_width",
                self.audio_controls.knob_arc_width,
                "dimension",
            ),
            token(
                "audio.knob_arc_segments",
                self.audio_controls.knob_arc_segments,
                "number",
            ),
            token(
                "audio.slider_track_sm",
                self.audio_controls.slider_track_widths[0],
                "dimension",
            ),
            token(
                "audio.slider_track_md",
                self.audio_controls.slider_track_widths[1],
                "dimension",
            ),
            token(
                "audio.slider_track_lg",
                self.audio_controls.slider_track_widths[2],
                "dimension",
            ),
        ]
    }

    /// Produce a lightweight conformance report for CI and docs.
    pub fn conformance_report(&self, reduced_motion_required: bool) -> DesignConformanceReport {
        let mut findings = Vec::new();

        finite_positive(
            &mut findings,
            "spacing.grid_unit",
            self.spacing.grid_unit,
            "spacing grid_unit must be finite and positive",
        );
        finite_non_negative(
            &mut findings,
            "spacing.control_padding_x",
            self.spacing.control_padding_x,
            "control horizontal padding must be finite and non-negative",
        );
        finite_non_negative(
            &mut findings,
            "spacing.control_padding_y",
            self.spacing.control_padding_y,
            "control vertical padding must be finite and non-negative",
        );
        finite_non_negative(
            &mut findings,
            "spacing.control_gap",
            self.spacing.control_gap,
            "control gap must be finite and non-negative",
        );
        finite_non_negative(
            &mut findings,
            "spacing.section_gap",
            self.spacing.section_gap,
            "section gap must be finite and non-negative",
        );

        for (id, value) in [
            ("radius.sm", self.corners.sm),
            ("radius.md", self.corners.md),
            ("radius.lg", self.corners.lg),
            ("radius.xl", self.corners.xl),
        ] {
            finite_non_negative(
                &mut findings,
                id,
                value,
                "corner radii must be finite and non-negative",
            );
        }

        finite_positive(
            &mut findings,
            "interaction.min_touch_target",
            self.interaction.min_touch_target,
            "minimum touch target must be finite and positive",
        );
        finite_non_negative(
            &mut findings,
            "interaction.focus_ring_width",
            self.interaction.focus_ring_width,
            "focus ring width must be finite and non-negative",
        );

        if self.language == DesignLanguage::AppleHig && self.interaction.min_touch_target < 44.0 {
            findings.push(ConformanceFinding {
                id: "apple.touch_target",
                message: "Apple HIG touch targets should be at least 44px".to_string(),
            });
        }
        if self.language == DesignLanguage::Material3 && self.interaction.min_touch_target < 48.0 {
            findings.push(ConformanceFinding {
                id: "material.touch_target",
                message: "Material 3 touch targets should be at least 48px".to_string(),
            });
        }

        if !(0.0..=1.0).contains(&self.elevation.shadow_opacity)
            || !self.elevation.shadow_opacity.is_finite()
        {
            findings.push(ConformanceFinding {
                id: "elevation.shadow_opacity",
                message: "shadow opacity must be finite and in [0, 1]".to_string(),
            });
        }

        if !(self.typography.small_size.is_finite()
            && self.typography.base_size.is_finite()
            && self.typography.large_size.is_finite()
            && self.typography.small_size > 0.0
            && self.typography.base_size > 0.0
            && self.typography.large_size > 0.0
            && self.typography.small_size <= self.typography.base_size
            && self.typography.base_size <= self.typography.large_size)
        {
            findings.push(ConformanceFinding {
                id: "typography.scale",
                message:
                    "typography sizes must be finite, positive, and ordered small <= base <= large"
                        .to_string(),
            });
        }
        if self.typography.dynamic_sizing && self.typography.large_size < self.typography.base_size
        {
            findings.push(ConformanceFinding {
                id: "typography.scale",
                message: "dynamic typography large_size must be >= base_size".to_string(),
            });
        }

        if !(self.animation.fast_ms <= self.animation.duration_ms
            && self.animation.duration_ms <= self.animation.slow_ms)
        {
            findings.push(ConformanceFinding {
                id: "motion.duration_order",
                message: "motion durations must be ordered fast <= default <= slow".to_string(),
            });
        }
        finite_positive(
            &mut findings,
            "motion.spring_stiffness",
            self.animation.spring_stiffness,
            "spring stiffness must be finite and positive",
        );
        finite_positive(
            &mut findings,
            "motion.spring_damping",
            self.animation.spring_damping,
            "spring damping must be finite and positive",
        );

        let motion = self.motion_spec(reduced_motion_required);
        if reduced_motion_required
            && (motion.duration_ms != 0 || motion.fast_ms != 0 || motion.slow_ms != 0)
        {
            findings.push(ConformanceFinding {
                id: "motion.reduced",
                message: "reduced-motion mode should collapse transition durations".to_string(),
            });
        }

        if self.layout.slider_height_compact > self.layout.slider_height_normal {
            findings.push(ConformanceFinding {
                id: "layout.slider_height_order",
                message: "compact slider height should not exceed normal slider height".to_string(),
            });
        }

        if !(self.audio_controls.knob_arc_sweep_deg.is_finite()
            && self.audio_controls.knob_arc_sweep_deg > 0.0
            && self.audio_controls.knob_arc_sweep_deg <= 360.0)
        {
            findings.push(ConformanceFinding {
                id: "audio.knob_arc_sweep",
                message: "knob arc sweep must be finite and in (0, 360]".to_string(),
            });
        }
        if self.audio_controls.knob_arc_segments < 12 {
            findings.push(ConformanceFinding {
                id: "audio.knob_arc_segments",
                message: "knob arc should use at least 12 segments".to_string(),
            });
        }
        for (index, width) in self.audio_controls.slider_track_widths.iter().enumerate() {
            if !width.is_finite() || *width <= 0.0 {
                findings.push(ConformanceFinding {
                    id: "audio.slider_track_width",
                    message: format!(
                        "slider track width at index {index} must be finite and positive"
                    ),
                });
            }
        }

        let token_count = self.style_dictionary_tokens().len();
        if token_count < 24 {
            findings.push(ConformanceFinding {
                id: "tokens.coverage",
                message: "style dictionary export should include core shape, spacing, interaction, typography, motion, and audio tokens".to_string(),
            });
        }

        DesignConformanceReport { findings }
    }

    pub fn motion_spec(&self, reduced_motion: bool) -> MotionSpec {
        if reduced_motion {
            MotionSpec {
                duration_ms: 0,
                fast_ms: 0,
                slow_ms: 0,
                prefer_spring: false,
                reduced_motion: true,
            }
        } else {
            MotionSpec {
                duration_ms: self.animation.duration_ms,
                fast_ms: self.animation.fast_ms,
                slow_ms: self.animation.slow_ms,
                prefer_spring: self.animation.prefer_spring,
                reduced_motion: false,
            }
        }
    }
}

pub(super) fn all_design_presets() -> Vec<(&'static str, DesignSystem)> {
    vec![
        ("neutral", DesignSystem::neutral()),
        ("apple_hig", DesignSystem::apple_hig()),
        ("material3", DesignSystem::material3()),
        ("fluent", DesignSystem::fluent()),
    ]
}
