// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use sotf_audio :: plugins :: { upmixer_output_channels } ;

pub(super) fn upmixer_settings_output_channels(speaker_config: &str, binaural_preview: bool) -> usize {
    if binaural_preview {
        2
    } else {
        upmixer_output_channels(speaker_config)
    }
}

