// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use ndarray::Array1;

/// NSGA environmental-selection variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NsgaVariant {
    /// NSGA-II: crowding-distance sorting inside the splitting front.
    Nsga2,
    /// NSGA-III: reference-direction niching inside the splitting front.
    Nsga3,
}

/// A Pareto solution returned by [`NsgaReport`].
#[derive(Debug, Clone)]
pub struct ParetoSolution {
    /// Parameter vector.
    pub x: Array1<f64>,
    /// Objective values, all minimised.
    pub objectives: Vec<f64>,
    /// Non-dominated rank. Rank `0` is the Pareto front.
    pub rank: usize,
    /// Crowding distance used by NSGA-II. Boundary points use infinity.
    pub crowding_distance: f64,
}

/// Result of an [`nsga`] run.
#[derive(Debug, Clone)]
pub struct NsgaReport {
    /// Rank-0 non-dominated front from the final population.
    pub pareto_front: Vec<ParetoSolution>,
    /// Final population, ranked and crowding-scored.
    pub population: Vec<ParetoSolution>,
    /// Objective evaluations consumed.
    pub nfev: usize,
    /// Generations completed.
    pub nit: usize,
    /// Whether at least one generation completed.
    pub success: bool,
    /// Human-readable termination message.
    pub message: String,
}

#[derive(Clone)]
pub(super) struct Individual {
    pub(super) x: Array1<f64>,
    pub(super) objectives: Vec<f64>,
    pub(super) rank: usize,
    pub(super) crowding_distance: f64,
}
