// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::color::D3Color;

/// Viridis color scale
pub(super) fn viridis_color(t: f64) -> D3Color {
    let colors = [
        D3Color::from_hex(0x440154),
        D3Color::from_hex(0x482878),
        D3Color::from_hex(0x3e4a89),
        D3Color::from_hex(0x31688e),
        D3Color::from_hex(0x26838f),
        D3Color::from_hex(0x1f9e89),
        D3Color::from_hex(0x35b779),
        D3Color::from_hex(0x6ece58),
        D3Color::from_hex(0xb5de2b),
        D3Color::from_hex(0xfde725),
    ];
    interpolate_colors(&colors, t)
}

/// Heat color scale (blue -> white -> red)
pub(super) fn heat_color(t: f64) -> D3Color {
    if t < 0.5 {
        let local_t = t * 2.0;
        D3Color::from_hex(0x0571b0).interpolate(&D3Color::from_hex(0xf7f7f7), local_t as f32)
    } else {
        let local_t = (t - 0.5) * 2.0;
        D3Color::from_hex(0xf7f7f7).interpolate(&D3Color::from_hex(0xca0020), local_t as f32)
    }
}

/// Cool color scale (cyan -> magenta)
pub(super) fn cool_color(t: f64) -> D3Color {
    D3Color::from_hex(0x00ffff).interpolate(&D3Color::from_hex(0xff00ff), t as f32)
}

/// Spectral color scale
pub(super) fn spectral_color(t: f64) -> D3Color {
    let colors = [
        D3Color::from_hex(0x9e0142),
        D3Color::from_hex(0xd53e4f),
        D3Color::from_hex(0xf46d43),
        D3Color::from_hex(0xfdae61),
        D3Color::from_hex(0xfee08b),
        D3Color::from_hex(0xe6f598),
        D3Color::from_hex(0xabdda4),
        D3Color::from_hex(0x66c2a5),
        D3Color::from_hex(0x3288bd),
        D3Color::from_hex(0x5e4fa2),
    ];
    interpolate_colors(&colors, t)
}

/// Grayscale color
pub(super) fn grayscale_color(t: f64) -> D3Color {
    let v = (t * 255.0) as u8;
    D3Color::rgb(v, v, v)
}

/// Monochrome color with brightness variation
pub(super) fn monochrome_color(base: D3Color, t: f64) -> D3Color {
    // Interpolate from dark version to light version
    let dark = D3Color {
        r: base.r * 0.2,
        g: base.g * 0.2,
        b: base.b * 0.2,
        a: base.a,
    };
    dark.interpolate(&base, t as f32)
}

/// Helper to interpolate through a color array
pub(super) fn interpolate_colors(colors: &[D3Color], t: f64) -> D3Color {
    let idx = (t * (colors.len() - 1) as f64) as usize;
    let idx = idx.min(colors.len() - 2);
    let local_t = (t * (colors.len() - 1) as f64) - idx as f64;
    colors[idx].interpolate(&colors[idx + 1], local_t as f32)
}

/// Normalize a vector
pub(super) fn normalize_vec(v: (f64, f64, f64)) -> (f64, f64, f64) {
    let len = (v.0 * v.0 + v.1 * v.1 + v.2 * v.2).sqrt();
    if len > 1e-10 {
        (v.0 / len, v.1 / len, v.2 / len)
    } else {
        (0.0, 0.0, 1.0)
    }
}

/// Format tick value for display based on the range
pub(super) fn format_tick_value(value: f64, min: f64, max: f64) -> String {
    let range = (max - min).abs();

    // For large numbers (like frequency), use k suffix
    if value.abs() >= 1000.0 && range >= 1000.0 {
        let k = value / 1000.0;
        if k == k.floor() {
            format!("{}k", k as i32)
        } else {
            format!("{:.1}k", k)
        }
    } else if range < 10.0 {
        // Small range - show one decimal
        format!("{:.1}", value)
    } else if value == value.floor() {
        // Integer value
        format!("{}", value as i32)
    } else {
        format!("{:.0}", value)
    }
}
