// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::ease_back_in;
use super::ease_back_in_out;
use super::ease_back_out;
use super::ease_bounce_in;
use super::ease_bounce_in_out;
use super::ease_bounce_out;
use super::ease_circle_in;
use super::ease_circle_in_out;
use super::ease_circle_out;
use super::ease_cubic_in;
use super::ease_cubic_in_out;
use super::ease_cubic_out;
use super::ease_elastic_in;
use super::ease_elastic_in_out;
use super::ease_elastic_out;
use super::ease_exp_in;
use super::ease_exp_in_out;
use super::ease_exp_out;
use super::ease_linear;
use super::ease_quad_in;
use super::ease_quad_in_out;
use super::ease_quad_out;
use super::ease_sin_in;
use super::ease_sin_in_out;
use super::ease_sin_out;

/// Enumeration of all easing types
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EaseType {
    Linear,
    QuadIn,
    QuadOut,
    QuadInOut,
    CubicIn,
    CubicOut,
    CubicInOut,
    SinIn,
    SinOut,
    SinInOut,
    ExpIn,
    ExpOut,
    ExpInOut,
    CircleIn,
    CircleOut,
    CircleInOut,
    ElasticIn,
    ElasticOut,
    ElasticInOut,
    BackIn,
    BackOut,
    BackInOut,
    BounceIn,
    BounceOut,
    BounceInOut,
}

impl EaseType {
    /// Apply the easing function to a value
    pub fn ease(&self, t: f64) -> f64 {
        match self {
            EaseType::Linear => ease_linear(t),
            EaseType::QuadIn => ease_quad_in(t),
            EaseType::QuadOut => ease_quad_out(t),
            EaseType::QuadInOut => ease_quad_in_out(t),
            EaseType::CubicIn => ease_cubic_in(t),
            EaseType::CubicOut => ease_cubic_out(t),
            EaseType::CubicInOut => ease_cubic_in_out(t),
            EaseType::SinIn => ease_sin_in(t),
            EaseType::SinOut => ease_sin_out(t),
            EaseType::SinInOut => ease_sin_in_out(t),
            EaseType::ExpIn => ease_exp_in(t),
            EaseType::ExpOut => ease_exp_out(t),
            EaseType::ExpInOut => ease_exp_in_out(t),
            EaseType::CircleIn => ease_circle_in(t),
            EaseType::CircleOut => ease_circle_out(t),
            EaseType::CircleInOut => ease_circle_in_out(t),
            EaseType::ElasticIn => ease_elastic_in(t),
            EaseType::ElasticOut => ease_elastic_out(t),
            EaseType::ElasticInOut => ease_elastic_in_out(t),
            EaseType::BackIn => ease_back_in(t),
            EaseType::BackOut => ease_back_out(t),
            EaseType::BackInOut => ease_back_in_out(t),
            EaseType::BounceIn => ease_bounce_in(t),
            EaseType::BounceOut => ease_bounce_out(t),
            EaseType::BounceInOut => ease_bounce_in_out(t),
        }
    }
}
