// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::ease_back_in;
use super::ease_back_out;
use super::ease_bounce_in;
use super::ease_bounce_in_out;
use super::ease_bounce_out;
use super::ease_circle_in;
use super::ease_circle_in_out;
use super::ease_circle_out;
use super::ease_cubic_in;
use super::ease_cubic_in_out;
use super::ease_cubic_out;
use super::ease_elastic_in;
use super::ease_elastic_out;
use super::ease_exp_in;
use super::ease_exp_in_out;
use super::ease_exp_out;
use super::ease_linear;
use super::ease_poly_in;
use super::ease_quad_in;
use super::ease_quad_in_out;
use super::ease_quad_out;
use super::ease_sin_in;
use super::ease_sin_in_out;
use super::ease_sin_out;
use super::ease_type::EaseType;

fn approx_eq(a: f64, b: f64) -> bool {
    (a - b).abs() < 1e-6
}

#[test]
fn test_linear() {
    assert!(approx_eq(ease_linear(0.0), 0.0));
    assert!(approx_eq(ease_linear(0.5), 0.5));
    assert!(approx_eq(ease_linear(1.0), 1.0));
}

#[test]
fn test_quad() {
    assert!(approx_eq(ease_quad_in(0.0), 0.0));
    assert!(approx_eq(ease_quad_in(1.0), 1.0));
    assert!(approx_eq(ease_quad_out(0.0), 0.0));
    assert!(approx_eq(ease_quad_out(1.0), 1.0));
    assert!(approx_eq(ease_quad_in_out(0.0), 0.0));
    assert!(approx_eq(ease_quad_in_out(0.5), 0.5));
    assert!(approx_eq(ease_quad_in_out(1.0), 1.0));
}

#[test]
fn test_cubic() {
    assert!(approx_eq(ease_cubic_in(0.0), 0.0));
    assert!(approx_eq(ease_cubic_in(1.0), 1.0));
    assert!(approx_eq(ease_cubic_out(0.0), 0.0));
    assert!(approx_eq(ease_cubic_out(1.0), 1.0));
    assert!(approx_eq(ease_cubic_in_out(0.0), 0.0));
    assert!(approx_eq(ease_cubic_in_out(0.5), 0.5));
    assert!(approx_eq(ease_cubic_in_out(1.0), 1.0));
}

#[test]
fn test_sin() {
    assert!(approx_eq(ease_sin_in(0.0), 0.0));
    assert!(approx_eq(ease_sin_in(1.0), 1.0));
    assert!(approx_eq(ease_sin_out(0.0), 0.0));
    assert!(approx_eq(ease_sin_out(1.0), 1.0));
    assert!(approx_eq(ease_sin_in_out(0.0), 0.0));
    assert!(approx_eq(ease_sin_in_out(0.5), 0.5));
    assert!(approx_eq(ease_sin_in_out(1.0), 1.0));
}

#[test]
fn test_exp() {
    assert!(approx_eq(ease_exp_in(0.0), 0.0));
    assert!(approx_eq(ease_exp_in(1.0), 1.0));
    assert!(approx_eq(ease_exp_out(0.0), 0.0));
    assert!(approx_eq(ease_exp_out(1.0), 1.0));
    assert!(approx_eq(ease_exp_in_out(0.0), 0.0));
    assert!(approx_eq(ease_exp_in_out(1.0), 1.0));
}

#[test]
fn test_circle() {
    assert!(approx_eq(ease_circle_in(0.0), 0.0));
    assert!(approx_eq(ease_circle_in(1.0), 1.0));
    assert!(approx_eq(ease_circle_out(0.0), 0.0));
    assert!(approx_eq(ease_circle_out(1.0), 1.0));
    assert!(approx_eq(ease_circle_in_out(0.0), 0.0));
    assert!(approx_eq(ease_circle_in_out(0.5), 0.5));
    assert!(approx_eq(ease_circle_in_out(1.0), 1.0));
}

#[test]
fn test_elastic() {
    assert!(approx_eq(ease_elastic_in(0.0), 0.0));
    assert!(approx_eq(ease_elastic_in(1.0), 1.0));
    assert!(approx_eq(ease_elastic_out(0.0), 0.0));
    assert!(approx_eq(ease_elastic_out(1.0), 1.0));
}

#[test]
fn test_back() {
    assert!(approx_eq(ease_back_in(0.0), 0.0));
    assert!(approx_eq(ease_back_in(1.0), 1.0));
    assert!(approx_eq(ease_back_out(0.0), 0.0));
    assert!(approx_eq(ease_back_out(1.0), 1.0));
    // Back goes outside [0, 1] during animation
    assert!(ease_back_in(0.5) < 0.0);
    assert!(ease_back_out(0.5) > 1.0);
}

#[test]
fn test_bounce() {
    assert!(approx_eq(ease_bounce_in(0.0), 0.0));
    assert!(approx_eq(ease_bounce_in(1.0), 1.0));
    assert!(approx_eq(ease_bounce_out(0.0), 0.0));
    assert!(approx_eq(ease_bounce_out(1.0), 1.0));
    assert!(approx_eq(ease_bounce_in_out(0.0), 0.0));
    assert!(approx_eq(ease_bounce_in_out(1.0), 1.0));
}

#[test]
fn test_poly() {
    let poly3_in = ease_poly_in(3.0);
    assert!(approx_eq(poly3_in(0.0), 0.0));
    assert!(approx_eq(poly3_in(1.0), 1.0));
    assert!(approx_eq(poly3_in(0.5), ease_cubic_in(0.5)));
}

#[test]
fn test_ease_type_enum() {
    assert!(approx_eq(EaseType::Linear.ease(0.5), 0.5));
    assert!(approx_eq(EaseType::CubicInOut.ease(0.0), 0.0));
    assert!(approx_eq(EaseType::CubicInOut.ease(1.0), 1.0));
}
