impl Showcase {
    fn render_progress_section(&self, cx: &mut Context<Self>) -> impl IntoElement {
        let section_title = cx.t(TranslationKey::SectionProgress);

        VStack::new()
            .spacing(StackSpacing::Lg)
            .child(self.section_header(section_title))
            // Linear Progress - Various Values
            .child(
                VStack::new()
                    .spacing(StackSpacing::Sm)
                    .child(Text::new("Linear Progress - Various Values").weight(TextWeight::Medium))
                    .child(
                        VStack::new()
                            .spacing(StackSpacing::Sm)
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(35.0)).child(Text::new("0%").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.0).size(ProgressSize::Md))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(35.0)).child(Text::new("25%").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.25).size(ProgressSize::Md))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(35.0)).child(Text::new("50%").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.50).size(ProgressSize::Md))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(35.0)).child(Text::new("75%").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.75).size(ProgressSize::Md))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(35.0)).child(Text::new("100%").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(1.0).size(ProgressSize::Md))),
                            ),
                    ),
            )
            // Linear Progress - Sizes
            .child(
                VStack::new()
                    .spacing(StackSpacing::Sm)
                    .child(Text::new("Linear Progress - Sizes").weight(TextWeight::Medium))
                    .child(
                        VStack::new()
                            .spacing(StackSpacing::Md)
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(30.0)).child(Text::new("Sm").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.6).size(ProgressSize::Sm))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(30.0)).child(Text::new("Md").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.6).size(ProgressSize::Md))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(30.0)).child(Text::new("Lg").size(TextSize::Xs)))
                                    .child(div().w(px(250.0)).child(Progress::new(0.6).size(ProgressSize::Lg))),
                            ),
                    ),
            )
            // Linear Progress - Variants
            .child(
                VStack::new()
                    .spacing(StackSpacing::Sm)
                    .child(Text::new("Linear Progress - Variants").weight(TextWeight::Medium))
                    .child(
                        VStack::new()
                            .spacing(StackSpacing::Md)
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(55.0)).child(Text::new("Default").size(TextSize::Xs)))
                                    .child(div().w(px(200.0)).child(Progress::new(0.7).variant(ProgressVariant::Default))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(55.0)).child(Text::new("Success").size(TextSize::Xs)))
                                    .child(div().w(px(200.0)).child(Progress::new(1.0).variant(ProgressVariant::Success))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(55.0)).child(Text::new("Warning").size(TextSize::Xs)))
                                    .child(div().w(px(200.0)).child(Progress::new(0.5).variant(ProgressVariant::Warning))),
                            )
                            .child(
                                HStack::new()
                                    .spacing(StackSpacing::Md)
                                    .align(StackAlign::Center)
                                    .child(div().w(px(55.0)).child(Text::new("Error").size(TextSize::Xs)))
                                    .child(div().w(px(200.0)).child(Progress::new(0.3).variant(ProgressVariant::Error))),
                            ),
                    ),
            )
            // Circular Progress - Various Values
            .child(
                VStack::new()
                    .spacing(StackSpacing::Sm)
                    .child(Text::new("Circular Progress - Various Values").weight(TextWeight::Medium))
                    .child(
                        HStack::new()
                            .spacing(StackSpacing::Lg)
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.0).size(px(48.0)))
                                    .child(Text::new("0%").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.25).size(px(48.0)))
                                    .child(Text::new("25%").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.50).size(px(48.0)))
                                    .child(Text::new("50%").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.75).size(px(48.0)))
                                    .child(Text::new("75%").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(1.0).size(px(48.0)))
                                    .child(Text::new("100%").size(TextSize::Xs).muted(true)),
                            ),
                    ),
            )
            // Circular Progress - Sizes & Variants
            .child(
                VStack::new()
                    .spacing(StackSpacing::Sm)
                    .child(Text::new("Circular Progress - Sizes & Variants").weight(TextWeight::Medium))
                    .child(
                        HStack::new()
                            .spacing(StackSpacing::Lg)
                            .align(StackAlign::End)
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.6).size(px(24.0)))
                                    .child(Text::new("24px").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.6).size(px(48.0)))
                                    .child(Text::new("48px").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.6).size(px(64.0)))
                                    .child(Text::new("64px").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(1.0).size(px(48.0)).variant(ProgressVariant::Success))
                                    .child(Text::new("Success").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.5).size(px(48.0)).variant(ProgressVariant::Warning))
                                    .child(Text::new("Warning").size(TextSize::Xs).muted(true)),
                            )
                            .child(
                                VStack::new()
                                    .spacing(StackSpacing::Xs)
                                    .align(StackAlign::Center)
                                    .child(CircularProgress::new(0.3).size(px(48.0)).variant(ProgressVariant::Error))
                                    .child(Text::new("Error").size(TextSize::Xs).muted(true)),
                            ),
                    ),
            )
    }
}
