// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::listener_id::ListenerId;
use super::types::ListenerFn;

/// Internal listener storage
pub(super) struct Listener {
    pub(super) id: ListenerId,
    pub(super) type_: String,
    pub(super) callback: ListenerFn,
    #[allow(dead_code)]
    pub(super) once: bool,
}

impl std::fmt::Debug for Listener {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Listener")
            .field("id", &self.id)
            .field("type_", &self.type_)
            .field("once", &self.once)
            .finish()
    }
}
