[group('bench')]
bench-plugins:
	cargo bench -p plugins --bench binaural-decoder-benchmark
	cargo bench -p plugins --bench upmixer-benchmark
	cargo bench -p plugins --bench compressor-benchmark

# ----------------------------------------------------------------------
# QA PLUGINS
# ----------------------------------------------------------------------

[group('qa-plugins')]
qa-plugins: qa-plugin-fuzzer qa-plugin-diagnostics

[group('qa-plugins')]
qa-plugin-fuzzer: qa-plugin-fuzzer-simple qa-plugin-fuzzer-1ch qa-plugin-fuzzer-2ch qa-plugin-fuzzer-6ch

[group('qa-plugins')]
qa-plugin-fuzzer-simple:
	@for file in ./data_generated/test-audio/wav/pink_noise/pink_noise_*.wav; do \
		for plugin in gain eq compressor limiter gate delay loudness_monitor abcompare expander mbcomp mbexp matrix mutesolo denoiser spectrum pnd; do \
			echo "=== Fuzzing plugin: $plugin with $file ==="; \
			cargo run --release --bin plugin-fuzzer -- --file "$file" --plugin $plugin || exit 1; \
		done; \
	done

[group('qa-plugins')]
qa-plugin-fuzzer-1ch:
	@for file in ./data_generated/test-audio/wav/pink_noise/pink_noise_ch1_*.wav; do \
		for plugin in mono_to_stereo; do \
			echo "=== Fuzzing plugin: $plugin with $file ==="; \
			cargo run --release --bin plugin-fuzzer -- --file "$file" --plugin $plugin || exit 1; \
		done; \
	done

[group('qa-plugins')]
qa-plugin-fuzzer-2ch:
	@for file in ./data_generated/test-audio/wav/pink_noise/pink_noise_ch2_*.wav; do \
		for plugin in fletcher upmixer xtc crossfeed; do \
			echo "=== Fuzzing plugin: $plugin with $file ==="; \
			cargo run --release --bin plugin-fuzzer -- --file "$file" --plugin $plugin || exit 1; \
		done; \
	done

[group('qa-plugins')]
qa-plugin-fuzzer-6ch:
	@for file in ./data_generated/test-audio/wav/pink_noise/pink_noise_ch6_*.wav; do \
		for plugin in downmix; do \
			echo "=== Fuzzing plugin: $plugin with $file ==="; \
			cargo run --release --bin plugin-fuzzer -- --file "$file" --plugin $plugin || exit 1; \
		done; \
	done

[group('qa-plugins')]
qa-plugin-diagnostics:
	cargo run --release --package plugins --bin qa-ab-compare --features qa
	cargo run --release --package plugins --bin qa-compressor --features qa
	cargo run --release --package plugins --bin qa-delay --features qa
	cargo run --release --package plugins --bin qa-downmix --features qa
	cargo run --release --package plugins --bin qa-eq --features qa
	cargo run --release --package plugins --bin qa-expander --features qa
	cargo run --release --package plugins --bin qa-gain --features qa
	cargo run --release --package plugins --bin qa-gate --features qa
	cargo run --release --package plugins --bin qa-limiter --features qa
	cargo run --release --package plugins --bin qa-loudness-compensation --features qa
	cargo run --release --package plugins --bin qa-mono-to-stereo --features qa
	cargo run --release --package plugins --bin qa-multiband-compressor --features qa
	cargo run --release --package plugins --bin qa-multiband-expander --features qa
	cargo run --release --package plugins --bin qa-pnd --features qa
	cargo run --release --package plugins --bin qa-upmixer --features qa
	cargo run --release --package plugins --bin qa-xtc --features qa

