//! Shared workflow helpers used by AutoEQ binaries
//!
//! This module centralizes the common pipeline steps for loading input data,
//! building target curves, preparing objective data, and running optimization.

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub use crate::optim::setup::*;

pub mod resume;

mod build;
mod load;
mod misc;
mod optimize;
#[cfg(test)]
mod tests;
mod types;

pub use build::*;
pub use load::*;
pub use optimize::*;
pub use types::*;
