// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use sotf_host::parameters::{ParameterId, ParameterValue};
use sotf_host::plugin::{InPlacePlugin, ProcessContext};
use super::consts;
use super::gate_data;
use super::gate_data::GateData;
use super::gate_plugin::GatePlugin;
use super::types::GatePluginParams;

    use crate::*;
    #[test]
    fn test_gate_basic() {
        let mut p = GatePlugin::new(1, -20.0, 100.0, 1.0, 10.0, 50.0);
        p.initialize(48000).unwrap();
        let mut b = vec![0.05; 1000];
        p.process_in_place(&mut b, &ProcessContext::new(48000, 1000))
            .unwrap();
        assert!(b[999] < 0.05);
    }

    #[test]
    fn test_hold_samples_precomputed_and_updated() {
        let mut p = GatePlugin::new(1, -20.0, 10.0, 1.0, 10.0, 50.0);
        assert_eq!(p.hold_samples, 441);

        p.initialize(96000).unwrap();
        assert_eq!(p.hold_samples, 960);

        p.set_parameter(ParameterId::from("hold"), ParameterValue::Float(1.5))
            .unwrap();
        assert_eq!(p.hold_samples, 144);
    }

    /// CRITICAL: Attack must control gate opening speed, Release must control closing speed.
    /// With fast attack (1 ms) and slow release (500 ms), the gate should open quickly
    /// when the signal rises above threshold.
    #[test]
    fn test_attack_controls_opening_speed() {
        let sr = 48000u32;
        let mut p = GatePlugin::new(1, -20.0, 100.0, 1.0, 0.0, 500.0);
        p.initialize(sr).unwrap();

        // Close the gate with very quiet signal (-100 dBFS)
        let quiet_len = sr as usize;
        let mut quiet = vec![0.00001f32; quiet_len];
        let ctx = ProcessContext::new(sr, quiet_len);
        p.process_in_place(&mut quiet, &ctx).unwrap();

        // Switch to loud signal (-6 dBFS, well above threshold)
        let loud_len = sr as usize / 10; // 100 ms
        let input_level = 0.5f32;
        let mut loud = vec![input_level; loud_len];
        let ctx2 = ProcessContext::new(sr, loud_len);
        p.process_in_place(&mut loud, &ctx2).unwrap();

        // With fast attack (1 ms) the gate should be essentially fully open
        // within the last 10 ms of the loud section.
        let tail_start = loud_len - sr as usize / 100;
        let avg_output: f32 =
            loud[tail_start..].iter().sum::<f32>() / (loud_len - tail_start) as f32;
        assert!(
            avg_output > input_level * 0.95,
            "Gate should open quickly with fast attack (1 ms), but avg output was {avg_output}"
        );
    }

    /// CRITICAL: Release must control gate closing speed.
    /// With slow attack (500 ms) and fast release (1 ms), the gate should close quickly
    /// when the signal drops below threshold.
    #[test]
    fn test_release_controls_closing_speed() {
        let sr = 48000u32;
        let mut p = GatePlugin::new(1, -20.0, 100.0, 500.0, 0.0, 1.0);
        p.initialize(sr).unwrap();

        // Open the gate with loud signal (-6 dBFS)
        let loud_len = sr as usize;
        let mut loud = vec![0.5f32; loud_len];
        let ctx = ProcessContext::new(sr, loud_len);
        p.process_in_place(&mut loud, &ctx).unwrap();

        // Switch to very quiet signal (-60 dBFS, well below threshold)
        let quiet_len = sr as usize / 10; // 100 ms
        let quiet_input = 0.001f32;
        let mut quiet = vec![quiet_input; quiet_len];
        let ctx2 = ProcessContext::new(sr, quiet_len);
        p.process_in_place(&mut quiet, &ctx2).unwrap();

        // With fast release (1 ms) the gate should be essentially fully closed
        // within the last 10 ms of the quiet section.
        let tail_start = quiet_len - sr as usize / 100;
        let avg_output: f32 =
            quiet[tail_start..].iter().sum::<f32>() / (quiet_len - tail_start) as f32;
        assert!(
            avg_output < quiet_input * 0.1,
            "Gate should close quickly with fast release (1 ms), but avg output was {avg_output}"
        );
    }

    /// CRITICAL: In linked stereo mode the monitoring cache `is_open` must reflect
    /// the actual gate state. When the gate is fully closed it must report false.
    #[test]
    fn test_linked_stereo_monitoring_cache_reports_closed() {
        let sr = 48000u32;
        let mut p = GatePlugin::from_params(
            2,
            GatePluginParams {
                threshold_db: -20.0,
                ratio: 100.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 10.0,
                mix: 1.0,
                link_channels: true,
                sidechain_hpf_hz: 0.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p.initialize(sr).unwrap();

        let block_size = 1024;
        let num_blocks = 20; // enough to trigger cache update (every 10 blocks)
        let quiet = vec![0.0001f32; block_size * 2];
        for _ in 0..num_blocks {
            let mut buf = quiet.clone();
            let ctx = ProcessContext::new(sr, block_size);
            p.process_in_place(&mut buf, &ctx).unwrap();
        }

        let data = p.get_data().unwrap();
        let gate_data = data.downcast_ref::<GateData>().unwrap();
        assert!(
            !gate_data.is_open,
            "Linked stereo gate should report is_open=false when fully closed"
        );
    }

    /// Sidechain HPF at 200 Hz: a 50 Hz signal below threshold should NOT open
    /// the gate (HPF filters out the low-freq detection signal). A 1 kHz signal
    /// at the same level should open it.
    #[test]
    fn test_sidechain_hpf_filters_low_freq_detection() {
        let sr = 48000u32;
        let threshold_db = -20.0;
        // Signal amplitude is above threshold in raw dB but below after HPF
        let amplitude = 10.0_f32.powf(-15.0 / 20.0); // -15 dBFS (above -20 threshold)

        // --- Test 1: 50 Hz signal with HPF=200 Hz. Gate should stay closed. ---
        let mut p_low = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db,
                ratio: 100.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 10.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 200.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p_low.initialize(sr).unwrap();

        let num_frames = 9600; // 200ms
        let mut buf_low = vec![0.0f32; num_frames];
        for (i, sample) in buf_low.iter_mut().enumerate() {
            *sample = amplitude * (2.0 * std::f32::consts::PI * 50.0 * i as f32 / sr as f32).sin();
        }

        let ctx = ProcessContext::new(sr, num_frames);
        p_low.process_in_place(&mut buf_low, &ctx).unwrap();

        // The 50 Hz signal should be significantly attenuated because the HPF
        // at 200 Hz filters out the 50 Hz from the sidechain detection.
        let rms_low: f32 =
            buf_low[4800..].iter().map(|x| x * x).sum::<f32>() / (num_frames - 4800) as f32;
        let rms_low = rms_low.sqrt();

        // --- Test 2: 1 kHz signal with HPF=200 Hz. Gate should open. ---
        let mut p_high = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db,
                ratio: 100.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 10.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 200.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p_high.initialize(sr).unwrap();

        let mut buf_high = vec![0.0f32; num_frames];
        for (i, sample) in buf_high.iter_mut().enumerate() {
            *sample =
                amplitude * (2.0 * std::f32::consts::PI * 1000.0 * i as f32 / sr as f32).sin();
        }

        p_high.process_in_place(&mut buf_high, &ctx).unwrap();

        let rms_high: f32 =
            buf_high[4800..].iter().map(|x| x * x).sum::<f32>() / (num_frames - 4800) as f32;
        let rms_high = rms_high.sqrt();

        // 1 kHz should pass through much louder than 50 Hz (gate open vs closed)
        assert!(
            rms_high > rms_low * 2.0,
            "1kHz (RMS={rms_high:.5}) should pass through gate much louder than 50Hz (RMS={rms_low:.5}) \
             when sidechain HPF=200Hz"
        );
    }

    /// Hysteresis test: a signal that oscillates +/-2 dB around the threshold should
    /// not cause the gate to "chatter" (rapidly open and close).
    ///
    /// Setup:
    ///   threshold = -20 dB, hysteresis = 4 dB
    ///   -> open threshold  = -20 dB
    ///   -> close threshold = -24 dB
    ///
    /// The test signal alternates every 100 samples between -18 dBFS and -22 dBFS.
    /// Both levels are between -24 dB and -20 dB when the gate is open, so once
    /// opened the gate should remain open for the entire alternating region.
    ///
    /// Without hysteresis the gate would open on -18 dB and close on -22 dB every
    /// 100-sample segment, producing many transitions.  With hysteresis it should
    /// stay open after the first opening.
    #[test]
    fn test_gate_hysteresis_no_chatter() {
        let sr = 48000u32;
        // Fast attack/release so the envelope reacts within the 100-sample segments
        let mut p = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db: -20.0,
                hysteresis_db: 4.0,
                ratio: 100.0,
                attack_ms: 0.5,
                hold_ms: 0.0,
                release_ms: 1.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 0.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p.initialize(sr).unwrap();

        // Build 1-second buffer that alternates every 100 samples between
        // -18 dBFS (above open threshold -20 dB) and -22 dBFS (between open and
        // close thresholds, so gate should stay open once opened).
        let amp_high = 10.0_f32.powf(-18.0 / 20.0); // -18 dBFS
        let amp_low = 10.0_f32.powf(-22.0 / 20.0); // -22 dBFS  (above close threshold -24 dB)
        let num_frames = sr as usize; // 1 second
        let mut buffer: Vec<f32> = (0..num_frames)
            .map(|i| {
                if (i / 100) % 2 == 0 {
                    amp_high
                } else {
                    amp_low
                }
            })
            .collect();

        let ctx = ProcessContext::new(sr, num_frames);
        p.process_in_place(&mut buffer, &ctx).unwrap();

        // Count how many times the output crosses a "gate closed" boundary.
        // If the gate chatters, the output will swing between near-zero and amp_low
        // each 100-sample segment.  With hysteresis the output should be consistently
        // passed through after the initial opening.
        //
        // Threshold for "effectively gated": output below 10 % of amp_low.
        let closed_threshold = amp_low * 0.1;

        // Skip the first 500 samples (attack / settling period).
        let steady_state = &buffer[500..];

        // Count sign-changes between "open" and "closed" state.
        let mut transitions = 0usize;
        let mut prev_open = steady_state[0] > closed_threshold;
        for &s in steady_state.iter().skip(1) {
            let cur_open = s > closed_threshold;
            if cur_open != prev_open {
                transitions += 1;
                prev_open = cur_open;
            }
        }

        // With hysteresis the gate should open once and stay open: 0 or at most 1
        // transition (the initial opening) throughout the steady-state region.
        // Without hysteresis we would expect ~2 * (num_frames / 100) ~ 190 transitions.
        assert!(
            transitions <= 2,
            "Gate with hysteresis=4dB should not chatter on a +/-2dB oscillating signal, \
             but observed {transitions} open/closed transitions in steady-state"
        );
    }

    /// Regression test: gate open/close decisions use linear-space thresholds.
    ///
    /// Prior to this refactor, `process_in_place` called `fast_log10(det)` on every
    /// frame to compare the detected envelope against the threshold in dB space.
    /// The gate now compares the linear envelope directly against pre-computed
    /// `threshold_linear` and `close_threshold_linear`, eliminating `fast_log10`
    /// from the hot per-frame audio path.  `fast_log10` is only called when the
    /// gate is actually closing and we need to compute the attenuation curve in
    /// dB space.
    #[test]
    fn test_gate_linear_threshold_no_fast_log10_in_decision() {
        let sr = 48000u32;
        let mut p = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db: -20.0,
                ratio: 100.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 10.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 0.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p.initialize(sr).unwrap();

        // Signal exactly at the linear threshold (-20 dBFS = 0.1).
        // With exact linear comparison the gate should remain open.
        let input_level = 0.1f32;
        let frames = sr as usize / 10;
        let mut buf = vec![input_level; frames];
        let ctx = ProcessContext::new(sr, frames);
        p.process_in_place(&mut buf, &ctx).unwrap();

        let tail_start = frames - sr as usize / 100;
        let avg_output: f32 = buf[tail_start..].iter().sum::<f32>() / (frames - tail_start) as f32;
        assert!(
            (avg_output - input_level).abs() < 0.001,
            "Gate should stay open for signal at exact threshold (linear comparison), \
             avg output was {avg_output}"
        );
    }

    #[test]
    fn test_soft_knee_curve_is_continuous_at_boundaries() {
        let mut p = GatePlugin::new(1, -20.0, 4.0, 1.0, 0.0, 10.0);
        p.range_db = 80.0;
        p.knee_db = 6.0;

        let threshold = -20.0;
        let upper = threshold + p.knee_db / 2.0;
        let lower = threshold - p.knee_db / 2.0;
        let slope = 1.0 - 1.0 / p.ratio.max(1.0);

        let at_upper = p.calculate_gate_attenuation(upper, threshold);
        let just_inside_upper = p.calculate_gate_attenuation(upper - 0.001, threshold);
        assert!(at_upper.abs() < 1e-6);
        assert!(
            just_inside_upper < 0.001,
            "knee should enter smoothly near upper boundary, got {just_inside_upper}"
        );

        let at_lower = p.calculate_gate_attenuation(lower, threshold);
        let expected_lower = (threshold - lower) * slope;
        assert!(
            (at_lower - expected_lower).abs() < 1e-5,
            "lower boundary should meet below-threshold line: got {at_lower}, expected {expected_lower}"
        );
    }

    // -------------------------------------------------------------------------
    // set_parameter smoke tests and edge cases
    // -------------------------------------------------------------------------

    #[test]
    fn test_set_parameter_all_params_roundtrip() {
        let mut p = GatePlugin::new(1, -20.0, 10.0, 1.0, 0.0, 50.0);
        p.initialize(48000).unwrap();

        let cases: &[(&str, ParameterValue)] = &[
            ("threshold", ParameterValue::Float(-30.0)),
            ("ratio", ParameterValue::Float(20.0)),
            ("attack", ParameterValue::Float(5.0)),
            ("hold", ParameterValue::Float(15.0)),
            ("release", ParameterValue::Float(200.0)),
            ("mix", ParameterValue::Float(0.5)),
            ("link_channels", ParameterValue::Bool(false)),
            ("sidechain_hpf_hz", ParameterValue::Float(100.0)),
            ("range_db", ParameterValue::Float(40.0)),
            ("hysteresis_db", ParameterValue::Float(2.0)),
            ("knee_db", ParameterValue::Float(3.0)),
            ("lookahead_ms", ParameterValue::Float(5.0)),
        ];

        for &(id, ref value) in cases {
            p.set_parameter(ParameterId::from(id), value.clone())
                .unwrap();
            let got = p.get_parameter(&ParameterId::from(id));
            assert_eq!(got, Some(value.clone()), "roundtrip failed for {}", id);
        }
    }

    #[test]
    fn test_set_parameter_clamps_out_of_bounds() {
        let mut p = GatePlugin::new(1, -20.0, 10.0, 1.0, 0.0, 50.0);
        p.initialize(48000).unwrap();

        // param_bridge clamps floats to range instead of returning Err
        p.set_parameter(ParameterId::from("threshold"), ParameterValue::Float(10.0))
            .unwrap();
        assert_eq!(p.threshold_db, 0.0);

        p.set_parameter(ParameterId::from("threshold"), ParameterValue::Float(-100.0))
            .unwrap();
        assert_eq!(p.threshold_db, -80.0);

        p.set_parameter(ParameterId::from("mix"), ParameterValue::Float(2.0))
            .unwrap();
        assert_eq!(p.mix, 1.0);

        p.set_parameter(ParameterId::from("mix"), ParameterValue::Float(-0.5))
            .unwrap();
        assert_eq!(p.mix, 0.0);
    }

    #[test]
    fn test_set_parameter_unknown_id_returns_error() {
        let mut p = GatePlugin::new(1, -20.0, 10.0, 1.0, 0.0, 50.0);
        p.initialize(48000).unwrap();

        let result = p.set_parameter(
            ParameterId::from("not_a_param"),
            ParameterValue::Float(1.0),
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_set_parameter_type_mismatch_returns_error() {
        let mut p = GatePlugin::new(1, -20.0, 10.0, 1.0, 0.0, 50.0);
        p.initialize(48000).unwrap();

        // threshold is float, not bool
        let result = p.set_parameter(
            ParameterId::from("threshold"),
            ParameterValue::Bool(true),
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_process_empty_buffer_returns_zero() {
        let mut p = GatePlugin::new(1, -20.0, 10.0, 1.0, 0.0, 50.0);
        p.initialize(48000).unwrap();

        let mut buf = vec![0.0f32; 0];
        let ctx = ProcessContext::new(48000, 0);
        let frames = p.process_in_place(&mut buf, &ctx).unwrap();
        assert_eq!(frames, 0);
    }

    #[test]
    fn test_input_channels_doubles_with_external_sidechain() {
        let mut p = GatePlugin::from_params(
            2,
            GatePluginParams {
                threshold_db: -40.0,
                ratio: 10.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 50.0,
                mix: 1.0,
                link_channels: true,
                sidechain_hpf_hz: 0.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: true,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p.initialize(48000).unwrap();

        assert_eq!(p.channels(), 2);
        assert_eq!(p.input_channels(), 4);
    }

    #[test]
    fn test_from_params_detection_mode_rms() {
        let p = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db: -40.0,
                ratio: 10.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 50.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 0.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "rms".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        assert_eq!(p.detection_mode_index, 1);
    }

    #[test]
    fn test_from_params_hpf_order_4th() {
        let mut p = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db: -40.0,
                ratio: 10.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 50.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 100.0,
                sidechain_hpf_order: "4th".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 0.0,
            },
        );
        p.initialize(48000).unwrap();
        assert_eq!(p.sidechain_hpf_order_index, 1);
        // Biquads should be built for 4th order (2 sections)
        assert_eq!(p.sidechain_hpf_biquads.len(), 1);
        assert_eq!(p.sidechain_hpf_biquads[0].len(), 2);
    }

    #[test]
    fn test_info_and_latency() {
        let p = GatePlugin::new(2, -20.0, 10.0, 1.0, 0.0, 50.0);
        assert_eq!(p.channels(), 2);
        let info = p.info();
        assert_eq!(info.name, "Gate");
        assert_eq!(p.latency_samples(), 0);

        let mut p2 = GatePlugin::from_params(
            1,
            GatePluginParams {
                threshold_db: -40.0,
                ratio: 10.0,
                attack_ms: 1.0,
                hold_ms: 0.0,
                release_ms: 50.0,
                mix: 1.0,
                link_channels: false,
                sidechain_hpf_hz: 0.0,
                sidechain_hpf_order: "2nd".to_string(),
                detection_mode: "peak".to_string(),
                sidechain_external: false,
                range_db: 80.0,
                hysteresis_db: 0.0,
                knee_db: 0.0,
                lookahead_ms: 5.0,
            },
        );
        p2.initialize(48000).unwrap();
        assert!(p2.latency_samples() > 0);
    }

