// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use serde::{Deserialize, Serialize};

/// Motion preset used by the designer preview controls.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MotionPreset {
    pub id: String,
    pub label: String,
    pub reduced_motion: bool,
}

impl MotionPreset {
    pub fn new(id: impl Into<String>, label: impl Into<String>, reduced_motion: bool) -> Self {
        Self {
            id: id.into(),
            label: label.into(),
            reduced_motion,
        }
    }
}
