[package]
name = "sotf-audio-plugins"
description = "an audio player and recorder that support audio plugins"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "sotf_plugins"
path = "src/lib.rs"

[features]
default = ["sofa_support"]
hal = ["sotf-hal"]
sofa_support = ["dep:netcdf"]

[dependencies]
tokio = { workspace = true }
ndarray = { workspace = true }
notify = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cpal = { workspace = true }
tempfile = { workspace = true }
serde_yaml = { workspace = true }
which = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }
netcdf =  { workspace = true, optional = true }
parking_lot = { workspace = true }
rustfft = { workspace = true }
realfft = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
directories = { workspace = true }
rusqlite = { workspace = true, features = ["bundled"] }
walkdir = { workspace = true }
autoeq-env = { workspace = true }
math-iir-fir = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }

# Audio decoding/encoding
symphonia = { workspace = true, default-features = false }
symphonia-core = { workspace = true }
symphonia-metadata = { workspace = true }
symphonia-bundle-flac = { workspace = true }
symphonia-bundle-mp3 = { workspace = true }
symphonia-codec-aac = { workspace = true }
symphonia-codec-alac = { workspace = true }
symphonia-codec-pcm = { workspace = true }
symphonia-codec-vorbis = { workspace = true }
symphonia-format-riff = { workspace = true }
symphonia-format-ogg = { workspace = true }
symphonia-format-isomp4 = { workspace = true }
ebur128 = { workspace = true }
hound = { workspace = true }
rubato = { workspace = true }
id3 = { workspace = true }
metaflac = { workspace = true }
bincode = "1.3.3"
anyhow = "1.0"

[target.'cfg(unix)'.dependencies]
signal-hook = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
sotf-hal = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }

[[bin]]
name = "plugin-fuzzer"
path = "bin/plugin_fuzzer.rs"

[[bin]]
name = "sofa_to_sqlite"
path = "bin/sofa_to_sqlite.rs"
required-features = ["sofa_support"]

[[bench]]
name = "binaural-decoder-benchmark"
harness = false

[[bench]]
name = "upmixer-benchmark"
harness = false

[[bench]]
name = "compressor-benchmark"
harness = false



