// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use gpui_themes :: { ThemeSchedule , TimeOfDay } ;

#[derive(Clone, Copy)]
pub(super) enum ScheduleBoundary {
    LightStart,
    DarkStart,
}

pub(super) fn set_schedule_boundary(
    mut schedule: ThemeSchedule,
    boundary: ScheduleBoundary,
    time: TimeOfDay,
) -> ThemeSchedule {
    match boundary {
        ScheduleBoundary::LightStart => schedule.light_start = time,
        ScheduleBoundary::DarkStart => schedule.dark_start = time,
    }
    schedule
}

