// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::path::PathBuf;

/// Configuration for the interactive component lab app.
#[derive(Debug, Clone)]
pub struct LabAppConfig {
    pub stories_dir: PathBuf,
    pub token_paths: Vec<PathBuf>,
    pub watch: bool,
}

impl LabAppConfig {
    pub fn new(stories_dir: PathBuf, token_paths: Vec<PathBuf>) -> Self {
        Self {
            stories_dir,
            token_paths,
            watch: false,
        }
    }

    pub fn with_watch(mut self, watch: bool) -> Self {
        self.watch = watch;
        self
    }
}

impl Default for LabAppConfig {
    fn default() -> Self {
        Self {
            stories_dir: PathBuf::from("crates/gpui-toolkit/stories"),
            token_paths: Vec::new(),
            watch: false,
        }
    }
}
