// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::initial_lab_state::InitialLabState;
use super::misc::button_variant;
use super::misc::design_for_theme_preset;
use super::misc::showcase_section_for_story_id;
use super::misc::surface_colormap;
use super::number::number_prop;
use super::number::number_step;
use super::preview_align::PreviewAlign;
use super::preview_layout_constraints::PreviewLayoutConstraints;
use super::preview_overflow::PreviewOverflow;
use super::preview_sizing::PreviewSizing;
use super::preview_surface::PreviewSurface;
use super::story::story_file_name;
use super::story::text_prop;
use super::types::bar_story_data;
use super::types::line_story_data;
use crate::{
    ComponentStory, StoryDocument, StoryProp, StoryPropValue, ThemePreset,
    UI_KIT_EXPORTED_COMPONENT_STORY_IDS,
};
use gpui_px::{Colormap, ScaleType};
use gpui_ui_kit::ButtonVariant;
use gpui_ui_kit::showcase::ShowcaseSection;
use serde_json::json;

#[test]
fn story_file_names_are_stable() {
    assert_eq!(
        story_file_name("audio-kit.potentiometer"),
        "audio_kit_potentiometer.story.json"
    );
}

#[test]
fn prop_helpers_fall_back_by_type() {
    let story =
        ComponentStory::new("test", "crate", "Title", "Description").props([StoryProp::new(
            "value",
            "Value",
            StoryPropValue::Number(0.25),
        )]);
    assert_eq!(number_prop(&story, "value", 1.0), 0.25);
    assert_eq!(text_prop(&story, "value", "fallback"), "fallback");
    assert_eq!(button_variant("outline"), ButtonVariant::Outline);
}

#[test]
fn theme_presets_resolve_design_languages() {
    let apple = ThemePreset::new("apple-hig", "Apple HIG", "apple_hig", false);
    let unknown = ThemePreset::new("custom", "Custom", "missing", false);

    assert_eq!(
        design_for_theme_preset(&apple).language.as_str(),
        "apple_hig"
    );
    assert_eq!(
        design_for_theme_preset(&unknown).language.as_str(),
        "neutral"
    );
}

#[test]
fn integer_story_props_use_integer_steps() {
    for prop_name in ["bars", "points", "size", "slices", "groups", "selected"] {
        assert_eq!(number_step(prop_name), 1.0);
    }
}

#[test]
fn layout_state_is_serializable() {
    let mut doc = StoryDocument::new(ComponentStory::new(
        "ui-kit.button",
        "gpui-ui-kit",
        "Button",
        "Primary action button",
    ));
    doc.layout = json!({
        "viewport": "mobile",
        "theme": "neutral",
        "motion": "reduced",
        "matrix": true,
        "constraints": {
            "sizing": "fixed",
            "min_width": 420.0,
            "min_height": 260.0,
            "aspect_ratio": 1.4,
            "padding": 16.0
        },
        "builder": {
            "horizontal_align": "start",
            "vertical_align": "stretch",
            "overflow": "scroll",
            "surface": "surface",
            "gap": 12.0,
            "border": false
        }
    });
    let serialized = serde_json::to_string(&doc).unwrap();
    assert!(serialized.contains("\"matrix\":true"));
    assert!(serialized.contains("\"motion\":\"reduced\""));
    assert!(serialized.contains("\"sizing\":\"fixed\""));
    assert!(serialized.contains("\"horizontal_align\":\"start\""));
    assert!(serialized.contains("\"overflow\":\"scroll\""));
}

#[test]
fn layout_constraints_parse_with_clamps() {
    let layout = json!({
        "constraints": {
            "sizing": "fit",
            "min_width": 80.0,
            "min_height": 9000.0,
            "aspect_ratio": 9.0,
            "padding": -8.0
        },
        "builder": {
            "horizontal_align": "end",
            "vertical_align": "stretch",
            "overflow": "scroll",
            "surface": "transparent",
            "gap": 900.0,
            "border": false
        }
    });
    let constraints = PreviewLayoutConstraints::from_layout(&layout);
    assert_eq!(constraints.sizing, PreviewSizing::Fit);
    assert_eq!(constraints.min_width, 160.0);
    assert_eq!(constraints.min_height, 1200.0);
    assert_eq!(constraints.aspect_ratio, 3.0);
    assert_eq!(constraints.padding, 0.0);
    assert_eq!(constraints.horizontal_align, PreviewAlign::End);
    assert_eq!(constraints.vertical_align, PreviewAlign::Stretch);
    assert_eq!(constraints.overflow, PreviewOverflow::Scroll);
    assert_eq!(constraints.surface, PreviewSurface::Transparent);
    assert_eq!(constraints.gap, 80.0);
    assert!(!constraints.border);
}

#[test]
fn initial_state_uses_saved_layout_when_valid() {
    let story = ComponentStory::new("ui-kit.button", "gpui-ui-kit", "Button", "Button");
    let mut doc = StoryDocument::new(story);
    doc.layout = json!({
        "viewport": "tablet",
        "theme": "apple-hig",
        "motion": "reduced",
        "matrix": true,
        "constraints": { "sizing": "fixed", "min_width": 440.0 },
        "builder": { "horizontal_align": "start", "overflow": "visible" }
    });
    let state = InitialLabState::from_document(&doc);
    assert_eq!(state.viewport_id, "tablet");
    assert_eq!(state.theme_id, "apple-hig");
    assert_eq!(state.motion_id, "reduced");
    assert!(state.matrix_mode);
    assert_eq!(state.layout_constraints.sizing, PreviewSizing::Fixed);
    assert_eq!(state.layout_constraints.min_width, 440.0);
    assert_eq!(
        state.layout_constraints.horizontal_align,
        PreviewAlign::Start
    );
    assert_eq!(state.layout_constraints.overflow, PreviewOverflow::Visible);
}

#[test]
fn px_line_story_data_is_chart_safe() {
    let sweep = line_story_data("sweep");
    assert_eq!(sweep.x.len(), sweep.y.len());
    assert!(sweep.x.iter().all(|value| *value > 0.0));
    assert_eq!(sweep.x_scale, ScaleType::Log);
    assert_eq!(
        sweep.comparison_y.as_ref().map(Vec::len),
        Some(sweep.x.len())
    );

    let flat = line_story_data("flat");
    assert_eq!(flat.x.len(), flat.y.len());
    assert!(flat.comparison_y.is_none());
}

#[test]
fn px_bar_story_data_matches_categories() {
    let bars = bar_story_data(7);
    assert_eq!(bars.categories.len(), 7);
    assert_eq!(bars.values.len(), bars.categories.len());
    assert_eq!(bars.comparison_values.len(), bars.categories.len());
}

#[test]
fn showcase_story_ids_map_to_sections() {
    assert_eq!(
        showcase_section_for_story_id("ui-kit.command-palette"),
        Some(ShowcaseSection::CommandPalette)
    );
    assert_eq!(
        showcase_section_for_story_id("ui-kit.accessibility"),
        Some(ShowcaseSection::Accessibility)
    );
    assert_eq!(showcase_section_for_story_id("ui-kit.button"), None);
}

#[test]
fn builtin_renderer_story_ids_have_preview_handlers() {
    let missing = crate::BUILTIN_RENDERER_STORY_IDS
        .iter()
        .copied()
        .filter(|story_id| !builtin_preview_handler_story_id(story_id))
        .collect::<Vec<_>>();

    assert!(
        missing.is_empty(),
        "builtin renderer stories without preview handlers: {missing:?}"
    );
}

fn builtin_preview_handler_story_id(story_id: &str) -> bool {
    matches!(
        story_id,
        "ui-kit.button"
            | "ui-kit.form"
            | "ui-kit.status"
            | "ui-kit.navigation"
            | "ui-kit.feedback"
            | "ui-kit.card"
            | "audio-kit.potentiometer"
            | "audio-kit.vertical-slider"
            | "audio-kit.volume-knob"
            | "audio-kit.meter"
            | "audio-kit.horizontal-meter"
            | "audio-kit.spectrum"
            | "audio-kit.spectrum-axis"
    ) || UI_KIT_EXPORTED_COMPONENT_STORY_IDS.contains(&story_id)
        || showcase_section_for_story_id(story_id).is_some()
        || crate::PX_CHART_STORY_IDS.contains(&story_id)
}

#[test]
fn surface_colormap_names_are_stable() {
    assert_eq!(surface_colormap("plasma"), Colormap::Plasma);
    assert_eq!(surface_colormap("coolwarm"), Colormap::CoolWarm);
    assert_eq!(surface_colormap("missing"), Colormap::Viridis);
}
