//! Shared plugin factory.
//!
//! Creates plugin instances from a type string and JSON parameters.
//! Used by the audio engine and by the A/B Compare plugin's sub-rack builder.

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.


mod consts;
mod create;
mod external;
mod is;
mod misc;
mod parse;
mod sandboxed_plugin_creation_options;
mod types;
mod validate;
#[cfg(test)]
mod tests;

pub use consts::*;
pub use create::*;
pub use is::*;
pub use sandboxed_plugin_creation_options::*;
pub use validate::*;

