// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Format a tick value using the optional custom formatter
pub(super) fn format_tick(value: f64, formatter: &Option<fn(f64) -> String>) -> String {
    match formatter {
        Some(f) => f(value),
        None => {
            // Default formatting: remove trailing zeros
            if value.abs() < 1e-10 {
                "0".to_string()
            } else if value.abs() >= 1000.0 || value.abs() < 0.01 {
                format!("{:.1e}", value)
            } else if value.fract().abs() < 1e-10 {
                format!("{:.0}", value)
            } else {
                format!("{:.1}", value)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::super::*;
    use super::*;

    #[test]
    fn test_format_tick_default() {
        assert_eq!(format_tick(0.0, &None), "0");
        assert_eq!(format_tick(10.0, &None), "10");
        assert_eq!(format_tick(10.5, &None), "10.5");
        assert_eq!(format_tick(1000.5, &None), "1.0e3");
    }

    #[test]
    fn test_format_tick_custom() {
        let formatter = |v: f64| format!("{:.2}Hz", v);
        assert_eq!(format_tick(440.0, &Some(formatter)), "440.00Hz");
    }
}
