// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::collections::HashMap;
pub use autoeq :: roomeq :: { CallbackAction , PipelineControl , PipelineEvent , PipelineObserver , RoomOptimizationCallback , RoomOptimizationProgress } ;
pub use autoeq :: roomeq :: { MeasurementSource , OptimizerConfig , ProcessingMode , RoomConfig , SpeakerConfig } ;

pub(super) fn room_callback_observer(mut callback: RoomOptimizationCallback) -> Box<dyn PipelineObserver> {
    Box::new(move |event: &PipelineEvent| {
        let progress = RoomOptimizationProgress::from(event);
        match callback(&progress) {
            CallbackAction::Continue => PipelineControl::Continue,
            CallbackAction::Stop => PipelineControl::Stop,
        }
    })
}

/// Build a RoomConfig from speaker curves
///
/// Convenience function to create a RoomConfig from in-memory curves.
pub fn build_room_config_from_curves(
    speakers: &[(String, autoeq::Curve)],
    optimizer: OptimizerConfig,
) -> RoomConfig {
    let mut speakers_map: HashMap<String, SpeakerConfig> = HashMap::new();
    for (name, curve) in speakers {
        speakers_map.insert(
            name.clone(),
            SpeakerConfig::Single(MeasurementSource::InMemory(curve.clone())),
        );
    }

    RoomConfig {
        version: autoeq::roomeq::default_config_version(),
        system: None,
        speakers: speakers_map,
        crossovers: None,
        target_curve: None,
        optimizer,
        recording_config: None,
        ctc: None,
        cea2034_cache: None,
    }
}

/// Create default optimizer config from autoeq::Args
pub fn optimizer_config_from_args(args: &autoeq::Args) -> OptimizerConfig {
    let is_bo_algorithm =
        args.algo.eq_ignore_ascii_case("autoeq:bo") || args.algo.eq_ignore_ascii_case("bo");
    OptimizerConfig {
        loss_type: format!("{:?}", args.loss).to_lowercase(),
        algorithm: args.algo.clone(),
        strategy: args.strategy.clone(),
        num_filters: args.num_filters,
        min_q: args.min_q,
        max_q: args.max_q,
        min_db: args.min_db,
        max_db: args.max_db,
        min_freq: args.min_freq,
        max_freq: args.max_freq,
        max_iter: args.maxeval,
        population: args.population,
        peq_model: format!("{:?}", args.peq_model).to_lowercase(),
        processing_mode: ProcessingMode::LowLatency,
        fir: None,
        seed: None,
        mixed_config: None,
        mixed_phase: None,
        phase_correction: None,
        refine: true,
        local_algo: "cobyla".to_string(),
        bo_initial_samples: (is_bo_algorithm && args.bo_initial_samples > 0)
            .then_some(args.bo_initial_samples),
        bo_batch_size: (is_bo_algorithm && args.bo_batch_size > 0).then_some(args.bo_batch_size),
        bo_posterior_std_threshold: (is_bo_algorithm && args.bo_posterior_std_threshold > 0.0)
            .then_some(args.bo_posterior_std_threshold),
        bo_acquisition: (is_bo_algorithm && !args.bo_acquisition.is_empty())
            .then(|| args.bo_acquisition.clone()),
        bo_ehvi: (is_bo_algorithm && args.bo_ehvi).then_some(true),
        psychoacoustic: true,
        psychoacoustic_smoothing: None,
        smooth_n: args.smooth_n,
        asymmetric_loss: true,
        asymmetric_loss_config: None,
        perceptual_policy: None,
        audibility_deadband: None,
        high_frequency_correction: None,
        early_late_correction: None,
        validation_bundle: None,
        tolerance: args.tolerance,
        atolerance: args.atolerance,
        allow_delay: None,
        excursion_protection: None,
        schroeder_split: None,
        phase_alignment: None,
        multi_seat: None,
        vog: None,
        multi_measurement: None,
        decomposed_correction: None,
        target_response: None,
        cea2034_correction: None,
        min_filter_improvement: 0.0,
        elimination_threshold: 0.0,
        sub_config: None,
        channel_matching: None,
        ssir_wav_path: None,
        max_boost_envelope: None,
        min_cut_envelope: None,
        epa_config: None,
        group_delay: None,
        auto_optimizer: None,
        smoothness_penalty: None,
        from_measurement_slope_override: None,
    }
}

