// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::ComponentTheme;
use gpui::Rgba;

/// Theme colors for number input styling
#[derive(Debug, Clone, ComponentTheme)]
pub struct NumberInputTheme {
    /// Background color
    #[theme(default = 0x1e1e1eff, from = background)]
    pub background: Rgba,
    /// Text color
    #[theme(default = 0xffffffff, from = text_primary)]
    pub text: Rgba,
    /// Button background
    #[theme(default = 0x2a2a2aff, from = surface)]
    pub button_bg: Rgba,
    /// Button hover background
    #[theme(default = 0x3a3a3aff, from = surface_hover)]
    pub button_hover: Rgba,
    /// Button active (pressed) background
    #[theme(default = 0x007accff, from = accent)]
    pub button_active: Rgba,
    /// Button text color
    #[theme(default = 0xccccccff, from = text_secondary)]
    pub button_text: Rgba,
    /// Border color
    #[theme(default = 0x3a3a3aff, from = border)]
    pub border: Rgba,
    /// Border focus color
    #[theme(default = 0x007accff, from = accent)]
    pub border_focus: Rgba,
    /// Label color
    #[theme(default = 0xaaaaaaff, from = text_secondary)]
    pub label: Rgba,
    /// Disabled opacity
    #[theme(default_f32 = 0.5, from_expr = "0.5")]
    pub disabled_opacity: f32,
}
