// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use serde::{Deserialize, Serialize};
use super::channel_loudness_params::ChannelLoudnessParams;
use super::default::default_auto_gain_position;
use super::default::default_high_freq;
use super::default::default_high_gain;
use super::default::default_low_freq;
use super::default::default_low_gain;
use super::default::default_mid_enabled;
use super::default::default_mid_freq;
use super::default::default_mid_gain;
use super::default::default_mid_q;
use super::default::default_playback_level_db;
use super::default::default_reference_level_db;
use super::loudness_compensation_plugin::LoudnessCompensationPlugin;

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LoudnessCompensationPluginParams {
    #[serde(default = "default_low_freq")]
    pub low_freq: f32,
    #[serde(default = "default_low_gain")]
    pub low_gain: f32,
    #[serde(default = "default_high_freq")]
    pub high_freq: f32,
    #[serde(default = "default_high_gain")]
    pub high_gain: f32,
    #[serde(default = "default_mid_enabled")]
    pub mid_enabled: bool,
    #[serde(default = "default_mid_freq")]
    pub mid_freq: f32,
    #[serde(default = "default_mid_gain")]
    pub mid_gain: f32,
    #[serde(default = "default_mid_q")]
    pub mid_q: f32,
    #[serde(default)]
    pub channel_params: Vec<ChannelLoudnessParams>,
    #[serde(default)]
    pub auto_gain_enabled: bool,
    #[serde(default)]
    pub auto_gain_max_db: f32,
    #[serde(default)]
    pub auto_gain_smoothing_ms: f32,
    /// Auto-gain position: "pre", "post" (default), or "disabled"
    #[serde(default = "default_auto_gain_position")]
    pub auto_gain_position: String,
    /// 0 = Manual (default), 1 = ISO 226, 2 = Auto
    #[serde(default)]
    pub mode: usize,
    #[serde(default = "default_playback_level_db")]
    pub playback_level_db: f32,
    #[serde(default = "default_reference_level_db")]
    pub reference_level_db: f32,
    /// Engine playback volume in dB (used in Auto mode)
    #[serde(default)]
    pub playback_volume_db: f32,
}

/// Type alias for backward compatibility.
pub type FletcherMunsonPlugin = LoudnessCompensationPlugin;

/// Type alias for backward compatibility.
pub type FletcherMunsonPluginParams = LoudnessCompensationPluginParams;

