[build.env]
passthrough = [
    "BROWSER_PATH",
    "WEBDRIVER_PATH",
]

[target.x86_64-unknown-linux-gnu]
dockerfile = "./from_macos_arm/Dockerfile.x86_64-unknown-linux-gnu"
# Force use of Docker
pre-build = []

[target.aarch64-unknown-linux-gnu]
dockerfile = "./from_macos_arm/Dockerfile.aarch64-unknown-linux-gnu"
pre-build = []

# Static musl targets for Linux
[target.x86_64-unknown-linux-musl]
dockerfile = "./from_macos_arm/Dockerfile.x86_64-unknown-linux-musl"
pre-build = []

[target.aarch64-unknown-linux-musl]
dockerfile = "./from_macos_arm/Dockerfile.aarch64-unknown-linux-musl"
pre-build = []

[target.x86_64-pc-windows-gnullvm]
dockerfile = "./from_macos_arm/Dockerfile.x86_64-pc-windows-gnullvm"
pre-build = []

[target.aarch64-pc-windows-gnullvm]
dockerfile = "./from_macos_arm/Dockerfile.aarch64-pc-windows-gnullvm"
pre-build = []
