// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::eq;
use super::super::types::{Cea2034CorrectionConfig, Cea2034CorrectionMode, OptimizerConfig};
use super::misc::resolve_correction_mode;
use super::misc::simulate_correction;
use crate::Curve;
use crate::error::{AutoeqError, Result};
use crate::read;
use crate::read::Cea2034Data;
use log::{debug, info};
use math_audio_iir_fir::Biquad;

/// Compute speaker correction filters from CEA2034 data.
///
/// Returns the correction filters and the room measurement curve with the
/// correction applied (the "residual" for Pass 2).
///
/// # Arguments
/// * `cea2034_data` - Pre-fetched CEA2034 data for this speaker
/// * `config` - CEA2034 correction configuration
/// * `room_curve` - Room measurement curve
/// * `schroeder_freq` - Schroeder frequency (correction applies above this)
/// * `arrival_time_ms` - Arrival time from impulse response (for auto distance)
/// * `sample_rate` - Sample rate for filter design
pub fn compute_speaker_correction(
    cea2034_data: &Cea2034Data,
    config: &Cea2034CorrectionConfig,
    room_curve: &Curve,
    schroeder_freq: f64,
    arrival_time_ms: Option<f64>,
    sample_rate: f64,
) -> Result<(Vec<Biquad>, Curve)> {
    let mode = resolve_correction_mode(config, arrival_time_ms);

    match mode {
        Cea2034CorrectionMode::Flat => compute_flat_lw_correction(
            cea2034_data,
            config,
            room_curve,
            schroeder_freq,
            sample_rate,
        ),
        Cea2034CorrectionMode::Score => compute_score_correction(
            cea2034_data,
            config,
            room_curve,
            schroeder_freq,
            sample_rate,
        ),
        Cea2034CorrectionMode::Auto => {
            // Should not reach here — resolved above
            unreachable!("Auto mode should have been resolved")
        }
    }
}

/// Flat Listening Window correction: optimize LW toward flat above Schroeder.
fn compute_flat_lw_correction(
    cea2034_data: &Cea2034Data,
    config: &Cea2034CorrectionConfig,
    room_curve: &Curve,
    schroeder_freq: f64,
    sample_rate: f64,
) -> Result<(Vec<Biquad>, Curve)> {
    if room_curve.freq.is_empty() {
        return Err(AutoeqError::InvalidMeasurement {
            message: "Room curve has no frequency data for CEA2034 correction".to_string(),
        });
    }

    // Interpolate Listening Window to room measurement's frequency grid
    let lw_interpolated =
        read::normalize_and_interpolate_response(&room_curve.freq, &cea2034_data.listening_window);

    info!(
        "  Flat LW correction: {} filters, {:.0}-{:.0} Hz, max_db={:.1}, min_db={:.1}",
        config.num_filters,
        schroeder_freq,
        room_curve.freq[room_curve.freq.len() - 1],
        config.max_db,
        config.min_db
    );

    // Build optimizer config for speaker correction
    let optimizer_config = OptimizerConfig {
        num_filters: config.num_filters,
        min_freq: schroeder_freq,
        max_freq: 20000.0,
        min_q: 0.5,
        max_q: config.max_q,
        min_db: config.min_db,
        max_db: config.max_db,
        loss_type: "flat".to_string(),
        asymmetric_loss: false, // Symmetric for speaker correction
        psychoacoustic: false,  // No room-mode smoothing needed for anechoic data
        refine: true,
        ..OptimizerConfig::default()
    };

    // Optimize the Listening Window curve toward flat
    let (filters, loss) = eq::optimize_channel_eq(
        &lw_interpolated,
        &optimizer_config,
        None, // Flat target (default)
        sample_rate,
    )
    .map_err(|e| AutoeqError::OptimizationFailed {
        message: format!("CEA2034 flat LW correction failed: {}", e),
    })?;

    info!(
        "  CEA2034 flat LW correction: {} filters, final loss={:.4}",
        filters.len(),
        loss
    );
    for f in &filters {
        debug!("    {:.0} Hz, Q={:.2}, {:.1} dB", f.freq, f.q, f.db_gain);
    }

    // Apply correction to the room measurement curve
    let corrected_room = simulate_correction(&filters, room_curve, sample_rate);

    Ok((filters, corrected_room))
}

/// Speaker-score correction is intentionally unsupported in roomeq.
///
/// The CEA2034 score is defined for anechoic spinorama data. Roomeq uses
/// spinorama curves only to build an anechoic speaker pre-correction before
/// room optimization, so silently approximating score mode as flat LW
/// correction would misrepresent the requested objective.
fn compute_score_correction(
    _cea2034_data: &Cea2034Data,
    _config: &Cea2034CorrectionConfig,
    _room_curve: &Curve,
    _schroeder_freq: f64,
    _sample_rate: f64,
) -> Result<(Vec<Biquad>, Curve)> {
    Err(AutoeqError::InvalidConfiguration {
        message: "CEA2034 score correction is not supported in roomeq; the Harman/Olive \
                  preference score is defined for anechoic spinorama data, while roomeq \
                  uses CEA2034 only for flat Listening Window speaker pre-correction"
            .to_string(),
    })
}
