// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::types::{MultiMeasurementStrategy, RoomConfig};
use super::all::all_channel_multiseat_enabled;
use super::all::all_channel_multiseat_policy;
use super::apply::predicted_seat_report;
use super::logical::logical_speaker_configs;
use super::misc::curves_share_frequency_grid;
use super::misc::default_all_channel_spatial_robustness;
use super::misc::measurement_source_count;
use super::misc::optional_max;
use super::misc::single_measurement_source;
use super::misc::spatial_robustness_config_from;
use super::misc::speaker_measurement_count;
use super::resolve::resolve_all_channel_seat_weights;
use super::role::role_for_channel;
use super::role::role_group_key;
pub use super::types::*;
use std::collections::{BTreeMap, HashMap};

pub fn multi_seat_coverage(config: &RoomConfig) -> MultiSeatCoverageReport {
    let mut by_role_group: BTreeMap<String, usize> = BTreeMap::new();
    let mut channels_with_multiple_measurements = 0;
    let mut non_sub_channel_count = 0;
    let mut non_sub_channels_with_multiple_measurements = 0;
    let mut max_seat_count = 0;

    for (channel, speaker) in logical_speaker_configs(config) {
        let role = role_for_channel(&channel);
        let is_non_sub = !role.is_sub_or_lfe();
        if is_non_sub {
            non_sub_channel_count += 1;
        }
        let Some(seat_count) = speaker_measurement_count(&speaker) else {
            continue;
        };
        if seat_count < 2 {
            continue;
        }

        channels_with_multiple_measurements += 1;
        max_seat_count = max_seat_count.max(seat_count);
        if is_non_sub {
            non_sub_channels_with_multiple_measurements += 1;
        }
        *by_role_group
            .entry(role_group_key(role.group()).to_string())
            .or_insert(0) += 1;
    }

    MultiSeatCoverageReport {
        channels_with_multiple_measurements,
        non_sub_channel_count,
        non_sub_channels_with_multiple_measurements,
        max_seat_count,
        by_role_group,
        all_channel_correction_ready: non_sub_channel_count > 0
            && non_sub_channels_with_multiple_measurements == non_sub_channel_count
            && max_seat_count >= 2,
        recommended_scope: multi_seat_recommended_scope(
            channels_with_multiple_measurements,
            non_sub_channel_count,
            non_sub_channels_with_multiple_measurements,
        )
        .to_string(),
        advisories: multi_seat_coverage_advisories(
            channels_with_multiple_measurements,
            non_sub_channel_count,
            non_sub_channels_with_multiple_measurements,
            max_seat_count,
        ),
    }
}

pub fn multi_seat_correction_report(
    config: &RoomConfig,
    channel_results: &HashMap<String, super::super::optimize::ChannelOptimizationResult>,
    rejected_channels: Option<&HashMap<String, Vec<String>>>,
) -> MultiSeatCorrectionReport {
    let policy = all_channel_multiseat_policy(config);
    let enabled = all_channel_multiseat_enabled(config);
    let mut channels = Vec::new();
    let mut max_seat_count = 0usize;
    let mut report_weights = Vec::new();
    let mut advisories = Vec::new();

    for (channel, speaker) in logical_speaker_configs(config) {
        let role = role_for_channel(&channel);
        if role.is_sub_or_lfe() {
            continue;
        }
        let role_group = role.group();
        let target_band_hz = role.default_target_band_hz();
        let source = single_measurement_source(&speaker);
        let seat_count = source.and_then(measurement_source_count).unwrap_or(0);
        max_seat_count = max_seat_count.max(seat_count);
        let (weights, weight_advisories) = resolve_all_channel_seat_weights(&policy, seat_count);
        if report_weights.is_empty() && !weights.is_empty() {
            report_weights = weights.clone();
        }

        let mut channel_advisories = weight_advisories;
        let status: String;
        let mut seats = Vec::new();
        let mut spatial_variance_peak_db = None;
        let mut min_correction_depth = None;

        if !enabled {
            status = "disabled".to_string();
        } else if source.is_none() {
            status = "unsupported_speaker_topology".to_string();
        } else if seat_count < 2 {
            status = "single_seat_only".to_string();
        } else if !channel_advisories.is_empty() {
            status = "invalid_policy_skipped".to_string();
        } else if policy.primary_seat >= seat_count {
            status = "invalid_policy_skipped".to_string();
            channel_advisories.push("primary_seat_out_of_range".to_string());
        } else if let Some(rejection_advisories) =
            rejected_channels.and_then(|rejections| rejections.get(&channel))
        {
            status = "rejected_guardrails".to_string();
            channel_advisories.extend(rejection_advisories.clone());
        } else if let Some(result) = channel_results.get(&channel) {
            match crate::read::load_source_individual(source.unwrap()) {
                Ok(curves) if curves.len() == seat_count => {
                    let same_grid = curves_share_frequency_grid(&curves);
                    if !same_grid {
                        status = "frequency_grid_mismatch_skipped".to_string();
                        channel_advisories
                            .push("frequency_grid_mismatch_all_channel_skipped".to_string());
                    } else {
                        let sr_config = spatial_robustness_config_from(
                            &default_all_channel_spatial_robustness(),
                        );
                        match super::super::spatial_robustness::analyze_spatial_robustness_weighted(
                            &curves,
                            &sr_config,
                            Some(&weights),
                        ) {
                            Ok(analysis) => {
                                spatial_variance_peak_db =
                                    analysis.spatial_variance.iter().cloned().reduce(f64::max);
                                min_correction_depth =
                                    analysis.correction_depth.iter().cloned().reduce(f64::min);

                                seats = curves
                                    .iter()
                                    .enumerate()
                                    .filter_map(|(idx, seat_curve)| {
                                        predicted_seat_report(
                                            idx,
                                            seat_curve,
                                            result,
                                            target_band_hz,
                                            policy.primary_seat,
                                            *weights.get(idx).unwrap_or(&0.0),
                                            policy.max_deviation_db,
                                        )
                                    })
                                    .collect();
                                if seats.len() == seat_count {
                                    let primary_pass = seats
                                        .iter()
                                        .find(|seat| seat.is_primary)
                                        .is_some_and(|seat| seat.pass);
                                    let non_primary_pass = seats
                                        .iter()
                                        .filter(|seat| !seat.is_primary)
                                        .all(|seat| seat.pass);
                                    if primary_pass && non_primary_pass {
                                        status = "applied".to_string();
                                    } else {
                                        status = "failed_constraints".to_string();
                                        if !primary_pass {
                                            channel_advisories
                                                .push("primary_seat_constraint_failed".to_string());
                                        }
                                        if !non_primary_pass {
                                            channel_advisories.push(
                                                "non_primary_seat_constraint_failed".to_string(),
                                            );
                                        }
                                    }
                                } else {
                                    status = "prediction_failed".to_string();
                                }
                            }
                            Err(e) => {
                                status = "spatial_robustness_invalid_skipped".to_string();
                                channel_advisories
                                    .push(format!("spatial_robustness_invalid_skipped: {e}"));
                            }
                        }
                    }
                    if seats.iter().any(|seat| seat.null_risk) {
                        channel_advisories.push("seat_specific_null_not_corrected".to_string());
                    }
                }
                Ok(_) => {
                    status = "seat_count_mismatch".to_string();
                }
                Err(err) => {
                    status = "measurement_load_failed".to_string();
                    channel_advisories.push(err.to_string());
                }
            }
        } else {
            status = "not_optimized".to_string();
        }

        let rms_target_error_db = optional_max(seats.iter().map(|seat| seat.rms_target_error_db));
        let max_abs_deviation_db = optional_max(seats.iter().map(|seat| seat.max_abs_deviation_db));
        let primary_pass = seats
            .iter()
            .find(|seat| seat.is_primary)
            .map(|seat| seat.pass);
        let non_primary: Vec<_> = seats.iter().filter(|seat| !seat.is_primary).collect();
        let non_primary_pass = (!non_primary.is_empty()).then(|| {
            non_primary
                .iter()
                .all(|seat| seat.max_abs_deviation_db <= policy.max_deviation_db)
        });

        channels.push(MultiSeatChannelCorrectionReport {
            channel,
            role,
            role_group,
            status,
            seat_count,
            target_band_hz,
            rms_target_error_db,
            max_abs_deviation_db,
            primary_pass,
            non_primary_pass,
            spatial_variance_peak_db,
            min_correction_depth,
            seats,
            advisories: channel_advisories,
        });
    }

    let applied = channels.iter().any(|channel| channel.status == "applied");
    if !enabled {
        advisories.push("all_channel_multiseat_disabled".to_string());
    }
    if channels.is_empty() {
        advisories.push("no_non_sub_channels".to_string());
    }
    if !applied && enabled {
        advisories.push("no_all_channel_multiseat_correction_applied".to_string());
    }
    if channels.iter().any(|channel| {
        channel
            .advisories
            .iter()
            .any(|a| a == "seat_specific_null_not_corrected")
    }) {
        advisories.push("seat_specific_nulls_were_not_overcorrected".to_string());
    }
    if channels
        .iter()
        .any(|channel| channel.status == "rejected_guardrails")
    {
        advisories.push("all_channel_corrections_rejected_by_guardrails".to_string());
    }
    if advisories.is_empty() {
        advisories.push("ok".to_string());
    }

    MultiSeatCorrectionReport {
        enabled,
        applied,
        strategy: multi_measurement_strategy_name(
            config
                .optimizer
                .multi_measurement
                .as_ref()
                .map(|mc| &mc.strategy)
                .unwrap_or(&policy.all_channel_strategy),
        )
        .to_string(),
        seat_count: max_seat_count,
        primary_seat: policy.primary_seat,
        seat_weights: report_weights,
        role_groups: multi_seat_role_group_reports(&channels),
        channels,
        advisories,
    }
}

fn multi_seat_recommended_scope(
    channels_with_multiple_measurements: usize,
    non_sub_channel_count: usize,
    non_sub_channels_with_multiple_measurements: usize,
) -> &'static str {
    if non_sub_channel_count > 0
        && non_sub_channels_with_multiple_measurements == non_sub_channel_count
    {
        "all_channel_reporting_ready"
    } else if non_sub_channels_with_multiple_measurements > 0 {
        "partial_non_sub_reporting_only"
    } else if channels_with_multiple_measurements > 0 {
        "sub_or_partial_only"
    } else {
        "single_seat_only"
    }
}

fn multi_seat_coverage_advisories(
    channels_with_multiple_measurements: usize,
    non_sub_channel_count: usize,
    non_sub_channels_with_multiple_measurements: usize,
    max_seat_count: usize,
) -> Vec<String> {
    let mut advisories = Vec::new();
    if channels_with_multiple_measurements == 0 {
        advisories.push("no_multi_seat_measurements".to_string());
    }
    if max_seat_count < 2 {
        advisories.push("insufficient_seats".to_string());
    }
    if non_sub_channels_with_multiple_measurements == 0 && channels_with_multiple_measurements > 0 {
        advisories.push("multi_seat_sub_only".to_string());
    }
    if non_sub_channel_count > 1 && non_sub_channels_with_multiple_measurements == 1 {
        advisories.push("only_one_non_sub_channel_has_multi_seat_data".to_string());
    }
    if non_sub_channel_count > 0
        && non_sub_channels_with_multiple_measurements > 0
        && non_sub_channels_with_multiple_measurements < non_sub_channel_count
    {
        advisories.push("partial_non_sub_multi_seat_coverage".to_string());
    }
    if advisories.is_empty() {
        advisories.push("all_channel_multi_seat_reporting_ready".to_string());
    }
    advisories
}

fn multi_seat_role_group_reports(
    channels: &[MultiSeatChannelCorrectionReport],
) -> Vec<MultiSeatRoleGroupCorrectionReport> {
    let mut groups: BTreeMap<HomeCinemaRoleGroup, Vec<&MultiSeatChannelCorrectionReport>> =
        BTreeMap::new();
    for channel in channels {
        groups.entry(channel.role_group).or_default().push(channel);
    }
    groups
        .into_iter()
        .map(|(role_group, channels)| {
            let applied: Vec<_> = channels
                .iter()
                .copied()
                .filter(|channel| channel.status == "applied")
                .collect();
            let pass = !applied.is_empty()
                && applied.iter().all(|channel| {
                    channel.primary_pass.unwrap_or(false)
                        && channel.non_primary_pass.unwrap_or(true)
                });
            let mut advisories = Vec::new();
            if applied.is_empty() {
                advisories.push("no_applied_channels".to_string());
            }
            if !pass && !applied.is_empty() {
                advisories.push("seat_constraint_failed".to_string());
            }
            if advisories.is_empty() {
                advisories.push("ok".to_string());
            }
            MultiSeatRoleGroupCorrectionReport {
                role_group,
                channel_count: channels.len(),
                applied_channel_count: applied.len(),
                pass,
                worst_rms_target_error_db: optional_max(
                    applied.iter().filter_map(|c| c.rms_target_error_db),
                ),
                worst_max_abs_deviation_db: optional_max(
                    applied.iter().filter_map(|c| c.max_abs_deviation_db),
                ),
                advisories,
            }
        })
        .collect()
}

fn multi_measurement_strategy_name(strategy: &MultiMeasurementStrategy) -> &'static str {
    match strategy {
        MultiMeasurementStrategy::Average => "average",
        MultiMeasurementStrategy::WeightedSum => "weighted_sum",
        MultiMeasurementStrategy::Minimax => "minimax",
        MultiMeasurementStrategy::VariancePenalized => "variance_penalized",
        MultiMeasurementStrategy::SpatialRobustness => "spatial_robustness",
        MultiMeasurementStrategy::MinimaxUncertainty => "minimax_uncertainty",
    }
}
