// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::gd_opt_config::GdOptConfig;
use super::super::optimize::optimize_group_delay;
use super::super::types::ChannelMeasurementInput;
use math_audio_iir_fir::{Biquad, BiquadFilterType};
use ndarray::Array1;
use std::f64::consts::PI;

/// Create a synthetic channel measurement with a known pure delay.
/// The channel has flat magnitude (0 dB) and linear phase corresponding
/// to the given delay.
pub(super) fn make_delayed_channel(
    freq_grid: &Array1<f64>,
    delay_ms: f64,
    coherence: f64,
) -> ChannelMeasurementInput {
    let n = freq_grid.len();
    let spl = Array1::zeros(n); // 0 dB flat
    let delay_s = delay_ms * 1e-3;

    // Phase = -ω * delay (linear phase from pure delay)
    let phase = freq_grid.mapv(|f| -2.0 * PI * f * delay_s);

    let coherence = Array1::from_elem(n, coherence);

    ChannelMeasurementInput {
        freq: freq_grid.clone(),
        spl,
        phase,
        coherence,
    }
}

#[test]
fn test_frequency_grid_values_must_match() {
    let freq0 = Array1::from(vec![20.0, 40.0, 80.0, 160.0]);
    let freq1 = Array1::from(vec![20.0, 41.0, 80.0, 160.0]);
    let ch0 = make_delayed_channel(&freq0, 0.0, 0.95);
    let ch1 = make_delayed_channel(&freq1, 1.0, 0.95);

    let result = optimize_group_delay(
        &[ch0, ch1],
        (20.0, 160.0),
        &GdOptConfig {
            ap_per_channel: 0,
            optimize_polarity: false,
            max_iter: 10,
            popsize: 4,
            seed: Some(1),
            ..Default::default()
        },
    );

    assert!(result.is_err());
    assert!(result.unwrap_err().contains("frequency grid"));
}

/// Create a channel with pure linear-phase delay plus the phase contribution
/// of an allpass biquad. Magnitude stays flat (0 dB).
pub(super) fn make_delayed_channel_with_allpass(
    freq_grid: &Array1<f64>,
    delay_ms: f64,
    ap_freq: f64,
    ap_q: f64,
    sample_rate: f64,
    coherence: f64,
) -> ChannelMeasurementInput {
    let n = freq_grid.len();
    let spl = Array1::zeros(n); // 0 dB flat
    let delay_s = delay_ms * 1e-3;

    let ap = Biquad::new(BiquadFilterType::AllPass, ap_freq, sample_rate, ap_q, 0.0);

    // Phase = linear delay phase + allpass phase
    let phase = freq_grid.mapv(|f| {
        let linear_phase = -2.0 * PI * f * delay_s;
        let ap_phase = ap.complex_response(f).arg();
        linear_phase + ap_phase
    });

    let coherence = Array1::from_elem(n, coherence);

    ChannelMeasurementInput {
        freq: freq_grid.clone(),
        spl,
        phase,
        coherence,
    }
}
