// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub(super) fn channel_weight(ch: usize, num_channels: usize) -> f64 {
    if num_channels <= 2 {
        // Mono or stereo: all channels weight 1.0
        1.0
    } else if num_channels == 5 {
        // 5.0: L, R, C, Ls, Rs
        match ch {
            0..=2 => 1.0,  // L, R, C
            3 | 4 => 1.41, // Ls, Rs (surround +1.5 dB)
            _ => 0.0,
        }
    } else if num_channels == 6 {
        // 5.1: L, R, C, LFE, Ls, Rs
        match ch {
            0..=2 => 1.0,  // L, R, C
            3 => 0.0,      // LFE excluded
            4 | 5 => 1.41, // Ls, Rs
            _ => 0.0,
        }
    } else {
        1.0
    }
}

/// Convert energy to loudness in LUFS: -0.691 + 10 × log10(energy).
pub fn energy_to_loudness(energy: f64) -> f64 {
    -0.691 + 10.0 * energy.log10()
}

/// Convert loudness in LUFS to energy.
pub(super) fn loudness_to_energy(lufs: f64) -> f64 {
    10.0_f64.powf((lufs + 0.691) / 10.0)
}
