// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::take;
use gpui::{AppCell, RequestFrameOptions};
use objc::{
    class, msg_send,
    runtime::{BOOL, Object},
    sel, sel_impl,
};
use std::ffi::c_void;
use std::panic::{self, AssertUnwindSafe};
use std::rc::Rc;
use std::sync::atomic::Ordering;

#[link(name = "Metal", kind = "framework")]
unsafe extern "C" {
    fn MTLCreateSystemDefaultDevice() -> *mut c_void;
}

#[inline(never)]
pub(super) fn request_frame_for_window(window: &super::super::window::IosWindow) {
    window.pump_momentum();
    let text_dirty = crate::TEXT_INPUT_DIRTY.swap(false, Ordering::AcqRel);
    let callback = window.request_frame_callback.borrow_mut().take();
    if let Some(mut cb) = callback {
        let result = panic::catch_unwind(AssertUnwindSafe(|| {
            cb(RequestFrameOptions {
                force_render: text_dirty,
                ..Default::default()
            });
        }));
        let mut slot = window.request_frame_callback.borrow_mut();
        if slot.is_none() {
            *slot = Some(cb);
        }
        drop(slot);
        if let Err(payload) = result {
            panic::resume_unwind(payload);
        }
    }
}

pub(super) fn begin_platform_metal_capture() -> bool {
    unsafe {
        // SAFETY: Metal capture APIs are process-global developer tooling
        // hooks. We create the default device and ask MTLCaptureManager to
        // capture all queues for that device until `stopCapture`.
        let device = MTLCreateSystemDefaultDevice() as *mut Object;
        if device.is_null() {
            return false;
        }

        let manager: *mut Object = msg_send![class!(MTLCaptureManager), sharedCaptureManager];
        if manager.is_null() {
            let _: () = msg_send![device, release];
            return false;
        }

        let is_capturing: BOOL = msg_send![manager, isCapturing];
        if is_capturing {
            let _: () = msg_send![device, release];
            return false;
        }

        let descriptor: *mut Object = msg_send![class!(MTLCaptureDescriptor), alloc];
        let descriptor: *mut Object = msg_send![descriptor, init];
        if descriptor.is_null() {
            let _: () = msg_send![device, release];
            return false;
        }

        let _: () = msg_send![descriptor, setCaptureObject: device];
        let _: () = msg_send![descriptor, setDestination: 1_isize];
        let started: BOOL = msg_send![
            manager,
            startCaptureWithDescriptor: descriptor
            error: std::ptr::null_mut::<*mut Object>()
        ];
        let _: () = msg_send![descriptor, release];
        let _: () = msg_send![device, release];
        started
    }
}

pub(super) fn end_platform_metal_capture() {
    unsafe {
        // SAFETY: `sharedCaptureManager` returns the process-wide manager; if a
        // capture is active, `stopCapture` is the documented balanced teardown
        // for captures started from code or Xcode.
        let manager: *mut Object = msg_send![class!(MTLCaptureManager), sharedCaptureManager];
        if manager.is_null() {
            return;
        }
        let is_capturing: BOOL = msg_send![manager, isCapturing];
        if is_capturing {
            let _: () = msg_send![manager, stopCapture];
        }
    }
}

pub(super) fn panic_payload_message(payload: &(dyn std::any::Any + Send)) -> &str {
    if let Some(message) = payload.downcast_ref::<&str>() {
        message
    } else if let Some(message) = payload.downcast_ref::<String>() {
        message.as_str()
    } else {
        "<non-string panic payload>"
    }
}

pub(super) fn retain_application_for_process_lifetime(app: &gpui::Application) {
    // SAFETY: `gpui::Application` is a private single-field tuple struct
    // containing `Rc<AppCell>` in the pinned GPUI revision. iOS does not let
    // `Platform::run` block forever like desktop platforms do, so `run_app`
    // would otherwise drop the application after the launch callback returns.
    // Clone the hidden Rc and intentionally leak it so GPUI's AppCell, windows,
    // and frame callbacks live for the process lifetime.
    debug_assert_eq!(
        std::mem::size_of::<gpui::Application>(),
        std::mem::size_of::<Rc<AppCell>>(),
        "Application layout changed -- iOS AppCell clone assumption broken"
    );
    let retained: Rc<AppCell> = unsafe {
        let app_cell: &Rc<AppCell> = std::mem::transmute(app);
        Rc::clone(app_cell)
    };
    std::mem::forget(retained);
    log::info!("GPUI iOS: Retained application for process lifetime");
}
