// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::misc::is_subwoofer_channel;
use super::super::room_optimization_result::RoomOptimizationResult;
use super::super::types::ChannelOptimizationResult;
use super::super::*;
use super::misc::apply_channel_matching_correction;
use super::misc::final_score_band_for_channel;
use super::misc::recompute_curve_flatness_score;
use super::role::role_aware_channel_matching_groups_with_keys;
use super::types::RoleChannelMatchingProfile;

pub(in super::super) fn channel_matching_role_key(channel_name: &str) -> Option<&'static str> {
    crate::roomeq::home_cinema::matching_group_key(channel_name)
}

pub(in super::super) fn channel_matching_profile_for_role_key(
    role_key: &str,
    base_threshold_db: f64,
) -> RoleChannelMatchingProfile {
    let base_threshold_db = base_threshold_db.max(0.05);
    let (threshold_factor, correction_weight, min_freq_hz, max_freq_hz) = match role_key {
        "front_lr" => (2.0 / 3.0, 1.0, 80.0, 16_000.0),
        "side_surrounds" | "rear_surrounds" | "wides" => (1.0, 0.85, 100.0, 12_000.0),
        "top_front" | "top_middle" | "top_rear" => (4.0 / 3.0, 0.65, 120.0, 10_000.0),
        _ => (1.0, 0.8, 200.0, 10_000.0),
    };
    let rms_threshold_db = base_threshold_db * threshold_factor;

    RoleChannelMatchingProfile {
        rms_threshold_db,
        correction: crate::roomeq::spectral_align::ChannelMatchingCorrectionProfile {
            peak_tolerance_db: rms_threshold_db,
            correction_weight,
            min_freq_hz,
            max_freq_hz,
        },
    }
}

pub(in super::super) fn channel_matching_band_rms_db(
    icd: &crate::roomeq::types::InterChannelDeviation,
    band: (f64, f64),
) -> f64 {
    let mut sum_sq = 0.0;
    let mut count = 0usize;
    for (freq, spread) in &icd.deviation_per_freq {
        if *freq >= band.0 && *freq <= band.1 {
            sum_sq += spread * spread;
            count += 1;
        }
    }

    if count > 0 {
        (sum_sq / count as f64).sqrt()
    } else {
        icd.midrange_rms_db
    }
}

pub(in super::super) fn channel_matching_worsens_reported_scores(
    result: &RoomOptimizationResult,
    config: &RoomConfig,
    baseline: &HashMap<String, ChannelOptimizationResult>,
) -> Option<(String, f64, f64)> {
    result.channel_results.iter().find_map(|(name, ch)| {
        let before = baseline.get(name)?.post_score;
        let (score_min, score_max) = final_score_band_for_channel(config, name);
        let after = recompute_curve_flatness_score(&ch.final_curve, score_min, score_max);
        if after > before + 1e-6 {
            Some((name.clone(), before, after))
        } else {
            None
        }
    })
}

/// Compute inter-channel deviation and optionally apply correction filters.
///
/// Called after per-channel optimization on any result with >1 channel.
/// If `channel_matching` config is enabled and ICD exceeds threshold, adds
/// targeted PEQ filters to bring channels closer together.
pub(in super::super) fn compute_and_correct_icd(
    result: &mut RoomOptimizationResult,
    config: &RoomConfig,
    sample_rate: f64,
) {
    let final_curves: HashMap<String, crate::Curve> = result
        .channel_results
        .iter()
        .filter(|(name, _)| !is_subwoofer_channel(config, name))
        .map(|(name, ch)| (name.clone(), ch.final_curve.clone()))
        .collect();
    if final_curves.len() <= 1 {
        result.metadata.inter_channel_deviation = None;
        return;
    }

    let f3 = final_curves
        .values()
        .filter_map(|c| {
            crate::roomeq::excursion::detect_f3(c, None)
                .ok()
                .map(|r| r.f3_hz)
        })
        .reduce(f64::min)
        .unwrap_or(50.0);

    let icd = crate::roomeq::spectral_align::compute_inter_channel_deviation(&final_curves, f3);
    info!(
        "Inter-channel deviation: midrange_rms={:.2}dB, peak={:.1}dB @{:.0}Hz, passband_rms={:.2}dB",
        icd.midrange_rms_db, icd.midrange_peak_db, icd.midrange_peak_freq, icd.passband_rms_db,
    );

    // Check if correction is enabled and needed.
    // When the user omits `channel_matching`, fall back to `ChannelMatchingConfig::default()`
    // so the two paths (None vs Some(default)) produce identical behaviour.
    let matching_cfg = config
        .optimizer
        .channel_matching
        .clone()
        .unwrap_or_default();
    let enabled = matching_cfg.enabled;
    let threshold = matching_cfg.threshold_db;
    let max_filters = matching_cfg.max_filters;

    if enabled {
        let matching_groups = role_aware_channel_matching_groups_with_keys(&final_curves);
        let mut applied_any = false;
        let baseline_channel_results = result.channel_results.clone();
        let baseline_channels = result.channels.clone();

        if matching_groups.is_empty() {
            info!("No role-compatible channel matching groups found; skipping ICD correction");
        }

        for group in matching_groups {
            let mut group_names: Vec<_> = group.curves.keys().cloned().collect();
            group_names.sort();
            let profile = channel_matching_profile_for_role_key(group.role_key, threshold);
            let matching_band = profile.correction.matching_band(f3);

            let group_icd =
                crate::roomeq::spectral_align::compute_inter_channel_deviation(&group.curves, f3);
            let group_rms_db = channel_matching_band_rms_db(&group_icd, matching_band);
            if group_rms_db <= profile.rms_threshold_db {
                info!(
                    "ICD group [{}] role={} rms={:.2}dB over {:.0}-{:.0}Hz <= threshold={:.2}dB - no correction needed",
                    group_names.join(", "),
                    group.role_key,
                    group_rms_db,
                    matching_band.0,
                    matching_band.1,
                    profile.rms_threshold_db,
                );
                continue;
            }

            info!(
                "ICD group [{}] role={} rms={:.2}dB over {:.0}-{:.0}Hz > threshold={:.2}dB - applying role-aware channel matching (tolerance {:.2}dB, weight {:.2}, max {} filters/ch)",
                group_names.join(", "),
                group.role_key,
                group_rms_db,
                matching_band.0,
                matching_band.1,
                profile.rms_threshold_db,
                profile.correction.peak_tolerance_db,
                profile.correction.correction_weight,
                max_filters,
            );

            let corrections =
                crate::roomeq::spectral_align::correct_inter_channel_deviation_with_profile(
                    &group.curves,
                    f3,
                    max_filters,
                    sample_rate,
                    profile.correction,
                );

            for correction in &corrections {
                if correction.plugin.is_some() {
                    apply_channel_matching_correction(result, correction, sample_rate);
                    applied_any = true;
                }
            }
        }

        if !applied_any {
            result.metadata.inter_channel_deviation = Some(icd);
            return;
        }

        if let Some((channel_name, before, after)) =
            channel_matching_worsens_reported_scores(result, config, &baseline_channel_results)
        {
            info!(
                "ICD correction discarded: channel '{}' score would regress from {:.4} to {:.4}",
                channel_name, before, after
            );
            result.channel_results = baseline_channel_results;
            result.channels = baseline_channels;
            result.metadata.inter_channel_deviation = Some(icd);
            return;
        }

        // Re-compute global ICD after role-aware correction.
        let corrected_curves: HashMap<String, crate::Curve> = result
            .channel_results
            .iter()
            .filter(|(name, _)| !is_subwoofer_channel(config, name))
            .map(|(name, ch)| (name.clone(), ch.final_curve.clone()))
            .collect();
        let icd_after =
            crate::roomeq::spectral_align::compute_inter_channel_deviation(&corrected_curves, f3);
        info!(
            "ICD after correction: midrange_rms={:.2}dB (was {:.2}dB), peak={:.1}dB @{:.0}Hz",
            icd_after.midrange_rms_db,
            icd.midrange_rms_db,
            icd_after.midrange_peak_db,
            icd_after.midrange_peak_freq,
        );
        result.metadata.inter_channel_deviation = Some(icd_after);
    } else {
        result.metadata.inter_channel_deviation = Some(icd);
    }
}
