// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::collections::HashMap;
use super::dtype::DType;

/// Byte order of a numeric type, parsed from the datatype message's bit field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub(super) enum ByteOrder {
    #[default]
    Little,
    Big,
}

#[derive(Debug, Clone, PartialEq)]
pub enum AttrValue {
    String(String),
    Float32(f32),
    Float64(f64),
    Int32(i32),
    Float32Array(Vec<f32>),
    Float64Array(Vec<f64>),
    Int32Array(Vec<i32>),
    Uint8Array(Vec<u8>),
}

#[derive(Debug, Clone)]
pub(super) enum Layout {
    Compact {
        data: Vec<u8>,
    },
    Contiguous {
        address: u64,
        size: u64,
    },
    Chunked {
        address: u64,
        chunk_dims: Vec<u32>,
        filters: Vec<Filter>,
    },
}

#[derive(Debug, Clone)]
pub(super) struct Filter {
    pub(super) id: u16,
    pub(super) _flags: u16,
    pub(super) client_data: Vec<u32>,
}

#[derive(Debug)]
pub(super) struct DatasetInfo {
    pub(super) dims: Vec<u64>,
    pub(super) dtype: DType,
    pub(super) layout: Layout,
    pub(super) attributes: HashMap<String, AttrValue>,
    pub(super) byte_order: ByteOrder,
    pub(super) is_null_dataspace: bool,
    pub(super) fill_value: Option<Vec<u8>>,
}

#[derive(Debug)]
pub(super) struct GroupInfo {
    pub(super) children: HashMap<String, u64>,
    pub(super) attributes: HashMap<String, AttrValue>,
}

#[derive(Debug)]
pub(super) struct FractalHeapInfo {
    pub(super) heap_id_length: u16,
    pub(super) max_heap_size: u16,
    pub(super) starting_block_size: u64,
    pub(super) max_direct_block_size: u64,
    pub(super) table_width: u16,
    pub(super) root_block_address: u64,
    pub(super) current_rows: u16,
    #[allow(dead_code)]
    pub(super) num_managed_objects: u64,
    #[allow(dead_code)]
    pub(super) address: u64,
    pub(super) io_filter_encoded_length: u16,
}

#[derive(Debug)]
pub(super) struct HeapRecord {
    pub(super) heap_id: Vec<u8>,
}

