#!/bin/bash
#
# Local release build orchestrator for SotF
#
# Builds all platform binaries from a Mac:
#   - macOS ARM64 + x86_64: built and signed locally
#   - Linux x86_64 + ARM64: built on a remote Linux x86 machine via SSH
#   - Windows x86_64: built on a remote Windows machine via SSH
#
# After builds: cosign non-Apple artifacts, generate checksums, update site,
# and prep GitHub release.
#
# Usage:
#   ./build-release-local.sh                     # Full release build
#   ./build-release-local.sh --dry-run           # Show what would be done
#   ./build-release-local.sh --skip-linux        # Skip Linux builds
#   ./build-release-local.sh --skip-windows      # Skip Windows builds
#   ./build-release-local.sh --skip-macos        # Skip macOS builds
#   ./build-release-local.sh --skip-sign         # Skip all signing
#   ./build-release-local.sh --skip-site         # Skip site/docs update
#   ./build-release-local.sh --deploy-site        # Also push site + binaries to the VPS via update_prod.sh
#   ./build-release-local.sh --post-only         # Only post-build steps (sign, checksums, site)
#   ./build-release-local.sh --clean-remote      # Wipe target/, dist/, etc. on remote builders before building
#   ./build-release-local.sh --config <file>     # Use alternate config file
#
# Configuration:
#   Create ~/.sotf-release.conf with SSH and signing details (see --init-config).
#   ./build-release-local.sh --init-config       # Generate a template config file
#
# Prerequisites:
#   - macOS with Xcode Command Line Tools
#   - Rust toolchain with x86_64-apple-darwin target
#   - SSH access to Linux and Windows build machines
#   - cosign (brew install cosign)
#   - For macOS signing: DEVELOPER_ID, APPLE_ID in config
#   - For Windows signing: WINDOWS_CERT_FILE, WINDOWS_CERT_PASSWORD in config
#

set -uo pipefail
# NOTE: we do NOT use set -e (errexit). Remote operations are wrapped in
# explicit error handling so the user sees which step failed instead of a
# silent exit.

trap 'log_error "Unexpected error at line $LINENO (exit $?)"' ERR

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="$PROJECT_ROOT/dist"
CONFIG_FILE="${HOME}/.sotf-release.conf"

# Extract version from root Cargo.toml
VERSION=$(grep -m1 '^version = ' "$PROJECT_ROOT/Cargo.toml" | sed 's/version = "\(.*\)"/\1/')
if [ -z "$VERSION" ]; then
    echo "ERROR: Could not extract version from Cargo.toml"
    exit 1
fi

GITHUB_RELEASE_URL="https://github.com/pierreaubert/sotf/releases/download/v${VERSION}"

# Options
DRY_RUN=false
SKIP_LINUX=false
SKIP_WINDOWS=false
SKIP_MACOS=false
SKIP_SIGN=false
SKIP_SITE=false
DEPLOY_SITE=false
POST_ONLY=false
CLEAN_REMOTE=false
INIT_CONFIG=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)       DRY_RUN=true; shift ;;
        --skip-linux)    SKIP_LINUX=true; shift ;;
        --skip-windows)  SKIP_WINDOWS=true; shift ;;
        --skip-macos)    SKIP_MACOS=true; shift ;;
        --skip-sign)     SKIP_SIGN=true; shift ;;
        --skip-site)     SKIP_SITE=true; shift ;;
        --deploy-site)   DEPLOY_SITE=true; shift ;;
        --post-only)     POST_ONLY=true; shift ;;
        --clean-remote)  CLEAN_REMOTE=true; shift ;;
        --init-config)   INIT_CONFIG=true; shift ;;
        --config)        CONFIG_FILE="$2"; shift 2 ;;
        --help|-h)
            sed -n '2,/^$/p' "$0" | sed 's/^#//' | sed 's/^ //'
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# -----------------------------------------------------------------------
# COLOR OUTPUT
# -----------------------------------------------------------------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_phase()   { echo -e "\n${BOLD}${CYAN}════════════════════════════════════════${NC}"; echo -e "${BOLD}${CYAN}  $1${NC}"; echo -e "${BOLD}${CYAN}════════════════════════════════════════${NC}\n"; }
log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()    { echo -e "${BOLD}→${NC} $1"; }
log_dry()     { echo -e "${YELLOW}[DRY-RUN]${NC} Would: $1"; }

# -----------------------------------------------------------------------
# CONFIG TEMPLATE
# -----------------------------------------------------------------------

generate_config_template() {
    cat > "$CONFIG_FILE" << 'CONF'
# SotF Release Build Configuration
# Generated by build-release-local.sh --init-config
#
# SSH connection details for remote build machines.
# The script syncs the repo via rsync, builds remotely, and copies artifacts back.

# --- Linux build machine (x86_64) ---
# Must have: Rust toolchain, Docker (for ARM64 cross builds), just, build-essential,
# and the system deps listed in .github/workflows/release.yml
LINUX_HOST="user@linux-builder.local"
LINUX_PORT="22"
LINUX_PROJECT_DIR="/home/user/src/sotf"
# SSH identity file (optional, uses default SSH config if empty)
LINUX_SSH_KEY=""

# --- Windows build machine (x86_64) ---
# Must have: Rust toolchain, Visual Studio Build Tools or MSVC,
#   Git Bash (C:/Program Files/Git), and rsync installed in Git Bash.
# The script routes all remote commands through Git Bash automatically,
# even though Windows OpenSSH defaults to cmd.exe.
# Use Git Bash / MSYS2 path format for the project directory:
WINDOWS_HOST="user@windows-builder.local"
WINDOWS_PORT="22"
WINDOWS_PROJECT_DIR="/c/Users/user/src/sotf"
WINDOWS_SSH_KEY=""
# Path to bash.exe on the Windows machine (auto-detected if empty)
WINDOWS_BASH_PATH=""

# --- macOS signing ---
# Apple Developer ID certificate name (from Keychain)
# Example: "Developer ID Application: Your Name (TEAMID)"
DEVELOPER_ID=""
# Apple Developer ID Installer certificate (for .pkg files)
INSTALLER_DEVELOPER_ID=""
# Apple ID for notarization
APPLE_ID=""
# Notarization keychain profile name (set up via: xcrun notarytool store-credentials)
NOTARIZATION_PROFILE="autoeq-notarization"

# --- Windows signing ---
# Path to .pfx code signing certificate
WINDOWS_CERT_FILE=""
WINDOWS_CERT_PASSWORD=""
WINDOWS_TIMESTAMP_URL="http://timestamp.digicert.com"
# For native Windows signing with SignTool:
WINDOWS_CERT_THUMBPRINT=""

# --- Cosign (Linux/Windows artifact signing) ---
# Leave empty for keyless OIDC signing (opens browser)
# Set path for key-based signing
COSIGN_KEY=""

# --- Site deployment ---
# rsync target for the website
SITE_DEPLOY_TARGET="spin@vps-c2ea73ea.vps.ovh.net:/var/www/html/spinorama-sotf"
CONF

    echo "Config template written to $CONFIG_FILE"
    echo "Edit it with your SSH hosts and signing credentials."
}

if $INIT_CONFIG; then
    if [ -f "$CONFIG_FILE" ]; then
        echo "Config already exists at $CONFIG_FILE"
        echo "Remove it first if you want a fresh template."
        exit 1
    fi
    generate_config_template
    exit 0
fi

# -----------------------------------------------------------------------
# LOAD CONFIG
# -----------------------------------------------------------------------

if [ ! -f "$CONFIG_FILE" ]; then
    log_error "Config file not found: $CONFIG_FILE"
    log_info "Run: $0 --init-config"
    exit 1
fi

# shellcheck source=/dev/null
source "$CONFIG_FILE"

# -----------------------------------------------------------------------
# HELPERS
# -----------------------------------------------------------------------

# Build the ssh transport string used by both ssh and rsync -e
# Result goes into the SSH_TRANSPORT_CMD variable (array).
build_ssh_transport() {
    local port="$1"
    local key="$2"
    SSH_TRANSPORT_CMD=(ssh)
    [ -n "$port" ] && SSH_TRANSPORT_CMD+=(-p "$port")
    [ -n "$key" ]  && SSH_TRANSPORT_CMD+=(-i "$key")
}

# Run an SSH command with optional key and port
ssh_cmd() {
    local host="$1"
    local port="$2"
    local key="$3"
    shift 3
    build_ssh_transport "$port" "$key"
    "${SSH_TRANSPORT_CMD[@]}" -o BatchMode=yes -o ConnectTimeout=10 "$host" "$@"
}

# Detect the path to bash.exe on the remote Windows machine.
# Sets WIN_BASH_PATH (used by win_ssh_cmd and rsync helpers).
# Called once at the start of the Windows build phase.
detect_win_bash() {
    local host="$1"
    local port="$2"
    local key="$3"

    # Use explicit config if provided
    if [ -n "${WINDOWS_BASH_PATH:-}" ]; then
        WIN_BASH_PATH="$WINDOWS_BASH_PATH"
        return 0
    fi

    # Try common Git Bash locations via raw SSH (cmd.exe shell)
    local candidates=(
        "C:/Program Files/Git/bin/bash.exe"
        "C:/Program Files (x86)/Git/bin/bash.exe"
        "C:/msys64/usr/bin/bash.exe"
    )

    build_ssh_transport "$port" "$key"
    for candidate in "${candidates[@]}"; do
        # cmd.exe can check file existence with 'if exist'
        if "${SSH_TRANSPORT_CMD[@]}" -o BatchMode=yes -o ConnectTimeout=10 "$host" \
            "if exist \"$candidate\" echo FOUND" 2>/dev/null | grep -q FOUND; then
            WIN_BASH_PATH="$candidate"
            log_info "Found bash at: $WIN_BASH_PATH"
            return 0
        fi
    done

    log_error "Could not find bash.exe on remote Windows machine"
    log_info "Tried: ${candidates[*]}"
    log_info "Set WINDOWS_BASH_PATH in your config file to the correct path"
    return 1
}

# Detect the path to rsync.exe on the remote Windows machine.
# Sets WIN_RSYNC_PATH. Called once at the start of the Windows build phase.
detect_win_rsync() {
    local host="$1"
    local port="$2"
    local key="$3"

    # Ask Git Bash for rsync, but do not trust the first PATH hit blindly:
    # Git for Windows can have a stale/broken rsync while MSYS2 has a working
    # one installed at /c/msys64/usr/bin/rsync.
    local rsync_path
    rsync_path=$(win_ssh_cmd "$host" "$port" "$key" '
        candidates=()
        path_rsync=$(command -v rsync 2>/dev/null || true)
        [ -n "$path_rsync" ] && candidates+=("$path_rsync")
        candidates+=(
            "/c/msys64/usr/bin/rsync"
            "/c/msys64/mingw64/bin/rsync"
            "/c/msys64/ucrt64/bin/rsync"
            "/c/cygwin64/bin/rsync"
            "/usr/bin/rsync"
            "/mingw64/bin/rsync"
            "/c/Program Files/Git/usr/bin/rsync"
        )

        seen=":"
        for candidate in "${candidates[@]}"; do
            [ -n "$candidate" ] || continue
            case "$seen" in *:"$candidate":*) continue ;; esac
            seen="${seen}${candidate}:"
            if [ -x "$candidate" ] && "$candidate" --version >/dev/null 2>&1; then
                printf "%s\n" "$candidate"
                exit 0
            fi
        done
        exit 1
    ' 2>/dev/null)
    rsync_path=$(echo "$rsync_path" | tr -d '\r' | tail -n 1)

    if [ -z "$rsync_path" ]; then
        log_error "rsync not found on remote Windows"
        return 1
    fi

    if ! win_ssh_cmd "$host" "$port" "$key" "'$rsync_path' --version >/dev/null 2>&1" >/dev/null 2>&1; then
        local missing_deps
        missing_deps=$(win_ssh_cmd "$host" "$port" "$key" "ldd '$rsync_path' 2>&1 | grep -i 'not found' || true" 2>/dev/null)
        log_error "rsync exists at $rsync_path but cannot run on remote Windows"
        if [ -n "$missing_deps" ]; then
            log_info "Missing rsync runtime dependencies:"
            while IFS= read -r line; do
                [ -n "$line" ] && log_info "  $line"
            done <<< "$missing_deps"
        fi
        return 1
    fi

    # Convert MSYS path (/usr/bin/rsync) to a short Windows path for
    # --rsync-path. The remote SSH shell is cmd.exe, so using 8.3 paths avoids
    # quote-sensitive spaces like "C:\Program Files\...".
    local win_rsync
    win_rsync=$(win_ssh_cmd "$host" "$port" "$key" "cygpath -m -s '$rsync_path' 2>/dev/null || cygpath -m '$rsync_path' 2>/dev/null || echo '$rsync_path'" 2>/dev/null)
    WIN_RSYNC_PATH=$(echo "$win_rsync" | tr -d '\r\n')
    log_info "Found rsync at: $WIN_RSYNC_PATH"
    return 0
}

# Run an SSH command on Windows, routing through Git Bash.
# Windows OpenSSH defaults to cmd.exe which can't run bash scripts or find
# MSYS2 tools (rsync, mkdir -p, etc.). This wraps the command in Git Bash.
# Requires detect_win_bash to have been called first.
WIN_BASH_PATH=""
WIN_RSYNC_PATH=""
win_ssh_cmd() {
    local host="$1"
    local port="$2"
    local key="$3"
    shift 3
    local cmd="$*"
    build_ssh_transport "$port" "$key"
    # Run the Git Bash script over stdin. Passing the command as a remote
    # command-line argument lets cmd.exe reinterpret shell metacharacters like
    # pipes, &&, ||, and redirections before bash sees them.
    printf '%s\n' "$cmd" | "${SSH_TRANSPORT_CMD[@]}" -o BatchMode=yes -o ConnectTimeout=30 "$host" \
        "\"$WIN_BASH_PATH\"" -s
}

# Common rsync excludes — mirrors .gitignore for build/generated dirs.
# Using an array avoids repeating between rsync_to and rsync_to_win.
RSYNC_EXCLUDES=(
    # Build artifacts
    # No trailing slash: these may be symlinks to external build volumes.
    --exclude='/target'
    --exclude='/target-static'
    --exclude='/.docker-target'
    --exclude='/dist'
    --exclude='/tools'
    --exclude='/certs'
    --exclude='/coverage'
    --exclude='/mutants.out'
    --exclude='/appimage-builder-*'
    --exclude='/site/dist'
    # Python
    --exclude='/venv'
    --exclude='/.venv'
    --exclude='__pycache__'
    # Generated data
    --exclude='/data'
    --exclude='/data_cached'
    --exclude='/data_generated'
    # Node
    --exclude='node_modules'
    # Git and editor
    --exclude='.git/'
    --exclude='.DS_Store'
    --exclude='/.vs/'
    --exclude='/.vscode/'
    --exclude='/.zed/'
    --exclude='/.idea/'
    --exclude='/.fleet/'
    --exclude='/.qwen/'
    --exclude='/.worktrees/'
    # AI assistant / code-graph state — large, machine-specific, never needed
    # on remote builders.
    --exclude='/.claude/'
    --exclude='/.tokensave/'
    --exclude='/.serena/'
    # Per-arch Xcode DerivedData for the AU plugins (gigabytes of host-arch
    # binaries, intermediates, and ModuleCache; rebuilt remotely anyway).
    --exclude='/crates/sotf-plugins/crates/plugins-au/build/'
    # Object files
    --exclude='*.o'
    --exclude='*.d'
    # Product/marketing docs
    --exclude='/product/'
)

handle_rsync_status() {
    local status="$1"
    local label="$2"
    local allow_partial="${3:-false}"

    if [ "$status" -eq 0 ]; then
        return 0
    fi

    # Exit 24 means files vanished while rsync was reading the live working
    # tree. That is common for editor/build cache churn and should not abort a
    # release build sync.
    if [ "$status" -eq 24 ]; then
        log_warning "$label completed with vanished source files (rsync exit 24); continuing"
        return 0
    fi

    # Exit 23 is a partial transfer. During the Windows source sync this is
    # usually a non-critical POSIX metadata/symlink mismatch on the receiver;
    # the subsequent cargo build will still fail if a required source file did
    # not arrive.
    if [ "$status" -eq 23 ] && [ "$allow_partial" = true ]; then
        log_warning "$label completed with partial transfer warnings (rsync exit 23); continuing"
        return 0
    fi

    return "$status"
}

rsync_to() {
    local host="$1"
    local port="$2"
    local key="$3"
    local remote_dir="$4"
    build_ssh_transport "$port" "$key"
    rsync -avz --delete \
        "${RSYNC_EXCLUDES[@]}" \
        -e "${SSH_TRANSPORT_CMD[*]}" \
        "$PROJECT_ROOT/" "${host}:${remote_dir}/"
    handle_rsync_status "$?" "rsync to ${host}:${remote_dir}"
}

# rsync to a Windows host — tells the remote side to use the detected rsync.
# detect_win_rsync normalizes this to a short cmd.exe-safe path.
rsync_to_win() {
    local host="$1"
    local port="$2"
    local key="$3"
    local remote_dir="$4"
    build_ssh_transport "$port" "$key"
    rsync -avz --delete \
        --no-perms --no-owner --no-group --omit-dir-times \
        "${RSYNC_EXCLUDES[@]}" \
        -e "${SSH_TRANSPORT_CMD[*]}" \
        --rsync-path="$WIN_RSYNC_PATH" \
        "$PROJECT_ROOT/" "${host}:${remote_dir}/"
    handle_rsync_status "$?" "rsync to ${host}:${remote_dir}" true
}

rsync_from() {
    local host="$1"
    local port="$2"
    local key="$3"
    local remote_path="$4"
    local local_path="$5"
    shift 5
    build_ssh_transport "$port" "$key"
    rsync -avz \
        -e "${SSH_TRANSPORT_CMD[*]}" \
        "$@" \
        "${host}:${remote_path}" "$local_path"
    handle_rsync_status "$?" "rsync from ${host}:${remote_path}"
}

# rsync from a Windows host — tells the remote side to use the detected rsync
rsync_from_win() {
    local host="$1"
    local port="$2"
    local key="$3"
    local remote_path="$4"
    local local_path="$5"
    shift 5
    build_ssh_transport "$port" "$key"
    rsync -avz \
        -e "${SSH_TRANSPORT_CMD[*]}" \
        --rsync-path="$WIN_RSYNC_PATH" \
        "$@" \
        "${host}:${remote_path}" "$local_path"
    handle_rsync_status "$?" "rsync from ${host}:${remote_path}"
}

# Track build results
declare -a BUILD_RESULTS=()
record_result() {
    BUILD_RESULTS+=("$1")
}

# Time a phase
phase_start_time=0
start_timer() { phase_start_time=$(date +%s); }
elapsed() {
    local now
    now=$(date +%s)
    local diff=$((now - phase_start_time))
    printf '%dm%02ds' $((diff / 60)) $((diff % 60))
}

# -----------------------------------------------------------------------
# PHASE 0: PREFLIGHT CHECKS
# -----------------------------------------------------------------------

preflight() {
    log_phase "Phase 0: Preflight Checks"

    log_step "Version: v${VERSION}"
    log_step "Dist dir: ${DIST_DIR}"

    # Sync auxiliary version-pinned files (AppxManifest.xml, site/package.json)
    # to the workspace Cargo.toml version BEFORE any remote rsync, so the
    # Windows builder picks up the correct manifest.
    log_step "Syncing version-pinned files to v${VERSION}..."
    if $DRY_RUN; then
        log_dry "./scripts/sync-version.sh"
    else
        if ! "$SCRIPT_DIR/sync-version.sh"; then
            log_error "Version sync failed"
            exit 1
        fi
    fi

    # Check local tools
    local missing=()
    command -v cargo &>/dev/null || missing+=("cargo")
    command -v just &>/dev/null  || missing+=("just")
    command -v rsync &>/dev/null || missing+=("rsync")

    if ! $SKIP_SIGN; then
        command -v cosign &>/dev/null || missing+=("cosign")
    fi

    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        exit 1
    fi
    log_success "Local tools OK"

    # Check git is clean
    if [ -n "$(git -C "$PROJECT_ROOT" status --porcelain)" ]; then
        log_warning "Working directory has uncommitted changes"
        log_info "Builds will use the current working tree state"
    fi

    # Check SSH connectivity
    if ! $SKIP_LINUX && ! $POST_ONLY; then
        log_step "Testing SSH to Linux: ${LINUX_HOST:-<not configured>}"
        if [ -z "${LINUX_HOST:-}" ]; then
            log_error "LINUX_HOST not configured in $CONFIG_FILE"
            exit 1
        fi
        if $DRY_RUN; then
            log_dry "ssh ${LINUX_HOST} echo ok"
        else
            if ssh_cmd "$LINUX_HOST" "${LINUX_PORT:-22}" "${LINUX_SSH_KEY:-}" "echo ok" &>/dev/null; then
                log_success "Linux SSH OK"
            else
                log_error "Cannot SSH to $LINUX_HOST"
                exit 1
            fi
        fi
    fi

    if ! $SKIP_WINDOWS && ! $POST_ONLY; then
        log_step "Testing SSH to Windows: ${WINDOWS_HOST:-<not configured>}"
        if [ -z "${WINDOWS_HOST:-}" ]; then
            log_error "WINDOWS_HOST not configured in $CONFIG_FILE"
            exit 1
        fi
        if $DRY_RUN; then
            log_dry "ssh ${WINDOWS_HOST} echo ok"
        else
            if ssh_cmd "$WINDOWS_HOST" "${WINDOWS_PORT:-22}" "${WINDOWS_SSH_KEY:-}" "echo ok" &>/dev/null; then
                log_success "Windows SSH OK"
            else
                log_error "Cannot SSH to $WINDOWS_HOST"
                exit 1
            fi
        fi
    fi

    mkdir -p "$DIST_DIR"
    log_success "Preflight complete"
}

# -----------------------------------------------------------------------
# PHASE 1: macOS BUILDS (local)
# -----------------------------------------------------------------------

build_macos() {
    if $SKIP_MACOS; then
        log_info "Skipping macOS builds (--skip-macos)"
        return
    fi

    log_phase "Phase 1: macOS Builds (local)"
    start_timer

    cd "$PROJECT_ROOT"

    # We deliberately do NOT use `just cross-macos-{arm64,x86}` here. Those
    # recipes historically rebuilt the GPUI binary with
    # `RUSTFLAGS="-C target-feature=+crt-static"` into `./target-static/` before
    # wrapping it in a DMG. The static binary cannot be signed/notarized
    # cleanly, so this pipeline builds the dynamically-linked binary first and
    # then asks the DMG script to package that exact binary.

    # --- macOS ARM64 ---
    log_step "Building macOS ARM64 (dynamic) ..."
    if $DRY_RUN; then
        log_dry "cargo build --release --target aarch64-apple-darwin (sotf-tui, sotf-desktop)"
        log_dry "./scripts/build-dmg-sotf.sh --arch arm64 --binary target/aarch64-apple-darwin/release/sotf-desktop"
    else
        rustup target add aarch64-apple-darwin 2>/dev/null || true
        cargo build --release --target aarch64-apple-darwin -p sotf-tui --features hal,onnx
        cargo build --release --target aarch64-apple-darwin -p sotf-gpui --features hal,onnx
        mkdir -p "$DIST_DIR"
        cp "target/aarch64-apple-darwin/release/sotf-tui"     "$DIST_DIR/sotf-tui-${VERSION}-macos-arm64"
        cp "target/aarch64-apple-darwin/release/sotf-desktop" "$DIST_DIR/sotf-desktop-${VERSION}-macos-arm64"
        record_result "macOS ARM64: OK"
        if ./scripts/build-dmg-sotf.sh --arch arm64 --binary "target/aarch64-apple-darwin/release/sotf-desktop"; then
            record_result "macOS ARM64 DMG: OK"
        else
            log_error "macOS ARM64 DMG packaging failed"
            record_result "macOS ARM64 DMG: FAILED"
            exit 1
        fi
    fi

    # --- macOS x86_64 ---
    log_step "Building macOS x86_64 (dynamic) ..."
    if $DRY_RUN; then
        log_dry "cargo build --release --target x86_64-apple-darwin (sotf-tui, sotf-desktop)"
        log_dry "./scripts/build-dmg-sotf.sh --arch x86_64 --binary target/x86_64-apple-darwin/release/sotf-desktop"
    else
        rustup target add x86_64-apple-darwin 2>/dev/null || true
        cargo build --release --target x86_64-apple-darwin -p sotf-tui --features hal
        cargo build --release --target x86_64-apple-darwin -p sotf-gpui --features hal
        mkdir -p "$DIST_DIR"
        cp "target/x86_64-apple-darwin/release/sotf-tui"     "$DIST_DIR/sotf-tui-${VERSION}-macos-x86_64"
        cp "target/x86_64-apple-darwin/release/sotf-desktop" "$DIST_DIR/sotf-desktop-${VERSION}-macos-x86_64"
        record_result "macOS x86_64: OK"
        if ./scripts/build-dmg-sotf.sh --arch x86_64 --binary "target/x86_64-apple-darwin/release/sotf-desktop"; then
            record_result "macOS x86_64 DMG: OK"
        else
            log_error "macOS x86_64 DMG packaging failed"
            record_result "macOS x86_64 DMG: FAILED"
            exit 1
        fi
    fi

    # --- macOS Systemwide pkg ---
    log_step "Building macOS Systemwide pkg..."
    if $DRY_RUN; then
        log_dry "./scripts/build-systemwide.sh"
    else
        ./scripts/build-systemwide.sh
        record_result "macOS Systemwide pkg: OK"
    fi

    # --- Sign macOS artifacts ---
    if ! $SKIP_SIGN && [ -n "${DEVELOPER_ID:-}" ]; then
        log_step "Signing macOS artifacts..."
        if $DRY_RUN; then
            log_dry "./scripts/sign-macos.sh --notarize"
        else
            export DEVELOPER_ID
            export INSTALLER_DEVELOPER_ID="${INSTALLER_DEVELOPER_ID:-}"
            export APPLE_ID="${APPLE_ID:-}"

            ./scripts/sign-macos.sh
            log_success "macOS code signing complete"

            if [ -n "${APPLE_ID:-}" ]; then
                log_step "Notarizing macOS artifacts..."
                ./scripts/sign-macos.sh --notarize
                log_success "macOS notarization complete"
            else
                log_warning "APPLE_ID not set, skipping notarization"
            fi
            record_result "macOS signing: OK"
        fi
    elif ! $SKIP_SIGN; then
        log_warning "DEVELOPER_ID not set, skipping macOS signing"
        record_result "macOS signing: SKIPPED (no DEVELOPER_ID)"
    fi

    log_success "macOS builds complete ($(elapsed))"
}

# -----------------------------------------------------------------------
# PHASE 2: LINUX BUILDS (remote SSH)
# -----------------------------------------------------------------------

build_linux() {
    if $SKIP_LINUX; then
        log_info "Skipping Linux builds (--skip-linux)"
        return
    fi

    log_phase "Phase 2: Linux Builds (remote: ${LINUX_HOST})"
    start_timer

    local host="$LINUX_HOST"
    local port="${LINUX_PORT:-22}"
    local key="${LINUX_SSH_KEY:-}"
    local remote_dir="${LINUX_PROJECT_DIR}"

    # Sync source to Linux machine
    log_step "Syncing source to ${host}:${remote_dir}..."
    if $DRY_RUN; then
        log_dry "rsync project to ${host}:${remote_dir}"
        if $CLEAN_REMOTE; then
            log_dry "ssh ${host} 'rm -rf ${remote_dir}/{target,target-static,node_modules,dist,venv}'"
        fi
    else
        # Ensure remote directory exists
        ssh_cmd "$host" "$port" "$key" "mkdir -p '$remote_dir'"
        if ! rsync_to "$host" "$port" "$key" "$remote_dir"; then
            log_error "rsync to Linux failed"
            record_result "Linux sync: FAILED"
            return
        fi
        if $CLEAN_REMOTE; then
            log_step "Cleaning build artifacts on remote (--clean-remote)..."
            ssh_cmd "$host" "$port" "$key" \
                "rm -rf '$remote_dir/target' '$remote_dir/target-static' '$remote_dir/node_modules' '$remote_dir/dist' '$remote_dir/venv'" \
                || log_warning "Remote cleanup failed (non-fatal)"
        else
            log_info "Reusing remote build artifacts (pass --clean-remote to wipe)"
        fi
        log_success "Source synced"
    fi

    # Build Linux x86_64 natively
    log_step "Building Linux x86_64 (native on remote)..."
    if $DRY_RUN; then
        log_dry "ssh ${host} 'cd ${remote_dir} && ./scripts/build-linux.sh --appimage'"
    else
        if ! ssh_cmd "$host" "$port" "$key" \
            "cd '$remote_dir' && ./scripts/build-linux.sh --appimage"; then
            log_error "Linux x86_64 build failed"
            record_result "Linux x86_64: FAILED"
        else
            record_result "Linux x86_64: OK"
        fi
    fi

    # Build Linux ARM64 via Docker on the remote
    log_step "Building Linux ARM64 (Docker on remote)..."
    if $DRY_RUN; then
        log_dry "ssh ${host} 'cd ${remote_dir} && just docker-linux-arm64'"
    else
        if ssh_cmd "$host" "$port" "$key" \
            "cd '$remote_dir' && just docker-linux-arm64"; then
            record_result "Linux ARM64: OK"
        else
            log_warning "Linux ARM64 build failed (continuing)"
            record_result "Linux ARM64: FAILED"
        fi
    fi

    # Copy artifacts back (current version only)
    log_step "Fetching Linux artifacts (v${VERSION})..."
    if $DRY_RUN; then
        log_dry "rsync ${host}:${remote_dir}/dist/*${VERSION}* -> ${DIST_DIR}/"
    else
        if ! rsync_from "$host" "$port" "$key" \
            "${remote_dir}/dist/" "$DIST_DIR/" \
            --include='*/' --include="*${VERSION}*" --exclude='*'; then
            log_error "rsync from Linux failed"
            record_result "Linux fetch: FAILED"
            return
        fi
        log_success "Linux artifacts fetched"
    fi

    log_success "Linux builds complete ($(elapsed))"
}

# -----------------------------------------------------------------------
# PHASE 3: WINDOWS BUILDS (remote SSH)
# -----------------------------------------------------------------------

build_windows() {
    if $SKIP_WINDOWS; then
        log_info "Skipping Windows builds (--skip-windows)"
        return
    fi

    log_phase "Phase 3: Windows Builds (remote: ${WINDOWS_HOST})"
    start_timer

    local host="$WINDOWS_HOST"
    local port="${WINDOWS_PORT:-22}"
    local key="${WINDOWS_SSH_KEY:-}"
    local remote_dir="${WINDOWS_PROJECT_DIR}"

    # Windows OpenSSH defaults to cmd.exe which can't run bash commands or
    # find MSYS2/Git Bash tools. All remote commands go through win_ssh_cmd
    # which routes them via Git Bash. rsync uses --rsync-path to invoke the
    # Git Bash rsync binary on the remote side.

    # Detect Git Bash location on the remote machine
    log_step "Detecting Git Bash on remote..."
    if ! $DRY_RUN; then
        if ! detect_win_bash "$host" "$port" "$key"; then
            record_result "Windows: FAILED (no Git Bash found)"
            return
        fi

        # Detect rsync location via Git Bash
        log_step "Detecting rsync on remote..."
        if ! detect_win_rsync "$host" "$port" "$key"; then
            log_info "rsync is not bundled with standard Git for Windows."
            log_info "Install it by one of these methods:"
            log_info "  1. If you have MSYS2: pacman -S rsync"
            log_info "  2. Download Git for Windows SDK (includes pacman):"
            log_info "     https://github.com/git-for-windows/build-extra/releases"
            log_info "  3. Manually copy rsync.exe into C:/Program Files/Git/usr/bin/"
            log_info "     If rsync is present but a DLL is missing, reinstall rsync and its MSYS dependencies."
            record_result "Windows: FAILED (no rsync)"
            return
        fi
        log_success "Git Bash + rsync OK on remote"
    fi

    # Sync source to Windows machine
    log_step "Syncing source to ${host}:${remote_dir}..."
    if $DRY_RUN; then
        log_dry "rsync project to ${host}:${remote_dir}"
        if $CLEAN_REMOTE; then
            log_dry "win_ssh_cmd ${host} 'rm -rf ${remote_dir}/{target,target-static,node_modules,dist,venv}'"
        fi
    else
        # Create remote directory via Git Bash
        win_ssh_cmd "$host" "$port" "$key" "mkdir -p ${remote_dir}" 2>/dev/null || true
        if ! rsync_to_win "$host" "$port" "$key" "$remote_dir"; then
            log_error "rsync to Windows failed"
            log_info "Debug: ssh ${host} '\"$WIN_RSYNC_PATH\" --version'"
            record_result "Windows sync: FAILED"
            return
        fi
        if $CLEAN_REMOTE; then
            log_step "Cleaning build artifacts on remote (--clean-remote)..."
            win_ssh_cmd "$host" "$port" "$key" \
                "rm -rf ${remote_dir}/target ${remote_dir}/target-static ${remote_dir}/node_modules ${remote_dir}/dist ${remote_dir}/venv" \
                || log_warning "Remote cleanup failed (non-fatal)"
        else
            log_info "Reusing remote build artifacts (pass --clean-remote to wipe)"
        fi
        log_success "Source synced"
    fi

    # Build Windows x86_64
    log_step "Building Windows x86_64 (native MSVC on remote)..."
    local win_build_cmd="cd ${remote_dir} && mkdir -p dist"
    win_build_cmd+=" && cargo build --release -p sotf-tui --bin sotf-tui"
    # Canonical artifact naming: <product>-<version>-<os>-<arch>.<ext>
    win_build_cmd+=" && cp target/release/sotf-tui.exe dist/sotf-tui-${VERSION}-windows-x86_64.exe"

    if $DRY_RUN; then
        log_dry "win_ssh_cmd ${host} '${win_build_cmd}'"
    else
        if ! win_ssh_cmd "$host" "$port" "$key" "$win_build_cmd"; then
            log_error "Windows build failed"
            record_result "Windows x86_64: FAILED"
            return
        fi
        record_result "Windows x86_64: OK"
    fi

    # Sign on Windows if cert thumbprint available
    if ! $SKIP_SIGN && [ -n "${WINDOWS_CERT_THUMBPRINT:-}" ]; then
        log_step "Signing Windows executables (SignTool on remote)..."
        local sign_cmd="cd ${remote_dir}"
        sign_cmd+=" && powershell.exe -ExecutionPolicy Bypass -File scripts/sign-windows.ps1"
        sign_cmd+=" -CertificateThumbprint ${WINDOWS_CERT_THUMBPRINT}"
        if $DRY_RUN; then
            log_dry "win_ssh_cmd ${host} sign-windows.ps1"
        else
            if win_ssh_cmd "$host" "$port" "$key" "$sign_cmd"; then
                log_success "Windows signing complete"
                record_result "Windows signing (SignTool): OK"
            else
                log_warning "Windows signing failed (continuing)"
                record_result "Windows signing (SignTool): FAILED"
            fi
        fi
    fi

    # Build MSIX package on remote. Honour --skip-sign so the test path
    # doesn't try to invoke SignTool / a code-signing cert.
    #
    # Pre-clean any stale Windows artifacts for this version on the remote so
    # that arch suffix changes (e.g. the historical x64 → x86_64 rename) don't
    # leave both names in dist/ and get rsynced back into the local dist/.
    #
    # We invoke build-msix.ps1 directly via powershell.exe rather than the
    # bash port via Git Bash. Native PowerShell sees `/o`, `/v`, `/d`, `/p`
    # for what they are (MakeAppx flags) instead of MSYS path-style args, and
    # has no need for cygpath, MSYS_NO_PATHCONV, or a third-party `zip.exe`
    # on PATH.
    log_step "Building MSIX package..."
    local ps_sign=""
    if ! $SKIP_SIGN; then
        ps_sign=" -Sign"
        # Forward cert credentials to the remote PowerShell. SSH usually
        # strips env vars (no AcceptEnv on Windows OpenSSH by default), so
        # we pass them as explicit -CertThumbprint / -CertFile / etc. flags
        # which build-msix.ps1 prefers over $env:WINDOWS_CERT_*.
        if [ -n "${WINDOWS_CERT_THUMBPRINT:-}" ]; then
            ps_sign+=" -CertThumbprint ${WINDOWS_CERT_THUMBPRINT}"
        elif [ -n "${WINDOWS_CERT_FILE:-}" ]; then
            ps_sign+=" -CertFile '${WINDOWS_CERT_FILE}'"
            if [ -n "${WINDOWS_CERT_PASSWORD:-}" ]; then
                ps_sign+=" -CertPassword '${WINDOWS_CERT_PASSWORD}'"
            fi
        fi
        if [ -n "${WINDOWS_TIMESTAMP_URL:-}" ]; then
            ps_sign+=" -TimestampUrl '${WINDOWS_TIMESTAMP_URL}'"
        fi
    fi
    local msix_cleanup="cd ${remote_dir} && rm -f dist/sotf-desktop-${VERSION}-windows-*.msix"
    local msix_powershell="powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts/build-msix.ps1 -Arch x86_64${ps_sign}"
    local msix_cmd="${msix_cleanup} && ${msix_powershell}"
    if $DRY_RUN; then
        log_dry "win_ssh_cmd ${host} '${msix_cleanup}'"
        log_dry "win_ssh_cmd ${host} '${msix_powershell}'"
    else
        if win_ssh_cmd "$host" "$port" "$key" "$msix_cmd"; then
            record_result "Windows MSIX: OK"
        else
            log_warning "MSIX build failed (continuing)"
            record_result "Windows MSIX: FAILED"
        fi
    fi

    # Copy artifacts back (current version only)
    log_step "Fetching Windows artifacts (v${VERSION})..."
    if $DRY_RUN; then
        log_dry "rsync ${host}:${remote_dir}/dist/*${VERSION}* -> ${DIST_DIR}/"
    else
        if ! rsync_from_win "$host" "$port" "$key" \
            "${remote_dir}/dist/" "$DIST_DIR/" \
            --include='*/' --include="*${VERSION}*" --exclude='*'; then
            log_error "rsync from Windows failed"
            record_result "Windows fetch: FAILED"
            return
        fi
        log_success "Windows artifacts fetched"
    fi

    log_success "Windows builds complete ($(elapsed))"
}

# -----------------------------------------------------------------------
# PHASE 4: POST-BUILD (cosign, checksums, site, release prep)
# -----------------------------------------------------------------------

post_build() {
    log_phase "Phase 4: Post-Build (signing, checksums, site)"
    start_timer

    # --- Normalize artifact filenames to <product>-<version>-<os>-<arch>.<ext> ---
    # Some helper scripts (e.g. build-dmg-sotf.sh) emit <product>-<os>-<arch>-<version>.<ext>;
    # rename them here so checksums and cosign signatures use the canonical name.
    normalize_artifact_names

    # --- Cosign non-Apple artifacts ---
    if ! $SKIP_SIGN; then
        sign_with_cosign
    fi

    # --- SHA256 checksums ---
    generate_checksums

    # --- Release notes ---
    generate_release_notes

    # --- Update site ---
    if ! $SKIP_SITE; then
        update_site
    fi

    log_success "Post-build complete ($(elapsed))"
}

normalize_artifact_names() {
    log_step "Normalizing artifact filenames..."

    if $DRY_RUN; then
        log_dry "Rename any <product>-<os>-<arch>-<version>.<ext> in dist/ to <product>-<version>-<os>-<arch>.<ext>"
        return
    fi

    # Match: <product>-<os>-<arch>-<version>.<ext>
    # Use bash regex with BASH_REMATCH; .ext intentionally greedy so .tar.gz survives.
    local pattern='^(.+)-(macos|darwin|linux|windows|win)-(arm64|aarch64|x86_64|amd64|x86|arm)-([0-9]+\.[0-9]+\.[0-9]+)(\..+)$'
    local renamed=0
    shopt -s nullglob
    for f in "$DIST_DIR"/*; do
        [ -f "$f" ] || continue
        local base
        base=$(basename "$f")
        if [[ "$base" =~ $pattern ]]; then
            local product="${BASH_REMATCH[1]}"
            local os="${BASH_REMATCH[2]}"
            local arch="${BASH_REMATCH[3]}"
            local ver="${BASH_REMATCH[4]}"
            local ext="${BASH_REMATCH[5]}"
            local newname="${product}-${ver}-${os}-${arch}${ext}"
            if [ "$base" = "$newname" ]; then
                continue
            fi
            if [ -e "$DIST_DIR/$newname" ]; then
                log_warning "Skip rename: target exists ($newname)"
                continue
            fi
            log_info "Renaming: $base → $newname"
            mv "$f" "$DIST_DIR/$newname"
            renamed=$((renamed + 1))
        fi
    done
    shopt -u nullglob

    if [ "$renamed" -gt 0 ]; then
        log_success "Renamed $renamed artifact(s) to canonical naming"
    else
        log_info "No artifacts needed renaming"
    fi
}

sign_with_cosign() {
    log_step "Signing artifacts with cosign..."

    if ! command -v cosign &>/dev/null; then
        log_warning "cosign not installed, skipping"
        record_result "Cosign: SKIPPED (not installed)"
        return
    fi

    local use_key=false
    if [ -n "${COSIGN_KEY:-}" ]; then
        use_key=true
        log_info "Using key-based signing: $COSIGN_KEY"
    else
        log_info "Using keyless OIDC signing (will open browser)"
    fi

    local signed_count=0

    for artifact in "$DIST_DIR"/*; do
        [ -f "$artifact" ] || continue
        local name
        name=$(basename "$artifact")

        # Cosign whitelist: only sign Windows .exe and Linux .AppImage / .tar.gz.
        # macOS .dmg / .pkg / bare binaries are already signed by Apple Developer ID.
        # .msix is signed by the Microsoft Store at submission time, not by us.
        # Logs, checksums, release notes, and existing cosign bundles are not signed.
        case "$name" in
            *.exe|*.AppImage|*.appimage|*.tar.gz) ;;
            *) continue ;;
        esac

        # Only sign artifacts for the current version.
        case "$name" in
            *"$VERSION"*) ;;
            *) continue ;;
        esac

        # Respect --skip-* flags so we don't sign artifacts for platforms we
        # didn't build this run. Canonical naming carries the OS segment.
        case "$name" in
            *linux*)   if $SKIP_LINUX;   then continue; fi ;;
            *windows*) if $SKIP_WINDOWS; then continue; fi ;;
        esac

        if $DRY_RUN; then
            log_dry "cosign sign-blob $name"
        else
            log_info "Signing: $name"
            if $use_key; then
                cosign sign-blob \
                    --key "$COSIGN_KEY" \
                    --bundle "${artifact}.bundle" \
                    "$artifact" || {
                    log_warning "Failed to sign $name"
                    continue
                }
            else
                cosign sign-blob \
                    --bundle "${artifact}.bundle" \
                    "$artifact" || {
                    log_warning "Failed to sign $name"
                    continue
                }
            fi
            signed_count=$((signed_count + 1))
        fi
    done

    if [ "$signed_count" -gt 0 ]; then
        log_success "Cosigned $signed_count artifacts"
        record_result "Cosign: OK ($signed_count artifacts)"
    else
        log_info "No artifacts to cosign"
        record_result "Cosign: nothing to sign"
    fi
}

generate_checksums() {
    log_step "Generating SHA256 checksums..."

    if $DRY_RUN; then
        log_dry "sha256sum dist/*${VERSION}* > dist/SHA256SUMS"
        return
    fi

    local checksum_file="$DIST_DIR/SHA256SUMS"
    rm -f "$checksum_file"

    cd "$DIST_DIR"
    local count=0
    for f in *; do
        [ -f "$f" ] || continue
        # Skip signatures, checksums, markdown
        case "$f" in
            *.bundle|*.sig|*.cert|*.md|SHA256SUMS*) continue ;;
        esac
        # Only checksum current version artifacts
        case "$f" in
            *"$VERSION"*) ;;
            *) continue ;;
        esac
        shasum -a 256 "$f" >> "$checksum_file"
        count=$((count + 1))
    done
    cd "$PROJECT_ROOT"

    if [ "$count" -gt 0 ]; then
        log_success "SHA256 checksums for $count files: $checksum_file"
    else
        log_warning "No artifacts found for checksumming"
    fi
}

generate_release_notes() {
    log_step "Generating release notes..."

    # Forward our --skip-site to build-release.sh so it doesn't rewrite
    # site/src/components/Download.astro when the user has asked us to leave
    # the site alone.
    local args=(--skip-build)
    if $SKIP_SITE; then
        args+=(--skip-site)
    fi

    if $DRY_RUN; then
        log_dry "./scripts/build-release.sh ${args[*]}"
        return
    fi

    # Reuse the existing release notes generator
    ./scripts/build-release.sh "${args[@]}"

    record_result "Release notes: OK"
}

update_site() {
    log_step "Updating website Download component..."

    if $DRY_RUN; then
        log_dry "Update site/src/components/Download.astro to v${VERSION}"
        return
    fi

    # The build-release.sh --skip-build already updates the site component,
    # but we also build the site and optionally deploy it.

    local site_dir="$PROJECT_ROOT/site"
    if [ ! -d "$site_dir" ]; then
        log_warning "Site directory not found, skipping"
        return
    fi

    log_step "Building site..."
    cd "$site_dir"
    npm run build
    cd "$PROJECT_ROOT"

    log_success "Site built"

    if $DEPLOY_SITE; then
        if [ ! -x "$site_dir/update_prod.sh" ]; then
            log_warning "$site_dir/update_prod.sh missing or not executable; skipping deploy"
            record_result "Site deploy: SKIPPED (script not found)"
        else
            log_step "Deploying site + release binaries via update_prod.sh..."
            cd "$site_dir"
            if ./update_prod.sh; then
                log_success "Site + binaries deployed"
                record_result "Site deploy: OK"
            else
                log_error "update_prod.sh failed"
                record_result "Site deploy: FAILED"
            fi
            cd "$PROJECT_ROOT"
        fi
    elif [ -n "${SITE_DEPLOY_TARGET:-}" ]; then
        log_info "Site deploy target: $SITE_DEPLOY_TARGET"
        log_info "Re-run with --deploy-site to push, or manually: ./site/update_prod.sh"
    fi

    record_result "Site update: OK"
}

# -----------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------

print_summary() {
    log_phase "Release Build Summary — v${VERSION}"

    # List artifacts
    log_step "Artifacts in ${DIST_DIR}:"
    local artifact_count=0
    for f in "$DIST_DIR"/*"$VERSION"*; do
        if [ -f "$f" ]; then
            local size
            size=$(du -h "$f" | cut -f1)
            local name
            name=$(basename "$f")
            printf "  %-50s %s\n" "$name" "$size"
            artifact_count=$((artifact_count + 1))
        fi
    done

    if [ "$artifact_count" -eq 0 ]; then
        log_warning "No artifacts found for v${VERSION}"
    fi

    echo ""

    # Build results
    if [ ${#BUILD_RESULTS[@]} -gt 0 ]; then
        log_step "Build results:"
        for result in "${BUILD_RESULTS[@]}"; do
            echo "  $result"
        done
        echo ""
    fi

    # Checksums
    if [ -f "$DIST_DIR/SHA256SUMS" ]; then
        log_step "Checksums: $DIST_DIR/SHA256SUMS"
    fi

    # Release notes
    if [ -f "$DIST_DIR/release-${VERSION}.md" ]; then
        log_step "Release notes: $DIST_DIR/release-${VERSION}.md"
    fi

    echo ""
    log_step "Next steps:"
    echo "  1. Review release notes: $DIST_DIR/release-${VERSION}.md"
    echo "  2. Add changelog entries"
    echo "  3. Create GitHub release:"
    echo "     git tag v${VERSION}"
    echo "     git push github v${VERSION}"
    echo "     gh release create v${VERSION} --title 'SotF v${VERSION}' \\"
    echo "       --notes-file $DIST_DIR/release-${VERSION}.md \\"
    echo "       $DIST_DIR/*${VERSION}* $DIST_DIR/SHA256SUMS"
    echo "  4. Deploy site: cd site && ./update_prod.sh"
}

# -----------------------------------------------------------------------
# MAIN
# -----------------------------------------------------------------------

main() {
    log_phase "SotF Release Build v${VERSION}"

    if $DRY_RUN; then
        log_warning "DRY RUN — no actions will be taken"
    fi

    preflight

    if ! $POST_ONLY; then
        build_macos
        build_linux
        build_windows
    else
        log_info "Post-only mode — skipping builds"
    fi

    post_build
    print_summary
}

main
