#!/usr/bin/env bash
# Script to create the Xcode project for SOTF Audio Units

set -e

echo "=================================================="
echo "SOTF Audio Units - Xcode Project Setup"
echo "=================================================="
echo ""
echo "This script provides instructions for creating the Xcode project."
echo "Unfortunately, Xcode projects can't be easily scripted, so you'll"
echo "need to follow these steps manually."
echo ""
echo "=================================================="
echo "STEP 1: Create App Extension Project"
echo "=================================================="
echo ""
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. Choose 'macOS' → 'App'"
echo "4. Set:"
echo "   - Product Name: SOTFAudioUnits"
echo "   - Organization: org.spinorama"
echo "   - Bundle Identifier: org.spinorama.SOTFAudioUnits"
echo "   - Language: Swift"
echo "   - User Interface: SwiftUI"
echo "5. Save in: $(pwd)"
echo ""
echo "=================================================="
echo "STEP 2: Add Audio Unit Extension"
echo "=================================================="
echo ""
echo "1. File → New → Target"
echo "2. Choose 'macOS' → 'Audio Unit Extension'"
echo "3. Set:"
echo "   - Product Name: EQAudioUnit"
echo "   - Organization: org.spinorama"
echo "   - Bundle Identifier: org.spinorama.SOTFAudioUnits.EQAudioUnit"
echo "   - Language: Swift"
echo "4. Click Finish"
echo "5. When asked 'Activate EQAudioUnit scheme?', click Activate"
echo ""
echo "=================================================="
echo "STEP 3: Configure Audio Unit"
echo "=================================================="
echo ""
echo "1. In Project Navigator, select EQAudioUnit target"
echo "2. General tab:"
echo "   - Deployment Target: macOS 15.0"
echo "   - Bundle Identifier: org.spinorama.SOTFAudioUnits.EQAudioUnit"
echo ""
echo "3. Build Settings tab:"
echo "   - Search for 'Library Search Paths'"
echo "   - Add: \$(PROJECT_DIR)/Resources"
echo "   - Search for 'Header Search Paths'"
echo "   - Add: \$(PROJECT_DIR)/Shared"
echo "   - Search for 'Swift Compiler - General'"
echo "   - Set 'Objective-C Bridging Header' to: Shared/BridgingHeader.h"
echo ""
echo "4. Build Phases tab:"
echo "   - Under 'Link Binary With Libraries', click +"
echo "   - Click 'Add Other...' → 'Add Files...'"
echo "   - Navigate to Resources/libsotf_audio_ffi.a and add it"
echo ""
echo "=================================================="
echo "STEP 4: Replace Generated Files"
echo "=================================================="
echo ""
echo "1. Delete the auto-generated files in EQAudioUnit group:"
echo "   - AudioUnitViewController.swift (or similar)"
echo "   - MainInterface.storyboard (if present)"
echo ""
echo "2. Add the SOTF files:"
echo "   - Right-click EQAudioUnit group → Add Files to 'SOTFAudioUnits'"
echo "   - Select:"
echo "     - EQAudioUnit/EQAudioUnit.swift"
echo "     - EQAudioUnit/EQViewController.swift"
echo "     - EQAudioUnit/Info.plist"
echo ""
echo "3. Update Info.plist:"
echo "   - In target settings, Info tab"
echo "   - Set Custom macOS Application Target Properties"
echo "   - Or use the provided Info.plist"
echo ""
echo "=================================================="
echo "STEP 5: Build Rust Library First"
echo "=================================================="
echo ""
echo "Before building in Xcode, run:"
echo ""
echo "  just build-au-rust"
echo ""
echo "This creates Resources/libsotf_audio_ffi.a"
echo ""
echo "=================================================="
echo "STEP 6: Build and Test"
echo "=================================================="
echo ""
echo "1. Select EQAudioUnit scheme"
echo "2. Product → Build (⌘B)"
echo "3. If successful, install with:"
echo ""
echo "  just install-au"
echo ""
echo "4. Test in Logic Pro, GarageBand, or with auval:"
echo ""
echo "  auval -v aufx SOEQ SOTF"
echo ""
echo "=================================================="
echo ""
echo "For more details, see README.md"
echo ""
