// Auto-generated by r2factor. Manual edits will be overwritten on next split.


/// Direct time-domain FIR convolution for the first N taps of the IR.
///
/// Provides zero additional latency by processing samples immediately.
/// Used in combination with FFT-based partition levels for the IR tail.
pub(super) struct TimeDomainHead {
    /// First N samples of the IR (reversed for direct convolution)
    pub(super) ir_taps: Vec<f32>,
    /// Circular input history buffer
    pub(super) history: Vec<f32>,
    /// Write position in history
    pub(super) pos: usize,
    /// Number of taps
    pub(super) n_taps: usize,
}

impl TimeDomainHead {
    pub(super) fn new(ir: &[f32], n_taps: usize) -> Self {
        let n = n_taps.min(ir.len());
        // Reverse the IR for direct convolution: y[n] = sum(h[k] * x[n-k])
        let mut ir_taps = vec![0.0; n];
        for (i, tap) in ir_taps.iter_mut().enumerate() {
            *tap = ir[i];
        }
        Self {
            ir_taps,
            history: vec![0.0; n],
            pos: 0,
            n_taps: n,
        }
    }

    #[inline]
    pub(super) fn process_sample(&mut self, sample: f32) -> f32 {
        self.history[self.pos] = sample;
        let mut output = 0.0;
        let mut read = self.pos;
        for &tap in &self.ir_taps {
            output += tap * self.history[read];
            if read == 0 {
                read = self.n_taps - 1;
            } else {
                read -= 1;
            }
        }
        self.pos = (self.pos + 1) % self.n_taps;
        output
    }

    pub(super) fn reset(&mut self) {
        self.history.fill(0.0);
        self.pos = 0;
    }
}

