//! Color Token System
//!
//! Provides semantic color tokens with automatic variant generation.
//! This system makes it easy to create consistent color palettes with
//! hover, active, muted, and subtle variants derived from a base color.
//!
//! # Usage
//!
//! ```ignore
//! use gpui_ui_kit::color_tokens::{ColorToken, SemanticColors};
//!
//! // Create a color token from a base color
//! let primary = ColorToken::from_base(rgb(0x007acc));
//!
//! // Use the variants
//! element
//!     .bg(primary.base)
//!     .hover(|s| s.bg(primary.hover))
//!     .active(|s| s.bg(primary.active));
//!
//! // Or create a full semantic color palette
//! let colors = SemanticColors::default();
//! element.bg(colors.success.base);
//! ```
//!
//! # Color Variants
//!
//! Each `ColorToken` provides:
//! - `base`: The original color
//! - `hover`: Slightly lighter/more saturated for hover states
//! - `active`: Slightly darker for pressed/active states
//! - `muted`: Low opacity version for backgrounds
//! - `subtle`: Very low opacity for subtle highlights

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

mod background_colors;
mod border_colors;
mod color_palette;
mod color_token;
mod misc;
mod semantic_colors;
#[cfg(test)]
mod tests;
mod text_colors;

pub use background_colors::BackgroundColors;
pub use border_colors::BorderColors;
pub use color_palette::ColorPalette;
pub use color_token::ColorToken;
pub use misc::{darken, desaturate, lighten, saturate, with_alpha};
pub use semantic_colors::SemanticColors;
pub use text_colors::TextColors;
