// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate :: params :: { BAND_PARAMS , PARAMS as DQ } ;
use sotf_host::param_specs::find_by_key as pk;
use super::dyn_eq_band_params::DynEqBandParams;

pub(super) fn default_num_bands() -> usize {
    pk(DQ, "num_bands").default_f64() as usize
}

pub(super) fn default_threshold() -> f32 {
    pk(DQ, "threshold").default_f64() as f32
}

pub(super) fn default_ratio() -> f32 {
    pk(DQ, "ratio").default_f64() as f32
}

pub(super) fn default_attack() -> f32 {
    pk(DQ, "attack").default_f64() as f32
}

pub(super) fn default_release() -> f32 {
    pk(DQ, "release").default_f64() as f32
}

pub(super) fn default_knee() -> f32 {
    pk(DQ, "knee").default_f64() as f32
}

pub(super) fn default_link_channels() -> bool {
    pk(DQ, "link_channels").default_bool()
}

pub(super) fn default_mix() -> f32 {
    pk(DQ, "mix").default_f64() as f32
}

pub(super) fn default_band_frequency() -> f32 {
    pk(BAND_PARAMS, "frequency").default_f64() as f32
}

pub(super) fn default_band_q() -> f32 {
    pk(BAND_PARAMS, "q").default_f64() as f32
}

pub(super) fn default_band_gain() -> f32 {
    pk(BAND_PARAMS, "gain").default_f64() as f32
}

pub(super) fn default_band_threshold() -> f32 {
    pk(BAND_PARAMS, "band_threshold").default_f64() as f32
}

pub(super) fn default_band_ratio() -> f32 {
    pk(BAND_PARAMS, "band_ratio").default_f64() as f32
}

pub(super) fn default_band_active() -> bool {
    pk(BAND_PARAMS, "active").default_bool()
}

pub(super) fn default_bands_params() -> Vec<DynEqBandParams> {
    let n = default_num_bands();
    (0..n).map(|_| DynEqBandParams::default()).collect()
}

