// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::axis::Axis;

/// External state provided to the solver. The solver reads but never writes.
#[derive(Debug, Clone, Default)]
pub struct LayoutPreferences<'a> {
    /// Per-slot ratio overrides, keyed by (slot_id, parent_axis).
    /// When the solver resolves a `Fractional` slot, it looks here first.
    /// If not found, uses `Sizing::Fractional::initial`.
    pub ratios: &'a [(&'a str, Axis, f32)],
    /// Per-slot collapsed state from user toggle.
    /// If a slot's id appears here with `true`, and the slot is `collapsible`,
    /// the solver treats it as collapsed (0 size) regardless of available space.
    pub collapsed: &'a [(&'a str, bool)],
}

impl<'a> LayoutPreferences<'a> {
    /// Look up the user's ratio override for a slot in a given axis.
    pub fn ratio_for(&self, id: &str, axis: Axis) -> Option<f32> {
        self.ratios
            .iter()
            .find(|(slot_id, a, _)| *slot_id == id && *a == axis)
            .map(|(_, _, r)| *r)
    }

    /// Check if a slot is user-collapsed.
    pub fn is_collapsed(&self, id: &str) -> bool {
        self.collapsed
            .iter()
            .any(|(slot_id, collapsed)| *slot_id == id && *collapsed)
    }
}
