//! Action definitions for the GPUI audio player.
//!
//! All keyboard actions are defined here and used by both keybindings
//! and the UI layer.

use gpui::*;

// Actions for keyboard shortcuts
actions!(
    player_ui,
    [
        PlayPause,
        Stop,
        NextTrack,
        PrevTrack,
        VolumeUp,
        VolumeDown,
        VolumeUpSmall,
        VolumeDownSmall,
        VolumeUpLarge,
        VolumeDownLarge,
        VolumeMax,
        VolumeMin,
        ToggleMute,
        SwitchToDevices,
        SwitchToDirectories,
        SwitchToHeadphoneEQ,
        SwitchToLibrary,
        SwitchToQueue,
        SwitchToPlugins,
        SwitchToStudio,
        SwitchToPluginGraph,
        SwitchToListeningTest,
        EarTrainingShowEqBands,
        EarTrainingShowBlindComparison,
        EarTrainingStart,
        EarTrainingPlayOriginal,
        EarTrainingPlayFiltered,
        EarTrainingSelectPreviousBand,
        EarTrainingSelectNextBand,
        EarTrainingSubmit,
        EarTrainingNextQuestion,
        ListeningCapturePathA,
        ListeningCapturePathB,
        ListeningPrepare,
        ListeningStartBlindAb,
        ListeningStartAbx,
        ListeningPlayCue1,
        ListeningPlayCue2,
        ListeningPlayCue3,
        ListeningCommitAnswer1,
        ListeningCommitAnswer2,
        SwitchToRoomEQ,
        SwitchToSpectrum,
        SwitchToSettings,
        SwitchToRecording,
        SwitchToSpinorama,
        OpenConfig, // Menu bar: open config (cmd-,)
        QuitApp,    // Menu bar: quit app (cmd-q)
        CycleTheme,
        CycleLanguage,
        ToggleSearch,
        ToggleLibraryView,
        ToggleHelp,
        ToggleHelpSupport,
        ToggleCommandPalette,
        ToggleScreenGuide,
        GraphSelectNextNode,
        GraphSelectPreviousNode,
        GraphSelectNextPluginType,
        GraphSelectPreviousPluginType,
        GraphSelectNextPort,
        GraphSelectPreviousPort,
        GraphAddSelectedPlugin,
        GraphEditSelectedNode,
        GraphToggleSelectedBypass,
        GraphConnectSelectedNode,
        GraphDisconnectSelectedNode,
        GraphRemoveSelectedNode,
        GraphMoveSelectedLeft,
        GraphMoveSelectedRight,
        GraphMoveSelectedUp,
        GraphMoveSelectedDown,
        GraphMoveSelectedLeftLarge,
        GraphMoveSelectedRightLarge,
        GraphMoveSelectedUpLarge,
        GraphMoveSelectedDownLarge,
        About,
        CycleSortOrder,
        SetSortArtist,
        SetSortAlbum,
        SetSortTitle,
        SetSortYear,
        CycleChannelFilter,
        SetFilterAll,
        SetFilterMono,
        SetFilterStereo,
        SetFilterSurround,
        SetFilterSurround71,
        SetFilterSurroundPlus,
        SetFilterMixed,
        SelectNext,
        SelectPrev,
        SelectNextPage,
        SelectPrevPage,
        NextPage,    // For library pagination
        PrevPage,    // For library pagination
        SelectLeft,  // Grid: move left
        SelectRight, // Grid: move right
        SelectUp,    // Grid: move up
        SelectDown,  // Grid: move down
        PreviousWorkflowStep,
        NextWorkflowStep,
        ToggleExpand,
        Enter,
        Cancel,
        RemoveItem,
        ClearQueue,
        FillQueueMagic,
        AddToQueue, // Album context menu: add album to queue
        PlayNow,    // Album context menu: play album now
        MovePluginUp,
        MovePluginDown,
        TogglePlugin,
        EqChartNudgeLeft,
        EqChartNudgeRight,
        EqChartNudgeUp,
        EqChartNudgeDown,
        EqChartNudgeLeftFine,
        EqChartNudgeRightFine,
        EqChartNudgeUpFine,
        EqChartNudgeDownFine,
        AddDirectory,
        ScanLibrary,
        QuickAddEQ,
        QuickAddGain,
        QuickAddUpmixer,
        QuickAddAAE,
        QuickAddCompressor,
        QuickAddGate,
        QuickAddLimiter,
        QuickAddExpander,
        QuickAddMultibandCompressor,
        QuickAddMultibandExpander,
        QuickAddLoudness,
        QuickAddFletcherMunson,
        QuickAddBinaural,
        QuickAddConvolution,
        QuickAddLoudnessMonitor,
        QuickAddSpectrum,
        QuickAddMuteSolo,
        QuickAddXTC,
        QuickAddDenoiser,
        QuickAddPnd,
        QuickAddABCompare,
        QuickAddDownmix,
        QuickAddMonoToStereo,
        QuickAddBandSplit,
        QuickAddBandMerge,
        QuickAddCrossfeed,
        QuickAddDelay,
        QuickAddAec,
        QuickAddBeamformer,
        QuickAddTransientShaper,
        QuickAddSaturation,
        QuickAddDynamicEq,
        QuickAddLinearPhaseEq,
        QuickAddSpectralCompressor,
        // Level meter actions
        SelectNextMeterGroup,
        SelectPrevMeterGroup,
        ToggleMeterMute,
        ToggleMeterSolo,
        ToggleMeterDim,
        ClearMeterMutesSolos,
        IncrementPluginParam,
        DecrementPluginParam,
        IncrementPluginParamLarge,
        DecrementPluginParamLarge,
        IncrementPluginParamSmall,
        DecrementPluginParamSmall,
        // Plugin view mode
        ToggleSimpleView,
        ToggleABPath,
        // Font size actions
        IncreaseFontSize,
        DecreaseFontSize,
        ResetFontSize,
        // Favorites
        ToggleFavoritesFilter,
        ToggleAlbumFavorite,
        // Playlist actions
        SwitchToPlaylists,
        CreatePlaylist,
        DeletePlaylist,
        RenamePlaylist,
        OpenPlaylist,
        PlayPlaylist,
        ImportPlaylist,
        ExportPlaylist,
        // Band selection for multiband plugins (0 = Global, 1-5 = bands)
        SelectBandGlobal,
        SelectBand1,
        SelectBand2,
        SelectBand3,
        SelectBand4,
        SelectBand5,
        // EQ band navigation
        SelectNextEqBand,
        SelectPrevEqBand,
        // Design system switching
        SetDesignNeutral,
        SetDesignAppleHig,
        SetDesignMaterial3,
        SetDesignFluent,
    ]
);
