// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use delaunator::EMPTY;

pub(super) const NO_EDGE: usize = EMPTY;

/// Squared bounding-box diagonal of a flat coordinate array.
///
/// Translation-invariant — moving the entire point set by a large offset
/// (e.g. lon/lat shifted by `1e6`) does not inflate the scale. The
/// previous implementation used the maximum absolute coordinate, which
/// caused non-degenerate triangulations on translated point sets to be
/// mis-flagged as collinear.
///
/// Returns at least `1.0` so the threshold never collapses to zero on
/// degenerate (single-point or coincident) inputs.
pub(super) fn bbox_scale_sq(coords: &[f64]) -> f64 {
    let mut xmin = f64::INFINITY;
    let mut xmax = f64::NEG_INFINITY;
    let mut ymin = f64::INFINITY;
    let mut ymax = f64::NEG_INFINITY;
    for i in (0..coords.len()).step_by(2) {
        let x = coords[i];
        let y = coords[i + 1];
        if !x.is_finite() || !y.is_finite() {
            continue;
        }
        if x < xmin {
            xmin = x;
        }
        if x > xmax {
            xmax = x;
        }
        if y < ymin {
            ymin = y;
        }
        if y > ymax {
            ymax = y;
        }
    }
    if !xmin.is_finite() || !ymin.is_finite() {
        return 1.0;
    }
    let dx = xmax - xmin;
    let dy = ymax - ymin;
    let s2 = dx * dx + dy * dy;
    if s2 > 0.0 { s2 } else { 1.0 }
}

pub(super) fn splitmix64(mut x: u64) -> u64 {
    x = x.wrapping_add(0x9e37_79b9_7f4a_7c15);
    x = (x ^ (x >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    x = (x ^ (x >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    x ^ (x >> 31)
}

pub(super) fn jitter_unit(i: usize, x: f64, y: f64, salt: u64) -> f64 {
    let seed = (i as u64).wrapping_mul(0xd6e8_feb8_6659_fd93)
        ^ x.to_bits().rotate_left(17)
        ^ y.to_bits().rotate_left(41)
        ^ salt;
    let unit = ((splitmix64(seed) >> 11) as f64) * (1.0 / ((1_u64 << 53) as f64));
    unit * 2.0 - 1.0
}

/// Test whether all returned triangles are degenerate (collinear within
/// a bounding-box-relative tolerance).
///
/// The 2D cross product has units of area (`length²`), so we compare it
/// to `1e-10 · bbox_diagonal²` — a relative tolerance that is translation
/// invariant.
///
/// **NaN handling.** If any vertex coordinate is non-finite we return
/// `false` (treat as not-collinear) so the caller skips the jitter
/// path. The previous implementation returned `true` for NaN input
/// because `f64::NAN.abs() > x` is always `false`, which silently
/// triggered jitter on otherwise-finite point sets containing a single
/// NaN.
pub(super) fn is_collinear(triangles: &[usize], coords: &[f64]) -> bool {
    let scale_sq = bbox_scale_sq(coords);
    let threshold = 1e-10 * scale_sq;
    for i in (0..triangles.len()).step_by(3) {
        let a = 2 * triangles[i];
        let b = 2 * triangles[i + 1];
        let c = 2 * triangles[i + 2];
        let ax = coords[a];
        let ay = coords[a + 1];
        let bx = coords[b];
        let by = coords[b + 1];
        let cx = coords[c];
        let cy = coords[c + 1];
        if !(ax.is_finite()
            && ay.is_finite()
            && bx.is_finite()
            && by.is_finite()
            && cx.is_finite()
            && cy.is_finite())
        {
            return false;
        }
        let cross = (cx - ax) * (by - ay) - (bx - ax) * (cy - ay);
        if cross.abs() > threshold {
            return false;
        }
    }
    true
}
