// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use sotf_host::param_specs::{ParamSpec, ParamType, UpdateMode};
use std::ffi::OsString;
use std :: path :: { PathBuf } ;
use super::format;
use super::format::format_default;
use super::format::format_float;
use super::format::format_range;
use super::generate::generate_params_table;
use super::generate::generate_plugin_page;
use super::misc::md_cell;
use super::misc::write_if_changed;
use super::misc::yaml_double_quoted;
use super::parse::parse_args_from;
use super::plugin_entry::plugin_registry;
use super::plugin_entry::validate_registry;
use super::types::Args;
use super::types::PluginEntry;

    use super::*;
    use sotf_host::param_specs::ParamCategory;

    fn make_float_spec(name: &'static str, doc: &'static str, unit: &'static str) -> ParamSpec {
        ParamSpec {
            name,
            engine_key: "test_key",
            param_type: ParamType::Float {
                default: 0.5,
                min: 0.0,
                max: 1.0,
                step: 0.01,
            },
            unit,
            group: "",
            update_mode: UpdateMode::Realtime,
            display_scale: 1.0,
            category: ParamCategory::Primary,
            doc,
        }
    }

    fn make_grouped_float_spec(group: &'static str) -> ParamSpec {
        ParamSpec {
            name: "Grouped",
            engine_key: "grouped",
            param_type: ParamType::Float {
                default: 0.30000001,
                min: -1.0,
                max: 1.0,
                step: 0.01,
            },
            unit: "dB",
            group,
            update_mode: UpdateMode::Realtime,
            display_scale: 1.0,
            category: ParamCategory::Primary,
            doc: "Grouped parameter",
        }
    }

    #[test]
    fn md_cell_escapes_pipes_backslashes_and_newlines() {
        assert_eq!(md_cell("a|b"), "a\\|b");
        assert_eq!(md_cell("a\\b"), "a\\\\b");
        assert_eq!(md_cell("line1\nline2"), "line1<br>line2");
        assert_eq!(md_cell("a\rb"), "a<br>b");
        assert_eq!(md_cell("a|b\\c\nd"), "a\\|b\\\\c<br>d");
        assert_eq!(md_cell("hello world"), "hello world");
    }

    #[test]
    fn yaml_double_quoted_escapes_quotes_and_backslashes() {
        assert_eq!(yaml_double_quoted("a\"b"), "a\\\"b");
        assert_eq!(yaml_double_quoted("a\\b"), "a\\\\b");
        assert_eq!(yaml_double_quoted("a\nb"), "a b");
        assert_eq!(yaml_double_quoted("a\rb"), "a b");
        assert_eq!(
            yaml_double_quoted("Adds \"warmth\"\nto signal"),
            "Adds \\\"warmth\\\" to signal"
        );
    }

    /// Pipe-table rows must be single-line and have the expected number of
    /// non-escaped column separators (one more than the cell count).
    fn assert_single_row(row: &str, expected_cells: usize) {
        assert!(!row.contains('\n'), "row contains a raw newline: {row:?}");
        assert!(row.starts_with('|'), "row does not start with '|': {row:?}");
        assert!(row.ends_with('|'), "row does not end with '|': {row:?}");
        let bytes = row.as_bytes();
        let separator_count = bytes
            .iter()
            .enumerate()
            .filter(|&(i, &c)| c == b'|' && (i == 0 || bytes[i - 1] != b'\\'))
            .count();
        assert_eq!(
            separator_count,
            expected_cells + 1,
            "expected {} cells in row but found {} separators: {row:?}",
            expected_cells,
            separator_count.saturating_sub(1),
        );
    }

    #[test]
    fn params_table_round_trips_pipes_quotes_and_newlines() {
        let evil_name = "Gain | \"main\"";
        let evil_doc = "Sets the \"main\" gain.\nUse with |care|.\\nope";
        let evil_unit = "dB|FS";
        let spec = make_float_spec(evil_name, evil_doc, evil_unit);

        let table = generate_params_table(std::slice::from_ref(&spec));

        let lines: Vec<&str> = table.lines().filter(|l| !l.is_empty()).collect();
        assert_eq!(lines.len(), 3, "expected 3 lines, got: {table}");
        assert_single_row(lines[0], 6); // header
        // lines[1] is the |---|---| separator row — skip strict check.
        assert_single_row(lines[2], 6); // data row

        // The pipe in the name must be escaped; quotes are valid markdown
        // and pass through unchanged.
        assert!(
            lines[2].contains("Gain \\| \"main\""),
            "name not escaped properly: {}",
            lines[2]
        );
        assert!(
            lines[2].contains("dB\\|FS"),
            "unit pipe not escaped: {}",
            lines[2]
        );
        assert!(
            lines[2].contains("<br>"),
            "newline in doc not converted: {}",
            lines[2]
        );
    }

    #[test]
    fn single_named_group_keeps_heading() {
        let spec = make_grouped_float_spec("Filter");
        let table = generate_params_table(std::slice::from_ref(&spec));
        assert!(
            table.contains("### Filter"),
            "single named group heading was dropped: {table}"
        );
    }

    #[test]
    fn empty_plugin_page_reports_no_configurable_parameters() {
        let entry = PluginEntry {
            slug: "meter",
            name: "Meter",
            description: "Read-only analysis plugin.",
            params: &[],
            global_params: None,
            band_template: None,
        };

        let page = generate_plugin_page(&entry);
        assert!(
            page.contains("*No configurable parameters.*"),
            "empty plugin page has no fallback parameter text: {page}"
        );
    }

    #[test]
    fn float_formatting_is_finite_and_trimmed() {
        assert_eq!(format_float(1.0), "1");
        assert_eq!(format_float(0.30000001), "0.3");
        assert_eq!(format_float(-0.0), "0");
        let spec = make_grouped_float_spec("");
        assert!(format_range(&spec).contains("-1 .. 1"));
        assert_eq!(format_default(&spec), "0.3");
    }

    #[test]
    #[should_panic(expected = "non-finite float")]
    fn float_formatting_rejects_nan() {
        let _ = format_float(f64::NAN);
    }

    #[test]
    fn plugin_page_yaml_frontmatter_is_valid_for_quotes_and_newlines() {
        let entry = PluginEntry {
            slug: "evil",
            name: "Plugin \"X\" \\ alpha",
            description: "Adds \"warmth\".\nLine two with a \\ backslash.",
            params: &[],
            global_params: None,
            band_template: None,
        };

        let page = generate_plugin_page(&entry);
        let mut lines = page.lines();

        assert_eq!(lines.next(), Some("---"), "missing opening frontmatter");
        let title_line = lines.next().expect("title line");
        let desc_line = lines.next().expect("description line");
        let close = lines.next().expect("closing frontmatter line");
        assert_eq!(
            close, "---",
            "frontmatter must close after title+description"
        );

        assert!(
            title_line.starts_with("title: \"") && title_line.ends_with('"'),
            "title line not properly quoted: {title_line:?}"
        );
        assert!(
            desc_line.starts_with("description: \"") && desc_line.ends_with('"'),
            "description line not properly quoted: {desc_line:?}"
        );

        // No raw newlines or carriage returns inside the quoted values.
        let title_inner = &title_line["title: \"".len()..title_line.len() - 1];
        let desc_inner = &desc_line["description: \"".len()..desc_line.len() - 1];
        assert!(!title_inner.contains('\n') && !title_inner.contains('\r'));
        assert!(!desc_inner.contains('\n') && !desc_inner.contains('\r'));

        // Quotes must be escaped, backslashes doubled.
        assert!(
            title_line.contains("\\\"X\\\""),
            "title quote not escaped: {title_line:?}"
        );
        assert!(
            title_line.contains("\\\\"),
            "title backslash not escaped: {title_line:?}"
        );
        assert!(
            desc_line.contains("\\\"warmth\\\""),
            "desc quote not escaped: {desc_line:?}"
        );
        assert!(
            desc_line.contains("\\\\"),
            "desc backslash not escaped: {desc_line:?}"
        );
    }

    #[test]
    #[should_panic(expected = "out of range")]
    fn choice_default_index_out_of_range_panics() {
        let spec = ParamSpec {
            name: "Mode",
            engine_key: "mode",
            param_type: ParamType::Choice {
                default_index: 99,
                labels: &["A", "B"],
            },
            unit: "",
            group: "",
            update_mode: UpdateMode::Realtime,
            display_scale: 1.0,
            category: ParamCategory::Primary,
            doc: "",
        };
        let _ = format_default(&spec);
    }

    #[test]
    fn registry_has_no_duplicate_slugs() {
        let reg = plugin_registry();
        validate_registry(&reg);
    }

    #[test]
    fn parse_args_supports_root_and_check() {
        let args = parse_args_from([
            OsString::from("sotf-docs-gen"),
            OsString::from("--check"),
            OsString::from("--root"),
            OsString::from("/tmp/sotf"),
        ])
        .unwrap();
        assert_eq!(
            args,
            Args {
                root: Some(PathBuf::from("/tmp/sotf")),
                check: true
            }
        );
    }

    #[test]
    fn write_if_changed_reports_idempotence_and_check_only_drift() {
        let path = unique_temp_file("sotf-docs-gen-idempotence.md");
        assert!(write_if_changed(&path, "one\n", false));
        assert!(!write_if_changed(&path, "one\n", false));
        assert!(write_if_changed(&path, "two\n", true));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "one\n");
        std::fs::remove_file(path).unwrap();
    }

    fn unique_temp_file(name: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("{name}-{}-{nanos}", std::process::id()))
    }

