use super::types::PluginEntry;
use sotf_host::param_specs::ParamSpec;
use std::collections::HashSet;

const HAL_INPUT_PARAMS: &[ParamSpec] = &[ParamSpec::int(
    "Input Channels",
    "input_channels",
    2,
    1,
    16,
    1,
    "ch",
    "General",
)
.structural()
.doc("Number of HAL input channels")];

pub(super) fn plugin_registry() -> Vec<PluginEntry> {
    use sotf_plugins::param_specs;
    vec![
        PluginEntry {
            slug: "eq",
            name: "Parametric EQ",
            description: "Biquad-based parametric equalizer with peak, shelf, and pass filters. Supports multiple filter bands for precise frequency response shaping.",
            params: &[],
            global_params: Some(param_specs::eq::GLOBAL_PARAMS),
            band_template: Some(param_specs::eq::BAND_TEMPLATE),
        },
        PluginEntry {
            slug: "gain",
            name: "Gain",
            description: "Simple volume control with smooth gain ramping to prevent clicks.",
            params: param_specs::gain::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "compressor",
            name: "Compressor",
            description: "Dynamic range compression with configurable threshold, ratio, attack, release, and makeup gain.",
            params: param_specs::compressor::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "expander",
            name: "Expander",
            description: "Dynamic range expansion with configurable threshold, ratio, attack, release, and range. Opens up dynamics below the threshold.",
            params: param_specs::expander::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "multiband-compressor",
            name: "Multiband Compressor",
            description: "Per-band dynamic range compression with 2-5 frequency bands and independent compressor settings per band.",
            params: param_specs::multiband_compressor::PARAMS,
            global_params: Some(param_specs::multiband_compressor::GLOBAL_PARAMS),
            band_template: None,
        },
        PluginEntry {
            slug: "multiband-expander",
            name: "Multiband Expander",
            description: "Per-band dynamic range expansion with 2-5 frequency bands and independent expander settings per band.",
            params: param_specs::multiband_expander::PARAMS,
            global_params: Some(param_specs::multiband_expander::GLOBAL_PARAMS),
            band_template: None,
        },
        PluginEntry {
            slug: "gate",
            name: "Gate",
            description: "Noise gate that silences audio below a configurable threshold.",
            params: param_specs::gate::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "hal-input",
            name: "HAL Input",
            description: "Reads audio from a system HAL device into the engine. Used by the macOS system-wide daemon.",
            params: HAL_INPUT_PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "hal-output",
            name: "HAL Output",
            description: "Writes audio from the engine to a system HAL device. Pair with HAL Input to route system audio through a plugin chain.",
            params: &[],
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "limiter",
            name: "Limiter",
            description: "Peak limiter to prevent clipping. Ensures output never exceeds the ceiling level.",
            params: param_specs::limiter::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "delay",
            name: "Delay",
            description: "Audio delay with configurable delay time per channel.",
            params: param_specs::delay::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "convolution",
            name: "Convolution",
            description: "FFT-based convolution engine for applying impulse responses (room correction, cabinet simulation, reverb).",
            params: param_specs::convolution::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "matrix",
            name: "Matrix Mixer",
            description: "Channel matrix mixing with per-routing gain control. Route any input channel to any output channel.",
            params: param_specs::matrix::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "channel-mute-solo",
            name: "Channel Mute/Solo",
            description: "Per-channel mute, solo, and dim controls with smooth fade transitions.",
            params: param_specs::channel_mute_solo::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "upmixer",
            name: "Upmixer",
            description: "Stereo to surround upmixing (2ch to 5.0/5.1/7.1) using FFT-based spatial decomposition and VBAP panning.",
            params: param_specs::upmixer::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "downmix",
            name: "Downmix",
            description: "Surround to stereo downmixing with configurable channel contributions.",
            params: param_specs::downmix::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "binaural",
            name: "Binaural Renderer",
            description: "HRTF-based 3D spatial audio rendering. Converts multichannel audio to binaural headphone output using SOFA files.",
            params: param_specs::binaural::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "crossfeed",
            name: "Crossfeed",
            description: "Headphone crossfeed that simulates speaker spacing. Supports Bauer, Meier, and multiband algorithms.",
            params: param_specs::crossfeed::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "crossover",
            name: "Crossover",
            description: "N-way crossover with selectable filter family (LR24 or linear-phase FIR) and per-channel configuration.",
            params: param_specs::crossover::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "xtc",
            name: "Crosstalk Cancellation (XTC)",
            description: "Crosstalk cancellation for speaker playback. Creates a wider stereo image by cancelling inter-speaker interference.",
            params: param_specs::xtc::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "pnd",
            name: "Perceptual Noise Diffusion",
            description: "Perceptual noise diffusion (PND) for improving perceived audio quality through controlled noise shaping.",
            params: param_specs::pnd::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "resampler",
            name: "Resampler",
            description: "High-quality sample-rate converter using sinc interpolation. Supports fixed and dynamic resampling ratios.",
            params: param_specs::resampler::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "loudness-compensation",
            name: "Loudness Compensation",
            description: "Equal-loudness contour compensation (Fletcher-Munson). Adjusts frequency response based on playback volume to maintain perceived tonal balance.",
            params: param_specs::loudness_compensation::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "mono-to-stereo",
            name: "Mono to Stereo",
            description: "Converts mono signals to stereo output.",
            params: param_specs::mono_to_stereo::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "denoiser",
            name: "Denoiser",
            description: "Audio denoising using MCRA (Minima Controlled Recursive Averaging) and Wiener filtering.",
            params: param_specs::denoiser::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "ab-compare",
            name: "A/B Compare",
            description: "Side-by-side A/B comparison. Instantly toggle between processed and bypass to evaluate your plugin chain.",
            params: param_specs::ab_compare::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "band-split",
            name: "Band Split",
            description: "Splits the audio signal into separate frequency bands for independent processing.",
            params: param_specs::band_split::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "band-merge",
            name: "Band Merge",
            description: "Merges previously split frequency bands back into a single signal.",
            params: param_specs::band_merge::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "aec",
            name: "Acoustic Echo Cancellation",
            description: "Cancels acoustic echoes from microphone input using reference signal correlation.",
            params: param_specs::aec::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "beamformer",
            name: "Beamformer",
            description: "Microphone array beamforming for directional audio capture.",
            params: param_specs::beamformer::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "de-esser",
            name: "De-Esser",
            description: "Sibilance reduction targeting harsh high-frequency content (s, t, sh sounds).",
            params: param_specs::de_esser::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "dither",
            name: "Dither",
            description: "Adds dither noise for bit-depth reduction, minimizing quantization distortion.",
            params: param_specs::dither::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "dynamic-eq",
            name: "Dynamic EQ",
            description: "Frequency-dependent dynamic equalizer that adjusts filter gain based on signal level.",
            params: param_specs::dynamic_eq::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "linear-phase-eq",
            name: "FIR EQ",
            description: "Parametric FIR equalizer with selectable linear or minimum phase and FFT convolution.",
            params: param_specs::linear_phase_eq::PARAMS,
            global_params: None,
            band_template: Some(param_specs::linear_phase_eq::BAND_TEMPLATE),
        },
        PluginEntry {
            slug: "saturation",
            name: "Saturation",
            description: "Harmonic saturation and soft clipping for adding warmth and character.",
            params: param_specs::saturation::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "spectral-compressor",
            name: "Spectral Compressor",
            description: "Frequency-dependent compression operating in the spectral domain for transparent dynamic control.",
            params: param_specs::spectral_compressor::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "stereo-imager",
            name: "Stereo Imager",
            description: "Controls stereo width from mono to extra-wide, using mid/side processing.",
            params: param_specs::stereo_imager::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "transient-shaper",
            name: "Transient Shaper",
            description: "Shapes attack and sustain characteristics of audio transients.",
            params: param_specs::transient_shaper::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "ambisonics",
            name: "Ambisonics",
            description: "Ambisonics encoding and decoding for immersive spatial audio.",
            params: param_specs::ambisonics::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "spectrum-analyzer",
            name: "Spectrum Analyzer",
            description: "FFT-based spectrum analysis with configurable bin count, frequency range, smoothing, and tilt correction.",
            params: param_specs::spectrum::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "aae",
            name: "Active Acoustic Enhancement",
            description: "Active acoustic enhancement using psychoacoustic processing to improve perceived clarity, presence, and depth.",
            params: param_specs::aae::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "declick",
            name: "Declick",
            description: "Removes clicks, pops, and short transient defects from audio (vinyl restoration, recording artifacts).",
            params: param_specs::declick::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "hiss-reducer",
            name: "Hiss Reducer",
            description: "Reduces high-frequency hiss and tape noise while preserving program content.",
            params: param_specs::hiss_reducer::PARAMS,
            global_params: None,
            band_template: None,
        },
        PluginEntry {
            slug: "speech-denoiser",
            name: "Speech Denoiser",
            description: "Neural speech-focused denoiser (RNNoise-derived) optimized for voice and dialogue cleanup.",
            params: param_specs::speech_denoiser::PARAMS,
            global_params: None,
            band_template: None,
        },
    ]
}

pub(super) fn validate_registry(registry: &[PluginEntry]) {
    let mut seen = HashSet::new();
    for entry in registry {
        assert!(
            seen.insert(entry.slug),
            "duplicate slug in plugin registry: {}",
            entry.slug
        );
    }
}
