// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::QUIET_ZONE;
use gpui::{BorderStyle, Bounds, Corners, Edges, PaintQuad, Pixels, Rgba, Window, point, px, size};
use qrcode::QrCode as QrMatrix;
use qrcode::types::Color as QrColor;

/// Paint the full QR matrix (used by static QrCode).
pub(super) fn paint_qr_full(
    bounds: Bounds<Pixels>,
    matrix: &Option<QrMatrix>,
    size_f32: f32,
    fg_color: Rgba,
    bg_color: Rgba,
    window: &mut Window,
) {
    if bg_color.a > 0.0 {
        window.paint_quad(PaintQuad {
            bounds,
            corner_radii: Corners::default(),
            background: bg_color.into(),
            border_widths: Edges::default(),
            border_color: bg_color.into(),
            border_style: BorderStyle::default(),
        });
    }

    let Some(matrix) = matrix else { return };
    let modules = matrix.width();
    if modules == 0 {
        return;
    }

    let colors = matrix.to_colors();
    let total_modules = modules + QUIET_ZONE * 2;
    let module_px = size_f32 / total_modules as f32;
    let origin_x: f32 = bounds.origin.x.into();
    let origin_y: f32 = bounds.origin.y.into();

    for row in 0..modules {
        for col in 0..modules {
            if colors[row * modules + col] == QrColor::Dark {
                let x = origin_x + (col + QUIET_ZONE) as f32 * module_px;
                let y = origin_y + (row + QUIET_ZONE) as f32 * module_px;
                window.paint_quad(PaintQuad {
                    bounds: Bounds {
                        origin: point(px(x), px(y)),
                        size: size(px(module_px), px(module_px)),
                    },
                    corner_radii: Corners::default(),
                    background: fg_color.into(),
                    border_widths: Edges::default(),
                    border_color: fg_color.into(),
                    border_style: BorderStyle::default(),
                });
            }
        }
    }
}

/// Paint a pre-extracted color slice (used by AnimatedQrCode static path).
pub(super) fn paint_qr_static(
    bounds: Bounds<Pixels>,
    colors: &[QrColor],
    modules: usize,
    size_f32: f32,
    fg_color: Rgba,
    bg_color: Rgba,
    window: &mut Window,
) {
    if bg_color.a > 0.0 {
        window.paint_quad(PaintQuad {
            bounds,
            corner_radii: Corners::default(),
            background: bg_color.into(),
            border_widths: Edges::default(),
            border_color: bg_color.into(),
            border_style: BorderStyle::default(),
        });
    }

    if modules == 0 {
        return;
    }

    let total_modules = modules + QUIET_ZONE * 2;
    let module_px = size_f32 / total_modules as f32;
    let origin_x: f32 = bounds.origin.x.into();
    let origin_y: f32 = bounds.origin.y.into();

    for row in 0..modules {
        for col in 0..modules {
            if colors[row * modules + col] == QrColor::Dark {
                let x = origin_x + (col + QUIET_ZONE) as f32 * module_px;
                let y = origin_y + (row + QUIET_ZONE) as f32 * module_px;
                window.paint_quad(PaintQuad {
                    bounds: Bounds {
                        origin: point(px(x), px(y)),
                        size: size(px(module_px), px(module_px)),
                    },
                    corner_radii: Corners::default(),
                    background: fg_color.into(),
                    border_widths: Edges::default(),
                    border_color: fg_color.into(),
                    border_style: BorderStyle::default(),
                });
            }
        }
    }
}
