// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::AuDisplay;
use super::PENDING_VIEW;
use super::au_raw_window::AuRawWindow;
use super::au_window_ptr::AU_WINDOW;
use super::au_window_ptr::AuWindowPtr;
use super::fallback_atlas::FallbackAtlas;
use gpui::{
    AnyWindowHandle, Bounds, Capslock, DevicePixels, DispatchEventResult, GpuSpecs, Modifiers,
    Pixels, PlatformAtlas, PlatformDisplay, PlatformInput, PlatformInputHandler, PlatformWindow,
    Point, PromptButton, PromptLevel, RequestFrameOptions, Scene, Size, WindowAppearance,
    WindowBackgroundAppearance, WindowBounds, WindowControlArea, WindowParams, px, size,
};
use gpui_wgpu::{GpuContext, WgpuRenderer, WgpuSurfaceConfig};
use objc::{class, msg_send, runtime::Object, sel, sel_impl};
use parking_lot::Mutex;
use raw_window_handle::{
    AppKitDisplayHandle, AppKitWindowHandle, HasDisplayHandle, HasWindowHandle,
};
use std::{
    cell::{Cell, RefCell},
    ffi::c_void,
    ptr::NonNull,
    rc::Rc,
    sync::Arc,
};

/// Execute a callback with a reference to the current AU window, if any.
/// The mutex guard is held for the duration of the callback, ensuring the
/// window pointer remains valid.
pub(crate) fn with_au_window<F, R>(f: F) -> Option<R>
where
    F: FnOnce(&AuWindow) -> R,
{
    AuWindowPtr::assert_main_thread();
    let guard = AU_WINDOW.lock().ok()?;
    let ptr = guard.as_ref()?.0;
    if ptr.is_null() {
        return None;
    }
    Some(f(unsafe { &*ptr }))
}

pub(crate) struct AuWindow {
    /// The NSView we render into (owned by the Swift AUViewController)
    pub(super) view: *mut Object,
    pub(super) bounds: Cell<Bounds<Pixels>>,
    pub(super) scale_factor: Cell<f32>,
    pub(super) input_handler: RefCell<Option<PlatformInputHandler>>,
    pub(crate) request_frame_callback: RefCell<Option<Box<dyn FnMut(RequestFrameOptions)>>>,
    pub(super) input_callback:
        RefCell<Option<Box<dyn FnMut(PlatformInput) -> DispatchEventResult>>>,
    pub(super) active_status_callback: RefCell<Option<Box<dyn FnMut(bool)>>>,
    pub(super) hover_status_callback: RefCell<Option<Box<dyn FnMut(bool)>>>,
    pub(super) resize_callback: RefCell<Option<Box<dyn FnMut(Size<Pixels>, f32)>>>,
    pub(super) moved_callback: RefCell<Option<Box<dyn FnMut()>>>,
    pub(super) should_close_callback: RefCell<Option<Box<dyn FnMut() -> bool>>>,
    pub(super) hit_test_callback: RefCell<Option<Box<dyn FnMut() -> Option<WindowControlArea>>>>,
    pub(super) close_callback: RefCell<Option<Box<dyn FnOnce()>>>,
    pub(super) appearance_changed_callback: RefCell<Option<Box<dyn FnMut()>>>,
    pub(super) mouse_position: Cell<Point<Pixels>>,
    pub(super) modifiers: Cell<Modifiers>,
    pub(super) renderer: Mutex<Option<WgpuRenderer>>,
}

impl AuWindow {
    /// Create a new AU window that renders into the NSView from PENDING_VIEW.
    ///
    /// The NSView must have been set in the PENDING_VIEW thread-local by
    /// `gpui_au_create` before calling `app.run()` / `open_window()`.
    pub fn new(_handle: AnyWindowHandle, _params: WindowParams) -> anyhow::Result<Self> {
        use crate::helpers::nslog;
        nslog(b"SOTF AuWindow::new: entry");

        let view_info = PENDING_VIEW.with(|pv| pv.borrow_mut().take());
        let (ns_view, width, height, scale) = match view_info {
            Some(info) => {
                nslog(b"SOTF AuWindow::new: PENDING_VIEW found");
                (info.ns_view, info.width, info.height, info.scale)
            }
            None => {
                nslog(b"SOTF AuWindow::new: No PENDING_VIEW -- creating without renderer");
                return Ok(Self {
                    view: std::ptr::null_mut(),
                    bounds: Cell::new(Bounds {
                        origin: Default::default(),
                        size: size(px(600.0), px(400.0)),
                    }),
                    scale_factor: Cell::new(2.0),
                    input_handler: RefCell::new(None),
                    request_frame_callback: RefCell::new(None),
                    input_callback: RefCell::new(None),
                    active_status_callback: RefCell::new(None),
                    hover_status_callback: RefCell::new(None),
                    resize_callback: RefCell::new(None),
                    moved_callback: RefCell::new(None),
                    should_close_callback: RefCell::new(None),
                    hit_test_callback: RefCell::new(None),
                    close_callback: RefCell::new(None),
                    appearance_changed_callback: RefCell::new(None),
                    mouse_position: Cell::new(Point::default()),
                    modifiers: Cell::new(Modifiers::default()),
                    renderer: Mutex::new(None),
                });
            }
        };

        // Configure the NSView with a CAMetalLayer for wgpu rendering.
        nslog(b"SOTF AuWindow::new: setting up CAMetalLayer");
        unsafe {
            let _: () = msg_send![ns_view, setWantsLayer: true];

            // Create a CAMetalLayer and set it as the view's layer
            let metal_layer: *mut Object = msg_send![class!(CAMetalLayer), layer];
            let _: () =
                msg_send![metal_layer, setContentsScale: scale as core_graphics::base::CGFloat];
            // Match the view's bounds
            let view_bounds: core_graphics::geometry::CGRect = msg_send![ns_view, bounds];
            let _: () = msg_send![metal_layer, setFrame: view_bounds];
            let _: () = msg_send![ns_view, setLayer: metal_layer];
        }

        let au_window = Self {
            view: ns_view,
            bounds: Cell::new(Bounds {
                origin: Default::default(),
                size: size(px(width), px(height)),
            }),
            scale_factor: Cell::new(scale),
            input_handler: RefCell::new(None),
            request_frame_callback: RefCell::new(None),
            input_callback: RefCell::new(None),
            active_status_callback: RefCell::new(None),
            hover_status_callback: RefCell::new(None),
            resize_callback: RefCell::new(None),
            moved_callback: RefCell::new(None),
            should_close_callback: RefCell::new(None),
            hit_test_callback: RefCell::new(None),
            close_callback: RefCell::new(None),
            appearance_changed_callback: RefCell::new(None),
            mouse_position: Cell::new(Point::default()),
            modifiers: Cell::new(Modifiers::default()),
            renderer: Mutex::new(None),
        };

        // Initialize wgpu renderer (Metal backend)
        nslog(b"SOTF AuWindow::new: initializing wgpu renderer");
        let pixel_w = (width * scale) as i32;
        let pixel_h = (height * scale) as i32;

        let config = WgpuSurfaceConfig {
            size: size(DevicePixels(pixel_w), DevicePixels(pixel_h)),
            transparent: false,
            preferred_present_mode: None,
        };

        // Create a lightweight raw window handle for WgpuRenderer::new().
        // WgpuRenderer::new handles instance + surface creation internally.
        let raw_window = AuRawWindow {
            ns_view: ns_view as *mut c_void,
        };
        let gpu_context: GpuContext = Rc::new(RefCell::new(None));

        nslog(b"SOTF AuWindow::new: creating wgpu renderer");
        match WgpuRenderer::new(gpu_context, &raw_window, config, None) {
            Ok(renderer) => {
                nslog(b"SOTF AuWindow::new: wgpu renderer created OK");
                *au_window.renderer.lock() = Some(renderer);
            }
            Err(e) => {
                let msg = format!("SOTF AuWindow::new: wgpu renderer FAILED: {e:#}");
                nslog(msg.as_bytes());
            }
        }

        Ok(au_window)
    }

    /// Register this window in the global AU_WINDOW slot.
    /// Called from AuPlatform::open_window after Boxing.
    pub(crate) fn register_global(boxed: &AuWindow) {
        use crate::helpers::nslog;
        let ptr: *const AuWindow = boxed;
        if let Ok(mut guard) = AU_WINDOW.lock() {
            *guard = Some(AuWindowPtr(ptr));
        }
        let msg = format!("SOTF AuWindow: registered at {:p}", ptr);
        nslog(msg.as_bytes());
    }

    /// Request a frame render (called from Swift via FFI)
    #[allow(dead_code)]
    pub fn request_frame(&self) {
        let cb = self.request_frame_callback.borrow_mut().take();
        if let Some(mut cb) = cb {
            cb(RequestFrameOptions::default());
            let mut slot = self.request_frame_callback.borrow_mut();
            if slot.is_none() {
                *slot = Some(cb);
            }
        }
    }

    /// Handle resize from the host (called from Swift via FFI)
    pub fn handle_resize(&self, width: f32, height: f32, scale: f32) {
        let new_size = size(px(width), px(height));
        self.bounds.set(Bounds {
            origin: Default::default(),
            size: new_size,
        });
        self.scale_factor.set(scale);

        // Update Metal layer scale and frame
        if !self.view.is_null() {
            unsafe {
                let layer: *mut Object = msg_send![self.view, layer];
                let _: () =
                    msg_send![layer, setContentsScale: scale as core_graphics::base::CGFloat];
                let new_frame = core_graphics::geometry::CGRect {
                    origin: core_graphics::geometry::CGPoint { x: 0.0, y: 0.0 },
                    size: core_graphics::geometry::CGSize {
                        width: width as f64,
                        height: height as f64,
                    },
                };
                let _: () = msg_send![layer, setFrame: new_frame];
            }
        }

        // Update wgpu surface
        let pixel_w = (width * scale) as i32;
        let pixel_h = (height * scale) as i32;
        {
            let mut guard = self.renderer.lock();
            if let Some(renderer) = guard.as_mut() {
                renderer.update_drawable_size(size(DevicePixels(pixel_w), DevicePixels(pixel_h)));
            }
        }

        // Fire resize callback
        let cb = self.resize_callback.borrow_mut().take();
        if let Some(mut cb) = cb {
            cb(new_size, scale);
            let mut slot = self.resize_callback.borrow_mut();
            if slot.is_none() {
                *slot = Some(cb);
            }
        }
    }

    /// Dispatch a mouse event (called from Swift via FFI)
    pub fn dispatch_input(&self, event: PlatformInput) {
        // Update tracked mouse position for MouseMove/Down/Up
        match &event {
            PlatformInput::MouseDown(e) => self.mouse_position.set(e.position),
            PlatformInput::MouseUp(e) => self.mouse_position.set(e.position),
            PlatformInput::MouseMove(e) => self.mouse_position.set(e.position),
            _ => {}
        }

        if let Some(callback) = self.input_callback.borrow_mut().as_mut() {
            callback(event);
        }
    }
}

impl HasWindowHandle for AuWindow {
    fn window_handle(
        &self,
    ) -> std::result::Result<raw_window_handle::WindowHandle<'_>, raw_window_handle::HandleError>
    {
        let view = NonNull::new(self.view as *mut c_void)
            .ok_or(raw_window_handle::HandleError::Unavailable)?;
        let handle = AppKitWindowHandle::new(view);
        Ok(unsafe { raw_window_handle::WindowHandle::borrow_raw(handle.into()) })
    }
}

impl HasDisplayHandle for AuWindow {
    fn display_handle(
        &self,
    ) -> std::result::Result<raw_window_handle::DisplayHandle<'_>, raw_window_handle::HandleError>
    {
        let handle = AppKitDisplayHandle::new();
        Ok(unsafe { raw_window_handle::DisplayHandle::borrow_raw(handle.into()) })
    }
}

impl PlatformWindow for AuWindow {
    fn bounds(&self) -> Bounds<Pixels> {
        self.bounds.get()
    }

    fn is_maximized(&self) -> bool {
        false
    }

    fn window_bounds(&self) -> WindowBounds {
        WindowBounds::Windowed(self.bounds.get())
    }

    fn content_size(&self) -> Size<Pixels> {
        self.bounds.get().size
    }

    fn resize(&mut self, _size: Size<Pixels>) {
        // Resize is driven externally by the host via handle_resize
    }

    fn scale_factor(&self) -> f32 {
        self.scale_factor.get()
    }

    fn appearance(&self) -> WindowAppearance {
        if self.view.is_null() {
            return WindowAppearance::Light;
        }
        unsafe {
            let effective: *mut Object = msg_send![self.view, effectiveAppearance];
            if effective.is_null() {
                return WindowAppearance::Light;
            }
            let name: *mut Object = msg_send![effective, name];
            if name.is_null() {
                return WindowAppearance::Light;
            }
            let dark_aqua: *mut Object = msg_send![class!(NSString), stringWithUTF8String: c"NSAppearanceNameDarkAqua".as_ptr()];
            let is_dark: bool = msg_send![name, isEqualToString: dark_aqua];
            if is_dark {
                WindowAppearance::Dark
            } else {
                WindowAppearance::Light
            }
        }
    }

    fn display(&self) -> Option<Rc<dyn PlatformDisplay>> {
        Some(Rc::new(AuDisplay::main()))
    }

    fn mouse_position(&self) -> Point<Pixels> {
        self.mouse_position.get()
    }

    fn modifiers(&self) -> Modifiers {
        self.modifiers.get()
    }

    fn capslock(&self) -> Capslock {
        Capslock { on: false }
    }

    fn set_input_handler(&mut self, input_handler: PlatformInputHandler) {
        *self.input_handler.borrow_mut() = Some(input_handler);
    }

    fn take_input_handler(&mut self) -> Option<PlatformInputHandler> {
        self.input_handler.borrow_mut().take()
    }

    fn prompt(
        &self,
        _level: PromptLevel,
        _msg: &str,
        _detail: Option<&str>,
        _answers: &[PromptButton],
    ) -> Option<futures::channel::oneshot::Receiver<usize>> {
        // No prompt support in AU extensions
        None
    }

    fn activate(&self) {}

    fn is_active(&self) -> bool {
        true // AU view is always considered active when visible
    }

    fn is_hovered(&self) -> bool {
        false
    }

    fn set_title(&mut self, _title: &str) {}

    fn background_appearance(&self) -> WindowBackgroundAppearance {
        WindowBackgroundAppearance::Opaque
    }

    fn set_background_appearance(&self, _background_appearance: WindowBackgroundAppearance) {}

    fn minimize(&self) {}
    fn zoom(&self) {}
    fn toggle_fullscreen(&self) {}

    fn is_fullscreen(&self) -> bool {
        false
    }

    fn on_request_frame(&self, callback: Box<dyn FnMut(RequestFrameOptions)>) {
        *self.request_frame_callback.borrow_mut() = Some(callback);
    }

    fn on_input(&self, callback: Box<dyn FnMut(PlatformInput) -> DispatchEventResult>) {
        *self.input_callback.borrow_mut() = Some(callback);
    }

    fn on_active_status_change(&self, callback: Box<dyn FnMut(bool)>) {
        *self.active_status_callback.borrow_mut() = Some(callback);
    }

    fn on_hover_status_change(&self, callback: Box<dyn FnMut(bool)>) {
        *self.hover_status_callback.borrow_mut() = Some(callback);
    }

    fn on_resize(&self, callback: Box<dyn FnMut(Size<Pixels>, f32)>) {
        *self.resize_callback.borrow_mut() = Some(callback);
    }

    fn on_moved(&self, callback: Box<dyn FnMut()>) {
        *self.moved_callback.borrow_mut() = Some(callback);
    }

    fn on_should_close(&self, callback: Box<dyn FnMut() -> bool>) {
        *self.should_close_callback.borrow_mut() = Some(callback);
    }

    fn on_hit_test_window_control(&self, callback: Box<dyn FnMut() -> Option<WindowControlArea>>) {
        *self.hit_test_callback.borrow_mut() = Some(callback);
    }

    fn on_close(&self, callback: Box<dyn FnOnce()>) {
        *self.close_callback.borrow_mut() = Some(callback);
    }

    fn on_appearance_changed(&self, callback: Box<dyn FnMut()>) {
        *self.appearance_changed_callback.borrow_mut() = Some(callback);
    }

    fn draw(&self, scene: &Scene) {
        let mut guard = self.renderer.lock();
        if let Some(renderer) = guard.as_mut() {
            renderer.draw(scene);
        }
    }

    fn sprite_atlas(&self) -> Arc<dyn PlatformAtlas> {
        let guard = self.renderer.lock();
        if let Some(renderer) = guard.as_ref() {
            renderer.sprite_atlas().clone()
        } else {
            Arc::new(FallbackAtlas::new())
        }
    }

    fn is_subpixel_rendering_supported(&self) -> bool {
        false
    }

    fn gpu_specs(&self) -> Option<GpuSpecs> {
        let guard = self.renderer.lock();
        guard.as_ref().map(|r| r.gpu_specs())
    }

    fn update_ime_position(&self, _bounds: Bounds<Pixels>) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_with_au_window_returns_none_when_unregistered() {
        // Ensure that with_au_window returns None when no window is registered
        let result = with_au_window(|_window| 42);
        assert!(result.is_none());
    }
}
