[package]
name = "math-iir-fir"
version = "0.5.14"
description = "Math-Audio IIR and FIR filters"
edition = { workspace = true }
keywords.workspace = true
categories.workspace = true
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
ndarray = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }
rustfft = { workspace = true }
num-complex = { workspace = true }
hound = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "biquad_bench"
harness = false

[lib]
name = "math_audio_iir_fir"
path = "src/mod.rs"
