//! BEM (Boundary Element Method) solver integration
//!
//! This module provides integration with external BEM solvers for high-accuracy HRTF simulation.
//!
//! # Supported BEM Solvers
//!
//! ## MESH2HRTF
//! - Open-source BEM solver specifically for HRTF computation
//! - Website: https://mesh2hrtf.org/
//! - Input: Triangle mesh + source/receiver positions
//! - Output: Frequency-domain transfer functions
//!
//! ## Integration Workflow
//! 1. Export mesh to BEM-compatible format (Wavefront OBJ or custom)
//! 2. Generate BEM configuration file
//! 3. Run BEM solver (external process)
//! 4. Import results and convert to time-domain impulse responses
//! 5. Write to SOFA format

use crate::acoustics::model::AcousticHeadModel;
use crate::error::{ScannerError, ScannerResult};
use crate::mesh::Mesh;
use nalgebra::Point3;
use std::path::{Path, PathBuf};
use std::process::Command;

/// BEM solver configuration
#[derive(Debug, Clone)]
pub struct BEMConfig {
    /// Path to BEM solver executable
    pub solver_path: PathBuf,

    /// Frequency range for simulation (Hz)
    pub freq_min: f32,
    pub freq_max: f32,

    /// Number of frequency points
    pub num_frequencies: usize,

    /// Speed of sound (m/s)
    pub speed_of_sound: f32,

    /// Mesh refinement level (higher = more accurate but slower)
    pub refinement_level: u8,
}

impl Default for BEMConfig {
    fn default() -> Self {
        Self {
            solver_path: PathBuf::from("mesh2hrtf"),
            freq_min: 100.0,          // 100 Hz
            freq_max: 20000.0,        // 20 kHz
            num_frequencies: 512,
            speed_of_sound: 343.0,    // m/s at 20°C
            refinement_level: 1,
        }
    }
}

/// BEM solver interface
pub struct BEMSolver {
    config: BEMConfig,
}

impl BEMSolver {
    /// Create a new BEM solver
    pub fn new(config: BEMConfig) -> Self {
        Self { config }
    }

    /// Export mesh to BEM-compatible format
    ///
    /// Exports to Wavefront OBJ format with specific requirements for BEM:
    /// - All faces must be triangles
    /// - Mesh must be closed (watertight)
    /// - Normals pointing outward
    pub fn export_mesh_for_bem(&self, mesh: &Mesh, output_path: &Path) -> ScannerResult<()> {
        log::info!("Exporting mesh for BEM solver: {:?}", output_path);

        // Validate mesh is suitable for BEM
        self.validate_mesh_for_bem(mesh)?;

        // Export to OBJ format
        mesh.export_obj(output_path.to_str().unwrap())?;

        log::info!("✓ Mesh exported for BEM");
        Ok(())
    }

    /// Validate that mesh meets BEM requirements
    fn validate_mesh_for_bem(&self, mesh: &Mesh) -> ScannerResult<()> {
        // Check minimum vertex count
        if mesh.vertex_count() < 100 {
            return Err(ScannerError::InvalidConfig(
                "Mesh too coarse for BEM (need at least 100 vertices)".to_string(),
            ));
        }

        // Note: Additional validation would check:
        // - Mesh is closed (no holes)
        // - All normals point outward
        // - No degenerate triangles
        // These checks are complex and omitted here for brevity

        log::info!(
            "Mesh validation: {} vertices, {} triangles",
            mesh.vertex_count(),
            mesh.triangle_count()
        );

        Ok(())
    }

    /// Generate BEM configuration file
    ///
    /// Creates a configuration file for the BEM solver with:
    /// - Mesh path
    /// - Source positions
    /// - Receiver positions (ears)
    /// - Frequency range
    pub fn generate_bem_config(
        &self,
        model: &AcousticHeadModel,
        source_positions: &[Point3<f32>],
        output_path: &Path,
    ) -> ScannerResult<()> {
        log::info!("Generating BEM configuration: {:?}", output_path);

        // Generate MESH2HRTF-compatible configuration
        let config_content = self.create_mesh2hrtf_config(model, source_positions);

        std::fs::write(output_path, config_content)
            .map_err(|e| ScannerError::Io(format!("Failed to write BEM config: {}", e)))?;

        log::info!("✓ BEM configuration generated");
        Ok(())
    }

    /// Create MESH2HRTF configuration content
    fn create_mesh2hrtf_config(
        &self,
        model: &AcousticHeadModel,
        source_positions: &[Point3<f32>],
    ) -> String {
        let mut config = String::new();

        // Header
        config.push_str("# MESH2HRTF Configuration\n");
        config.push_str("# Generated by head-scanner\n\n");

        // Frequency settings
        config.push_str(&format!(
            "frequencyRange {} {} {}\n",
            self.config.freq_min, self.config.freq_max, self.config.num_frequencies
        ));

        // Speed of sound
        config.push_str(&format!("speedOfSound {}\n", self.config.speed_of_sound));

        // Mesh refinement
        config.push_str(&format!("refinement {}\n", self.config.refinement_level));

        // Receiver positions (ears) - relative to head center
        config.push_str("\n# Receiver positions (ears)\n");
        let left_rel = model.left_ear - model.head_center;
        let right_rel = model.right_ear - model.head_center;

        config.push_str(&format!(
            "receiver 0 {} {} {}\n",
            left_rel.x / 100.0,
            left_rel.y / 100.0,
            left_rel.z / 100.0
        ));
        config.push_str(&format!(
            "receiver 1 {} {} {}\n",
            right_rel.x / 100.0,
            right_rel.y / 100.0,
            right_rel.z / 100.0
        ));

        // Source positions
        config.push_str("\n# Source positions\n");
        for (i, pos) in source_positions.iter().enumerate() {
            let rel = pos - model.head_center;
            config.push_str(&format!(
                "source {} {} {} {}\n",
                i,
                rel.x / 100.0,
                rel.y / 100.0,
                rel.z / 100.0
            ));
        }

        config
    }

    /// Run BEM solver (external process)
    ///
    /// This launches the BEM solver as an external process.
    /// **Note**: This can take hours for full HRTF computation!
    pub fn run_bem_simulation(
        &self,
        mesh_path: &Path,
        config_path: &Path,
        output_dir: &Path,
    ) -> ScannerResult<()> {
        log::info!("Starting BEM simulation...");
        log::warn!(
            "BEM simulation can take several hours. Consider running overnight."
        );

        // Check if solver exists
        if !self.config.solver_path.exists() {
            return Err(ScannerError::InvalidConfig(format!(
                "BEM solver not found: {:?}\nInstall MESH2HRTF from https://mesh2hrtf.org/",
                self.config.solver_path
            )));
        }

        // Run BEM solver
        let output = Command::new(&self.config.solver_path)
            .arg("--mesh")
            .arg(mesh_path)
            .arg("--config")
            .arg(config_path)
            .arg("--output")
            .arg(output_dir)
            .output()
            .map_err(|e| {
                ScannerError::Io(format!("Failed to execute BEM solver: {}", e))
            })?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(ScannerError::InvalidConfig(format!(
                "BEM simulation failed:\n{}",
                stderr
            )));
        }

        log::info!("✓ BEM simulation completed");
        Ok(())
    }

    /// Import BEM results and convert to impulse responses
    ///
    /// BEM solvers typically output frequency-domain data.
    /// This function:
    /// 1. Reads frequency-domain transfer functions
    /// 2. Applies inverse FFT to get time-domain impulse responses
    /// 3. Resamples to target sample rate if needed
    pub fn import_bem_results(
        &self,
        bem_output_dir: &Path,
        target_sample_rate: f32,
    ) -> ScannerResult<(Vec<Point3<f32>>, Vec<Vec<Vec<f32>>>)> {
        log::info!("Importing BEM results from {:?}", bem_output_dir);

        // Look for output files
        // MESH2HRTF typically creates:
        // - ObjectMesh_hrtf.nc (NetCDF format)
        // - or individual .txt files per source/receiver

        let hrtf_file = bem_output_dir.join("ObjectMesh_hrtf.nc");

        if !hrtf_file.exists() {
            return Err(ScannerError::InvalidConfig(format!(
                "BEM output file not found: {:?}",
                hrtf_file
            )));
        }

        // TODO: Implement NetCDF parsing and IFFT
        // This requires:
        // 1. NetCDF library (netcdf or hdf5)
        // 2. FFT library (rustfft)
        // 3. Conversion from frequency domain to time domain

        Err(ScannerError::InvalidConfig(
            "BEM result import not yet implemented. Use analytical HRTF for now.".to_string(),
        ))
    }
}

/// Helper function to check if BEM solver is available
pub fn is_bem_available() -> bool {
    // Check common installation locations
    let common_paths = [
        "mesh2hrtf",
        "/usr/local/bin/mesh2hrtf",
        "/opt/mesh2hrtf/bin/mesh2hrtf",
    ];

    for path in &common_paths {
        if Path::new(path).exists() {
            return true;
        }
    }

    false
}

/// Get estimated time for BEM simulation
///
/// Returns rough estimate in hours based on:
/// - Number of sources
/// - Number of frequencies
/// - Mesh complexity
pub fn estimate_bem_time(
    num_sources: usize,
    num_frequencies: usize,
    mesh_vertex_count: usize,
) -> f32 {
    // Very rough estimate (actual time varies greatly)
    // Assumes modern workstation with 8+ cores
    let complexity_factor = (mesh_vertex_count as f32 / 1000.0).sqrt();
    let freq_factor = num_frequencies as f32 / 100.0;
    let source_factor = num_sources as f32;

    // Base time per source per frequency: ~1 second
    let total_seconds = complexity_factor * freq_factor * source_factor;

    total_seconds / 3600.0 // Convert to hours
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bem_config_default() {
        let config = BEMConfig::default();
        assert_eq!(config.freq_min, 100.0);
        assert_eq!(config.freq_max, 20000.0);
        assert_eq!(config.speed_of_sound, 343.0);
    }

    #[test]
    fn test_time_estimation() {
        // Small simulation: 10 sources, 100 freqs, 500 vertices
        let time_small = estimate_bem_time(10, 100, 500);
        assert!(time_small < 1.0); // Less than 1 hour

        // Large simulation: 1000 sources, 512 freqs, 5000 vertices
        let time_large = estimate_bem_time(1000, 512, 5000);
        assert!(time_large > 10.0); // More than 10 hours
    }

    #[test]
    fn test_bem_availability() {
        // This will fail unless MESH2HRTF is installed
        let available = is_bem_available();
        println!("BEM solver available: {}", available);
    }
}
