// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::plot::filter_color::filter_color;
use crate::plot::ref_lines::make_ref_lines;
use crate::plot::trend_lines::{
    calculate_tonal_balance, create_regression_trace, generate_regression_line,
};
use ndarray::Array1;
use plotly::common::{AxisSide, Mode};
use plotly::layout::{AxisType, GridPattern, LayoutGrid, RowOrder};
use plotly::{Layout, Plot, Scatter};
use std::collections::HashMap;

mod consts;
mod create;
mod misc;
mod plot;
#[cfg(test)]
mod tests;

pub use misc::*;
pub use plot::*;
