//! Measurement source handling (single file or averaging)

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

mod inline_measurement;
mod load;
mod measurement_ref;
mod measurement_single;
mod measurement_source;
#[cfg(test)]
mod tests;
mod types;

pub use inline_measurement::*;
pub use load::*;
pub use measurement_ref::*;
pub use measurement_single::*;
pub use measurement_source::*;
pub use types::*;
