// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::default::default_min_q;
use super::default::default_sub_max_db;
use super::default::default_sub_max_q;
use super::default::default_sub_min_db;
use super::default::default_sub_num_filters;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Subwoofer-specific optimizer overrides
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct SubOptimizerConfig {
    /// Number of PEQ filters for subwoofer channels
    #[serde(default = "default_sub_num_filters")]
    pub num_filters: usize,
    /// Maximum boost in dB (room gain can be 15+ dB at resonances)
    #[serde(default = "default_sub_max_db")]
    pub max_db: f64,
    /// Maximum cut in dB
    #[serde(default = "default_sub_min_db")]
    pub min_db: f64,
    /// Minimum Q factor
    #[serde(default = "default_min_q")]
    pub min_q: f64,
    /// Maximum Q factor (higher Q for narrow room modes)
    #[serde(default = "default_sub_max_q")]
    pub max_q: f64,
}

impl Default for SubOptimizerConfig {
    fn default() -> Self {
        Self {
            num_filters: default_sub_num_filters(),
            max_db: default_sub_max_db(),
            min_db: default_sub_min_db(),
            min_q: default_min_q(),
            max_q: default_sub_max_q(),
        }
    }
}
