// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::default::default_true;
use super::default::default_validation_lufs;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Validation/listening-test descriptor generation.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct ValidationBundleConfig {
    /// Generate a JSON validation bundle descriptor alongside RoomEQ output.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Include ABX descriptors for before/after listening checks.
    #[serde(default = "default_true")]
    pub abx: bool,
    /// Include MUSHRA descriptors for multi-condition preference tests.
    #[serde(default = "default_true")]
    pub mushra: bool,
    /// Include perceptual regression summaries and advisories.
    #[serde(default = "default_true")]
    pub perceptual_regression_summary: bool,
    /// Loudness target for matched program-material assets.
    #[serde(default = "default_validation_lufs")]
    pub target_lufs: f64,
}

impl Default for ValidationBundleConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            abx: true,
            mushra: true,
            perceptual_regression_summary: true,
            target_lufs: default_validation_lufs(),
        }
    }
}
