name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc g++ pkg-config libssl-dev ca-certificates

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        run: |
          cargo install just
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install for Linux
        run: |
          sudo just install-linux-root
          sudo just install-ubuntu-common
          sudo just install-ubuntu-x86
          just post-install-npm
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          JUST_JUSTFILE: $GITHUB_WORKSPACE/Justfile

      - name: Build
        run: just build
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          BROWSER_PATH: /usr/bin/chromium-browser
          WEBDRIVER_PATH: /usr/bin/chromedriver

      - name: Run tests
        run: just test
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          BROWSER_PATH: /usr/bin/chromium-browser
          WEBDRIVER_PATH: /usr/bin/chromedriver

      - name: QA for AutoEQ
        run: just qa
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          BROWSER_PATH: /usr/bin/chromium-browser
          WEBDRIVER_PATH: /usr/bin/chromedriver
