name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt update
          apt install -y build-essential gcc g++ pkg-config libssl-dev ca-certificates

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        run: |
          cargo install just
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install for Linux
        run: |
          just install-ubuntu-x86
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          JUST_JUSTFILE: $GITHUB_WORKSPACE/Justfile

      - name: Build
        run: cargo build --verbose
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          BROWSER_PATH: /usr/bin/chromium-browser
          WEBDRIVER_PATH: /usr/bin/chromedriver

      - name: Run tests
        run: cargo test --verbose
        env:
          AUTOEQ_DIR: $GITHUB_WORKSPACE
          BROWSER_PATH: /usr/bin/chromium-browser
          WEBDRIVER_PATH: /usr/bin/chromedriver
